packages:
  # --- COMMON PACKAGES ---
  <<: !include_dir_named common
  <<: !include_dir_named bluetooth

  # --- BOARD AND MODULES ---
  board: !include board/upesy_wroom.yaml
  i2c_internal: !include board/extension/internal_i2c.yaml
  bme280: !include board/module/bme280_i2c.yaml

substitutions:
  common:
    log_level: WARN
#    log_baud_rate: "115200"
  device:
    name: ble-relay1
    location: "1etg, Kjøkken"
    framework:
      type: esp-idf
  extension:
    i2c:
      internal:
        frequency: 100kHz

esphome:
  comment: "BLE Relay"
  name: ${device.name}
  friendly_name: ${device.name}
  area: ${device.location}

esp32:
    framework:
      type: esp-idf
