packages:
  # --- COMMON PACKAGES ---
  <<: !include_dir_named common
  <<: !include_dir_named bluetooth

  # --- BOARD AND MODULES ---
  board: !include board/upesy_wroom.yaml
  i2c_internal: !include board/extension/internal_i2c.yaml
  bme280: !include board/module/bme280_i2c.yaml

substitutions:
  devicename: ble-relay1
  log_level: WARN
  location: "1etg, Kjøkken"
  i2c_internal_frequency: 100kHz

esphome:
  comment: "BLE Relay"
  name: $devicename
  friendly_name: $devicename
  area: $location

esp32:
    framework:
      type: esp-idf
