packages:
  # --- COMMON PACKAGES ---
  <<: !include_dir_named common
  <<: !include_dir_named bluetooth

  # --- BOARD AND MODULES ---
  board: !include board/upesy_wroom.yaml
  bme280: !include board/module/chip_temp_bme280.yaml

substitutions:
  common:
    log_level: WARN
#    log_baud_rate: "115200"
  device:
    name: ble-relay1
    location: "Storage"
    framework:
      type: esp-idf

esphome:
  comment: "BLE Relay"
  name: ${device.name}
  friendly_name: ${device.name}
  area: ${device.location}

wifi:
#  use_address: 192.168.69.53
  use_address: ${device.name}.local
  manual_ip: 
    gateway: 192.168.68.1
    subnet: 255.255.252.0
    static_ip: 192.168.71.90

esp32:
    framework:
      type: esp-idf
