packages:
  # --- COMMON PACKAGES ---
  <<: !include_dir_named common

  # --- BOARD AND MODULES ---
  board: !include board/esp32s3_cam_n16r8_mb.yaml
  ai-on-the-edge: !include board/module/ai_on_the_edge.yaml

substitutions:
  common:
    log_level: DEBUG
#    log_baud_rate: "115200"
  device:
    name: esp32-s3-cam-d28abc
    location: "Storage"
    framework:
      type: esp-idf
  module:
    ai_on_the_edge:
      camera:
        flash_light: rgb_led
        resolution: 800x600
        jpeg_quality: 10
        agc_gain_ceiling: 128x
        wb_mode: cloudy

esphome:
  comment: ${device.model} @ ${device.location}
  name: ${device.name}
  friendly_name: ${device.name}
  area: ${device.location}

wifi:
  use_address: ${device.name}.local
  manual_ip: 
    gateway: 192.168.68.1
    subnet: 255.255.252.0
    static_ip: 192.168.71.97

#globals:
#  - id: !extend global_crop_zones
    # 1024x768 numbers
#    initial_value: '"[[3,8,49,90],[49,8,93,90],[94,9,138,90],[141,10,186,91],[189,12,233,91],[236,11,279,91],[285,12,326,91],[331,13,373,91],[378,15,422,92]]"'

esp32_camera_utils:
  debug: true
  # 800x600 crop zone
#  camera_window:
#    offset_x: 480 # multiple of 4
#    offset_y: 500 # multiple of 4
#    width: 432 # multiple of 8
#    height: 104 # multiple of 8
#  camera_window:
#    offset_x: 472 # multiple of 4
#    offset_y: 492 # multiple of 4
#    width: 432 # multiple of 8
#    height: 104 # multiple of 8
  # 1024x768 crop zone
#  camera_window:
#    offset_x: 456 # multiple of 4
#    offset_y: 488 # multiple of 4
#    width: 440 # multiple of 8
#    height: 112 # multiple of 8

meter_reader_tflite:
  debug: true
  
tflite_micro_helper:
  debug: true

