packages:
  # --- COMMON PACKAGES ---
  <<: !include_dir_named common

  # --- BOARD AND MODULES ---
  board: !include board/esp32s3_cam_n16r8_freenove.yaml

substitutions:
  common:
    log_level: DEBUG
#    log_baud_rate: "115200"
  device:
    name: esp32-s3-cam-freenove-74f5d4
    location: "Storage"
    framework:
      type: esp-idf
  module:
    camera:
      resolution: 1024x768
      jpeg_quality: 20
      agc_gain_ceiling: 64x

esphome:
  comment: ${device.model} @ ${device.location}
  name: ${device.name}
  friendly_name: ${device.name}
  area: ${device.location}

wifi:
  use_address: ${device.name}.local
  manual_ip: 
    gateway: 192.168.68.1
    subnet: 255.255.252.0
    static_ip: 192.168.71.96

output:
  # fan output
  - platform: ledc
    id: fan_output
    pin: ${pin.ext.h2.p5}
    max_power: 0.75
    min_power: 0.15
    zero_means_zero: true
  # led output
  - platform: ledc
    id: flash_led_output
    pin: ${pin.ext.h2.p17}
    frequency: 4882Hz
    min_power: 0.05
    zero_means_zero: true

fan:
  - platform: speed
    output: fan_output
    id: fan_speed
    name: "Cooling Fan"
    speed_count: 10
    restore_mode: RESTORE_DEFAULT_OFF
    entity_category: config

sensor:
  - platform: pulse_counter
    id: fan_rpm
    pin:
      number: ${pin.ext.h2.p6}
      mode: INPUT_PULLUP
    count_mode:
      rising_edge: INCREMENT
      falling_edge: DISABLE
    filters:
      - multiply: 0.5
#      - lambda: |-
#          if (x <= 9900) return x;
#          else return 9900;
#      - lambda: |-
#          if (x >= 8500) return x;
#          else return 0;
    unit_of_measurement: RPM
    update_interval: 10s
    
light:
  - platform: monochromatic
    output: flash_led_output
    id: flash_led_light
    name: "Flash LED"
    default_transition_length: 400ms
    restore_mode: RESTORE_DEFAULT_OFF
    entity_category: config

display:
  - platform: lcd_pcf8574
    id: display_lcd
    address: 0x27
    dimensions: 16x2
    update_interval: 5s
    lambda: |-
      // Print a sensor value with 0 digits after the decimal
      it.printf(0, 0, "CPU:%.0f", id(cpu_temperature).state);
      // Result: "CPU:42"
      
      // Print a sensor value with 0 digits after the decimal
      it.printf(6, 0, "  FAN:%4.0f", id(fan_rpm).state);
      // Result: "  FAN:8500"
      
      // Result: "CPU:42  FAN:8500"

      // Print the current time
      it.strftime(0, 1, " %H:%M    %d.%m ", id(time_homeassistant).now());
      // Result for 10:06 on august 21st -> " 10:06  21.08 "
