packages:
  # --- COMMON PACKAGES ---
  <<: !include_dir_named common

  # --- BOARD AND MODULES ---
  board: !include board/esp32s3_cam_n16r8_freenove.yaml

substitutions:
  common:
    log_level: DEBUG
#    log_baud_rate: "115200"
  device:
    name: esp32-s3-cam-freenove-74f5d4
    location: "Storage"
    framework:
      type: esp-idf
  module:
    camera:
      resolution: 1024x768
      jpeg_quality: 20
      agc_gain_ceiling: 64x

esphome:
  comment: ${device.model} @ ${device.location}
  name: ${device.name}
  friendly_name: ${device.name}
  area: ${device.location}

wifi:
  use_address: ${device.name}.local
  manual_ip: 
    gateway: 192.168.68.1
    subnet: 255.255.252.0
    static_ip: 192.168.71.96

output:
  # fan output
  - platform: ledc
    id: fan_output
    pin: ${pin.ext.h2.p5}
  # led output
  - platform: ledc
    id: flash_led_output
    pin: ${pin.ext.h2.p17}
    min_power: 0.15
    zero_means_zero: true

fan:
  - platform: speed
    output: fan_output
    id: fan_speed
    name: "Cooling Fan"
    speed_count: 5
    restore_mode: RESTORE_DEFAULT_OFF
    entity_category: config
    
light:
  - platform: monochromatic
    output: flash_led_output
    id: flash_led_light
    name: "Flash LED"
    default_transition_length: 200ms
    restore_mode: RESTORE_DEFAULT_OFF
    entity_category: config

display:
  - platform: lcd_pcf8574
    id: display_lcd
    address: 0x27
    dimensions: 16x2
    update_interval: 5s
    lambda: |-
      // Print 0 at the top left
      it.print("0");

      // Print 1 at the second row and second column.
      it.print(1, 1, "1");

      // Let's write a sensor value (let's assume it's 42.1)
      it.printf("%.1f", id(cpu_temperature).state);
      // Result: "42.1" (the dot will appear on the segment showing "2")

      // Print a right-padded sensor value with 0 digits after the decimal
      it.printf("Sensor value: %8.0f", id(cpu_temperature).state);
      // Result: "Sensor value:       42"

      // Print the current time
      it.strftime("It is %H:%M on %d.%m.%Y", id(time_homeassistant).now());
      // Result for 10:06 on august 21st 2018 -> "It is 10:06 on 21.08.2018"
