packages:
  # --- COMMON PACKAGES ---
  <<: !include_dir_named common

  # --- BOARD AND MODULES ---
  board: !include board/esp32s3_cam_n8r8_eye.yaml

substitutions:
  common:
    log_level: DEBUG
#    log_baud_rate: "115200"
  device:
    name: esp32-s3-cam-d56278
    location: "Storage"
    framework:
      type: esp-idf
  module:
    camera:
      resolution: 1024x768
      jpeg_quality: 20
      agc_gain_ceiling: 64x

esphome:
  comment: ${device.model} @ ${device.location}
  name: ${device.name}
  friendly_name: ${device.name}
  area: ${device.location}

wifi:
  use_address: ${device.name}.local
  manual_ip: 
    gateway: 192.168.68.1
    subnet: 255.255.252.0
    static_ip: 192.168.71.100

light:
  - platform: esp32_rmt_led_strip
    id: rgb_led
    rgb_order: GRB
    pin: ${pin.ext.h2.p2}
    num_leds: 4
    rmt_symbols: ${device.rmt_symbols_block}
    chipset: ws2812
    color_correct: [90%, 90%, 90%]
    effects:
      - pulse:
      - strobe:
      - strobe:
          name: "Slow Blink" # 200ms on, 1500ms off
          colors:
            - state: true
              brightness: 25%
              red: 100%
              green: 0%
              blue: 0%
              duration: 500ms
              transition_length: 500ms
            - state: false
              duration: 2000ms
              transition_length: 1000ms
    default_transition_length: 100ms
    initial_state:
      state: true
      brightness: 50%
      color_brightness: 100%
      red: 100%
      green: 0%
      blue: 0%
    name: "LED"
    entity_category: config
