packages:
  # --- COMMON PACKAGES ---
  <<: !include_dir_named common

  # --- BOARD AND MODULES ---
  board: !include board/esp32_cam_ai_thinker.yaml
  ai-on-the-edge: !include board/module/ai_on_the_edge.yaml

substitutions:
  common:
    log_level: WARN
#    log_baud_rate: "115200"
  device:
    name: esp32-cam-74f5d4
    location: "Kjøkken"
    framework:
      type: esp-idf
  module:
    ai_on_the_edge:
      camera:
        resolution: 800x600
        jpeg_quality: 20
      meter:
        last_valid_value: "000016494"

esphome:
  comment: ${device.model} @ ${device.location}
  name: ${device.name}
  friendly_name: ${device.name}
  area: ${device.location}

wifi:
  use_address: ${device.name}.local
  manual_ip: 
    gateway: 192.168.68.1
    subnet: 255.255.252.0
    static_ip: 192.168.71.94

globals:
  - id: !extend global_crop_zones
  # 800x600 numbers
    initial_value: '"[[3,8,49,90],[49,8,93,90],[94,9,138,90],[141,10,186,91],[189,12,233,91],[236,11,279,91],[285,12,326,91],[331,13,373,91],[378,15,422,92]]"'

esp32_camera_utils: