substitutions:
  name: everything-presence-lite-5ba4c0
  friendly_name: EPL-5ba4c0
  illuminance_update_interval: "5s"
  log_level: ERROR
  location: "1etg, Inngang"

packages:
  # --- COMMON PACKAGES ---
  <<: !include_dir_named bluetooth
  time: !include common/time.yaml
  status: !include common/status.yaml

  # --- BOARD AND MODULES ---
  EverythingSmartTechnology.Everything_Presence_Lite: github://everythingsmarthome/everything-presence-lite/everything-presence-lite-ha-no-ble.yaml@main
  tweaks: !include board/everything_presence_lite.yaml

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  area: $location

esp32:
  framework:
    advanced:
      assertion_level: DISABLE
