substitutions:
  name: everything-presence-pro-e65644
  friendly_name: EPP-e65644
  log_level: "ERROR"
  device_config:
    bluetooth_enabled: true
  device:
    name: everything-presence-pro-e65644
    friendly_name: EPP-e65644
    location: "TV Stue"

packages:
  # --- COMMON PACKAGES ---
  <<: !include_dir_named bluetooth
  time: !include common/time.yaml
  status: !include common/status.yaml

  # --- BOARD AND MODULES ---
  EverythingSmartTechnology.Everything Presence Pro: github://everythingsmarthome/everything-presence-pro/everything-presence-pro-wifi-co2.yaml@main
  tweaks: !include board/everything_presence_pro.yaml

esphome:
  comment: ${device.model} @ ${device.location}
  name: ${device.name}
  name_add_mac_suffix: false
  friendly_name: ${device.friendly_name}
  area: ${device.location}

esp32_ble:
  max_connections: 2
esp32_ble_tracker:
  scan_parameters:
    interval: 500ms
    window: 10ms
bluetooth_proxy:
  active: false
  connection_slots: 1
