substitutions:
  name: everything-presence-lite-aa2aa0
  friendly_name: EPL-aa2aa0
  illuminance_update_interval: "5s"
  log_level: ERROR
  location: "1etg, Kjøkken"

packages:
  EverythingSmartTechnology.Everything_Presence_Lite: github://everythingsmarthome/everything-presence-lite/everything-presence-lite-ha-no-ble.yaml@main
  <<: !include_dir_named bluetooth
  time: !include common/time.yaml
  status: !include common/status.yaml

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
  area: $location

api:
  encryption:
    key: !secret homeassistant_api

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  enable_btm: true
  enable_rrm: true
