substitutions:
  name: everything-presence-lite-5cdaf8
  friendly_name: EPL-5cdaf8
  log_level: ERROR
  device_config:
    bluetooth_enabled: true
  device:
    name: everything-presence-lite-5cdaf8
    friendly_name: EPL-5cdaf8
    location: "Gang"

packages:
  # --- COMMON PACKAGES ---
  <<: !include_dir_named bluetooth
  time: !include common/time.yaml
  status: !include common/status.yaml

  # --- BOARD AND MODULES ---
  EverythingSmartTechnology.Everything_Presence_Lite: github://everythingsmarthome/everything-presence-lite/everything-presence-lite-ha-no-ble.yaml@main
  tweaks: !include board/everything_presence_lite.yaml

esphome:
  comment: ${device.model} @ ${device.location}
  name: ${device.name}
  name_add_mac_suffix: false
  friendly_name: ${device.friendly_name}
  area: ${device.location}

wifi:
#  use_address: 192.168.69.85
  use_address: everything-presence-lite-5cdaf8.local
  manual_ip:
    gateway: 192.168.68.1
    subnet: 255.255.252.0
    static_ip: 192.168.71.24

esp32_ble:
  max_connections: 2
esp32_ble_tracker:
  scan_parameters:
    interval: 500ms
    window: 10ms
bluetooth_proxy:
  active: false
  connection_slots: 1
