packages:
  # --- COMMON PACKAGES ---
  <<: !include_dir_named common
#  <<: !include_dir_named bluetooth

  # --- BOARD AND MODULES ---
  board: !include board/geekmagic_smalltv_pro.yaml

  # --- GUI PACKAGES ---
  colors: !include gui/themes/colors_night_owl.yaml
  lvgl: !include gui/240x240.yaml

  # --- LVGL WIDGET PACKAGES ---
  room_temperature_widget_sensors: !include { file: gui/widgets/labels/number_sensor.yaml, vars: {
    uid: room_temp_value,
    entity_id: sensor.t22_temperature
  }}

substitutions:
  devicename: gm-smalltv-pro-ee703c
  log_level: WARN
#  log_baud_rate: "115200"
  home_page: page_temperature

esphome:
  comment: "GeekMagic SmallTV Pro"
  name: ${devicename}
  friendly_name: ${devicename}
  project:
    version: "1.0.0"

# --- LVGL CLOCKS ---
time:
  - id: !extend time_homeassistant
    on_time_sync:
      - script.execute: lvgl_time_update
    on_time:
      - minutes: '*'
        seconds: 0
        then:
          - script.execute: lvgl_time_update

lvgl:
  buffer_size: 50%

binary_sensor:
  # Call sensors from HA.
  - platform: homeassistant
    entity_id: binary_sensor.etg2_simen_occupancy
    id: motion_simen
  - platform: homeassistant
    entity_id: binary_sensor.etg2_gang_occupancy
    id: motion_gang
  # Turn on display while room is occupied
  - platform: template
    id: motion_detected
    lambda: !lambda |-
      if ( (id(motion_simen).state) or (id(motion_gang).state) ) {
        return true;
      } else {
        return false;
      }
    on_state: 
      then:
        - script.execute: display_on_off

  # Touchpad
  - id: !extend touch_pad
    on_press:
      - lvgl.page.next
