packages:
  # --- COMMON PACKAGES ---
  <<: !include_dir_named common

  # --- BOARD AND MODULES ---
  board: !include board/jc4880p443ciwy.yaml

  # --- GUI PACKAGES ---
  colors: !include gui/themes/colors_night_owl.yaml
  lvgl: !include gui/800x480.yaml

  # --- LVGL WIDGET PACKAGES ---
  room_temperature_widget_sensors: !include { file: gui/widgets/labels/number_sensor.yaml, vars: {
    uid: room_temp_value,
    entity_id: sensor.t22_temperature
  }}

substitutions:
  common:
    log_level: DEBUG
#    log_baud_rate: "115200"
  device:
    name: jc4880p443
    location: "Storage"
    framework:
      type: esp-idf
  display:
    home_page: page_analog_clock

esphome:
  comment: ${device.model} @ ${device.location}
  name: ${device.name}
  friendly_name: ${device.name}
  area: ${device.location}

wifi:
  use_address: ${device.name}.local
  manual_ip: 
    gateway: 192.168.68.1
    subnet: 255.255.252.0
    static_ip: 192.168.71.36

# --- LVGL CLOCKS ---
time:
  - id: !extend time_homeassistant
    on_time_sync:
      - script.execute: lvgl_time_update
    on_time:
      - minutes: '*'
        seconds: 0
        then:
          - script.execute: lvgl_time_update

