packages:
  <<: !include_dir_named common
  <<: !include_dir_named bluetooth
  board: !include board/m5stack_atom_s3_lite_esp_idf.yaml
  extension: !include board/extension/i2c_port_abc.yaml
  env: !include board/module/unit_env_iv.yaml
  pir: !include board/module/unit_pir.yaml

substitutions:
  devicename: m5s-as3-lite-b6873c
  env_i2c_bus: i2c_port_abc
  pir_in_pin: $in_port_abc_pin

esphome:
  comment: "M5Stack Atom S3 Lite b6873c"
  name: $devicename
  friendly_name: $devicename
  platformio_options:
    build_flags:
      - "-w" # https://docs.platformio.org/en/latest/projectconf/sections/env/options/build/build_flags.html

esp32:
#  framework:
#    type: arduino
  framework:
    type: esp-idf
    version: 5.3.1
    platform_version: 6.9.0
    # Custom sdkconfig options
    sdkconfig_options: # https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/kconfig.html#config-compiler-disable-gcc12-warnings
      CONFIG_SPIFFS_DBG: n
