packages:
  <<: !include_dir_named common
  <<: !include_dir_named bluetooth
  board: !include board/m5stack_coreink.yaml
#  internal_i2c: !include board/extension/internal_i2c.yaml
  hat: !include board/extension/hat_i2c.yaml
  grove: !include board/extension/grove_i2c.yaml
  env_iii: !include board/module/hat_env_iii.yaml
  env_iv: !include board/module/unit_env_iv.yaml
  co2: !include board/module/unit_co2.yaml
  <<: !include_dir_named gui/lvgl/epaper

substitutions:
  devicename: m5s-coreink-9fc2c8
  location: "2etg, Simen"
  i2c_grove_frequency: 40kHz
  log_level: WARN
  default_font: f20

esphome:
  comment: "M5Stack CoreInk @ Simen"
  name: $devicename
  friendly_name: $devicename
  area: $location
  project: 
    version: "1.0.0"
  on_boot:
    - priority: 800
      then:
        # Bypass sleep circuit arduino
  #      - lambda: |-
  #          pinMode(GPIO_NUM_12, OUTPUT);
  #          digitalWrite(GPIO_NUM_12, HIGH);
  #          gpio_hold_en(GPIO_NUM_12);
        # Bypass sleep circuit esp-idf
        - lambda: |-
            gpio_set_direction(GPIO_NUM_12, GPIO_MODE_OUTPUT);
            gpio_set_level(GPIO_NUM_12, 1);
            gpio_hold_en(GPIO_NUM_12);
            gpio_deep_sleep_hold_en();
    - priority: -100
      then:
        - component.update: display_eink
        - wait_until:
            condition:
              lambda: 'return id(data_updated) == true;'
        # Wait a bit longer so all the items are received
        - delay: 5s
        - logger.log: "Initial sensor data received: Refreshing display..."
        - lambda: 'id(initial_data_received) = true;'
        - lvgl.page.show: page_home
        - script.execute: update_screen

esp32:
  framework:
    type: esp-idf

api:
  on_client_connected:
    then:
      - lvgl.widget.show: img_hastatus
  on_client_disconnected:
    then:
      - lvgl.widget.hide: img_hastatus

wifi:
  enable_btm: true
  enable_rrm: true
  on_connect:
    then:
      - lvgl.widget.show: img_wifistatus
  on_disconnect:
    then:
      - lvgl.widget.hide: img_wifistatus

lvgl:
  log_level: WARN
  buffer_size: 25%

  bg_color: paper_white
  disp_bg_color: paper_white
  default_font: $default_font

  top_layer:
    widgets:
      # Status icons
#      - image:
#          id: img_wifistatus
#          align: bottom_left
#          y: -1
#          x: 1
#          hidden: true
#          src: i_wifi
      - label:
          id: img_wifistatus
          text: "\U000F05A9" # mdi-wifi
          text_font: f_mdi_s
          align: bottom_left
#      - image:
#          id: img_hastatus
#          align: bottom_right
#          y: -1
#          x: -1
#          hidden: true
#          src: i_api
      - label:
          id: img_hastatus
          text: "\U000F07D0" # mdi-home-assistant
          text_font: f_mdi_s
          align: bottom_right
      # Display update timestamp
      - label:
          id: lbl_disp_updated
          align: bottom_mid
          text: "?"
          text_font: f20b
      # Header nav
      - obj:
          align: top_mid
          width: 100%
          height: 32
          bg_color: paper_white
          bg_opa: TRANSP
          layout:
            type: GRID
            grid_columns: [ FR(2), FR(2), FR(2), FR(5) ]
            grid_rows: [ FR(1) ]
          widgets:
#            - image:
#                id: img_home
#                grid_cell_column_pos: 0
#                grid_cell_row_pos: 0
#                grid_cell_x_align: center
#                grid_cell_y_align: center
#                src: i_home
            - label:
                text: "\U000F02DC" # mdi-home
                text_font: f_mdi_s
                text_align: center
                grid_cell_column_pos: 0
                grid_cell_row_pos: 0
                grid_cell_x_align: center
                grid_cell_y_align: center
#            - image:
#                id: img_refresh
#                grid_cell_column_pos: 1
#                grid_cell_row_pos: 0
#                grid_cell_x_align: center
#                grid_cell_y_align: center
#                src: i_refresh
            - label:
                text: "\U000F0450" # mdi-refresh
                text_font: f_mdi_s
                text_align: center
                grid_cell_column_pos: 1
                grid_cell_row_pos: 0
                grid_cell_x_align: center
                grid_cell_y_align: center
#            - image:
#                id: img_next
#                grid_cell_column_pos: 2
#                grid_cell_row_pos: 0
#                grid_cell_x_align: center
#                grid_cell_y_align: center
#                src: i_next
            - label:
                text: "\U000F0055" # mdi-arrow-right-thick
                text_font: f_mdi_s
                text_align: center
                grid_cell_column_pos: 2
                grid_cell_row_pos: 0
                grid_cell_x_align: center
                grid_cell_y_align: center

  pages:
    - id: page_home
      widgets:
        - obj:
            align: top_mid
            styles: header_footer
#            bg_color: paper_white
#            bg_opa: COVER
            widgets:
#              - image:
#                  src: i_temp_room
#                  align: top_right
#                  y: 1
#                  x: -1
              - label:
                  text: "Rom"
                  text_font: f25b
                  text_align: right
                  align: top_right
        - obj:
            align: center
            width: 100%
            height: 136
#            bg_color: paper_white
            pad_all: 0
            layout:
              type: GRID
              grid_columns: [ FR(1), FR(3), FR(1) ]
              grid_rows: [ 6px, 130px ]
            widgets:
              - label:
                  id: graph_temp_room
                  text: "?"
                  grid_cell_column_pos: 0
                  grid_cell_column_span: 3
                  grid_cell_row_pos: 0
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  text_font: f16
#              - image:
#                  src: i_temp_l
#                  grid_cell_column_pos: 0
#                  grid_cell_row_pos: 1
#                  grid_cell_x_align: start
#                  grid_cell_y_align: center
              - label:
                  text: "\U000F050F" # mdi-thermometer
                  text_font: f_mdi_m
                  grid_cell_column_pos: 0
                  grid_cell_row_pos: 1
                  grid_cell_x_align: start
                  grid_cell_y_align: center
              - label:
                  id: lbl_temp_room_value
                  text: "?"
                  grid_cell_column_pos: 1
                  grid_cell_row_pos: 1
                  grid_cell_x_align: center
                  grid_cell_y_align: center
                  text_font: f100b
                  text_color: paper_black
              - label:
                  id: lbl_temp_room_unit
                  text: "°C"
                  grid_cell_column_pos: 2
                  grid_cell_row_pos: 1
                  grid_cell_x_align: end
                  grid_cell_y_align: center
                  text_align: right
                  text_font: f32b
                  text_color: paper_black

    - id: page_temp
      widgets:
        - obj:
            align: top_mid
            styles: header_footer
#            bg_color: paper_white
#            bg_opa: COVER
            widgets:
#              - image:
#                  src: i_temp_s
#                  align: top_right
#                  y: 1
#                  x: -1
              - label:
                  text: "Enhet"
                  text_font: f25b
                  text_align: right
                  align: top_right
        - obj:
            align: center
            width: 100%
            height: 136
#            bg_color: paper_white
            pad_all: 0
            layout:
              type: GRID
              grid_columns: [ FR(1), FR(3), FR(1) ]
              grid_rows: [ 6px, 130px ]
            widgets:
              - label:
                  id: graph_temp_local
                  text: "?"
                  grid_cell_column_pos: 0
                  grid_cell_column_span: 3
                  grid_cell_row_pos: 0
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  text_font: f16
#              - image:
#                  src: i_temp_l
#                  grid_cell_column_pos: 0
#                  grid_cell_row_pos: 1
#                  grid_cell_x_align: start
#                  grid_cell_y_align: center
              - label:
                  text: "\U000F050F" # mdi-thermometer
                  text_font: f_mdi_m
                  grid_cell_column_pos: 0
                  grid_cell_row_pos: 1
                  grid_cell_x_align: start
                  grid_cell_y_align: center
              - label:
                  id: lbl_temp_local_value
                  text: "?"
                  grid_cell_column_pos: 1
                  grid_cell_row_pos: 1
                  grid_cell_x_align: center
                  grid_cell_y_align: center
                  text_font: f100b
                  text_color: paper_black
              - label:
                  id: lbl_temp_local_unit
                  text: "°C"
                  grid_cell_column_pos: 2
                  grid_cell_row_pos: 1
                  grid_cell_x_align: end
                  grid_cell_y_align: center
                  text_align: right
                  text_font: f32b
                  text_color: paper_black

font:
  - file:
      type: gfonts
      family: Noto Sans Display
      weight: 500
    id: f16
    size: 16
    glyphs: &norwegian-glyphs [ ' ', ',', '.', ':', '%', '°', '@', '?','~',
      '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '-', '/',
      'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N',
      'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'Æ', 'Ø', 'Å',
      'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n',
      'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'æ', 'ø', 'å']
  - file:
      type: gfonts
      family: Noto Sans Display
      weight: 800
    id: f16b
    size: 16
    glyphs: *norwegian-glyphs
  - file:
      type: gfonts
      family: Noto Sans Display
      weight: 500
    id: f18
    size: 18
    glyphs: *norwegian-glyphs
  - file:
      type: gfonts
      family: Noto Sans Display
      weight: 500
    id: f20
    size: 20
    glyphs: *norwegian-glyphs
  - file:
      type: gfonts
      family: Noto Sans Display
      weight: 800
    id: f20b
    size: 20
    glyphs: *norwegian-glyphs
  - file:
      type: gfonts
      family: Noto Sans Display
      weight: 700
    id: f25b
    size: 25
    glyphs: *norwegian-glyphs
  - file:
      type: gfonts
      family: Noto Sans Display
      weight: 700
    id: f32b
    size: 32
    glyphs: *norwegian-glyphs
  - file:
      type: gfonts
      family: Noto Sans Display
      weight: 600
    id: f100b
    size: 100
    glyphs: *norwegian-glyphs

  # icons
  - file: gui/fonts/materialdesignicons-webfont.ttf
    id: f_mdi_s
    size: 32
    glyphs: [
      "\U000F05A9", # mdi-wifi
      "\U000F07D0", # mdi-home-assistant

      "\U000F0450", # mdi-refresh
      "\U000F0055", # mdi-arrow-right-thick
      "\U000F02DC", # mdi-home
      
      "\U000F02FC", # mdi-information
      "\U000F0F54", # mdi-home-thermometer

      "\U000F050F", # mdi-thermometer
      ]
  - file: gui/fonts/materialdesignicons-webfont.ttf
    id: f_mdi_m
    size: 36
    glyphs: [
      "\U000F050F", # mdi-thermometer
      ]

#image:
#  - id: i_wifi
#    file: mdi:wifi
#    type: binary
#    resize: 28x28
#  - id: i_api
#    file: mdi:home-assistant
#    type: binary
#    resize: 28x28

#  - id: i_refresh
#    file: mdi:refresh
#    type: binary
#    resize: 28x28
#  - id: i_next
#    file: mdi:arrow-right-thick
#    type: binary
#    resize: 28x28
#  - id: i_home
#    file: mdi:home
#    type: binary
#    resize: 28x28

#  - id: i_information
#    file: mdi:information
#    type: binary
#    resize: 28x28
#  - id: i_temp_room
#    file: mdi:home-thermometer
#    type: binary
#    resize: 28x28

#  - id: i_temp_s
#    file: mdi:thermometer
#    type: binary
#    resize: 28x28
#  - id: i_temp_l
#    file: mdi:thermometer
#    type: binary
#    resize: 32x32

#graph:
#  - id: graph_temperature_room
#    duration: 8h
#    x_grid: 15min
#    y_grid: 1.0
#    width: 200
#    height: 50
#    border: false
#    traces:
#      - sensor: temperature_feels_like
#        line_thickness: 6
#        continuous: true
#  - id: graph_temperature_local
#    duration: 6h
#    x_grid: 15min
#    y_grid: 1.0
#    width: 200
#    height: 70
#    border: false
#    traces:
#      - sensor: temperature_local
#        line_thickness: 6
#        continuous: true

# Check if person is home
binary_sensor:
  - platform: homeassistant
    entity_id: binary_sensor.etg2_occupancy
    id: motion_detected

sensor:
  # Call sensors from HA.
#  - platform: homeassistant
#    entity_id: sensor.etg2_simen_temperature
#    id: temperature_homeassistant
#    on_value:
#      then:
#        - lambda: 'id(data_updated) = true;'
  - platform: homeassistant
    entity_id: sensor.etg2_simen_tc_heatindex
    id: temperature_feels_like
    on_value:
      then:
        - lvgl.label.update:
            id: lbl_temp_room_value
            text:
              format: "%.0f"
              args: [ 'x' ]
        - lvgl.label.update:
            id: lbl_disp_updated
            text:
              time_format: "%H:%M"
              time: !lambda return id(time_homeassistant).now();
        - lambda: 'id(data_updated) = true;'

  # Combine sensors
  - platform: combination
    type: median
    id: temperature_local
    name: "Temperature"
    device_class: "temperature"
    state_class: "measurement"
    sources:
      # ENV III
      - source: temperature_sht30_hat_env
      - source: temperature_qmp6988_hat_env
      # ENV IV
      - source: temperature_bmp280_unit_env
      - source: temperature_sht40_unit_env
      # ENV Pro
#      - source: temperature_bme688
      # CO2
      - source: temperature_scd40_unit_co2
    filters:
      - or:
        - heartbeat: 900s
        - delta: 0.15
    on_value:
      then:
        - lvgl.label.update:
            id: lbl_temp_local_value
            text:
              format: "%.0f"
              args: [ 'x' ]
        - lvgl.label.update:
            id: lbl_disp_updated
            text:
              time_format: "%H:%M"
              time: !lambda return id(time_homeassistant).now();
        - lambda: 'id(data_updated) = true;'

  - platform: combination
    type: median
    id: humidity_local
    name: "Humidity"
    device_class: "humidity"
    state_class: "measurement"
    sources:
      # ENV III
      - source: humidity_sht30_hat_env
      # ENV IV
      - source: humidity_sht40_unit_env
      # ENV Pro
#      - source: humidity_bme688
      # CO2
      - source: humidity_scd40_unit_co2
    filters:
      - or:
        - heartbeat: 900s
        - delta: 0.15

  - platform: combination
    type: median
    id: pressure_local
    name: "Pressure"
    device_class: "atmospheric_pressure"
    state_class: "measurement"
    sources:
      # ENV III
      - source: pressure_qmp6988_hat_env
      # ENV IV
      - source: pressure_bmp280_unit_env
      # ENV Pro
#      - source: pressure_bme688
    filters:
      - or:
        - heartbeat: 900s
        - delta: 0.15