packages:
  <<: !include_dir_named common
  <<: !include_dir_named bluetooth
  board: !include board/m5stack_atom_s3.yaml
  hat: !include board/extension/i2c_hat.yaml
  env: !include board/module/hat_env_iii.yaml

substitutions:
  devicename: m5s-as3-b5c828

esphome:
  comment: "M5Stack Atom S3 b5c828"
  name: $devicename
  friendly_name: $devicename

esp32:
  framework:
    type: esp-idf
    sdkconfig_options: # https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/kconfig.html#config-compiler-disable-gcc12-warnings
      CONFIG_SPIFFS_DBG: n

display:
  - platform: ili9xxx
    model: st7789v
    id: display_lcd
    cs_pin: $disp_cs_pin
    dc_pin: $disp_dc_pin
    reset_pin: $disp_reset_pin
    data_rate: 40Mhz
    invert_colors: true
    update_interval: 1s
    dimensions:
      height: 128
      width: 128
      offset_height: 1
      offset_width: 2
    # Rotate 180deg
    transform:
      mirror_x: true
      mirror_y: true
    pages:
      - id: page_local
        lambda: |-
          // Frame
          //it.rectangle(0,  0, it.get_width(), it.get_height(), id(c_yellow));

          it.print(-1, -2, id(f20b), id(c_gray), TextAlign::TOP_LEFT, "HAT");
          it.print(it.get_width()+1, -2, id(f24b), id(c_gray), TextAlign::TOP_RIGHT, "°C");
          
          it.printf(it.get_width()/2, it.get_height()/2, id(f60b), id(c_white), TextAlign::CENTER, "%2.0f", id(temperature_local).state);

          // Show wifi icon.
          if (id(component_wifi).is_connected()) {
            it.image(-1, it.get_height()+1, id(i_wifi), ImageAlign::BOTTOM_LEFT, id(c_green), COLOR_OFF);
          }
          // Show HA icon.
          if (id(component_api).is_connected()) {
            it.image(it.get_width()+1, it.get_height()+1, id(i_api), ImageAlign::BOTTOM_RIGHT, Color(0x00daff), COLOR_OFF);
          }

          it.strftime(it.get_width()/2, it.get_height()+3, id(f18), id(c_gray), TextAlign::BOTTOM_CENTER, "%H:%M", id(time_homeassistant).now());
      - id: page_room
        lambda: |-
          // Frame
          //it.rectangle(0,  0, it.get_width(), it.get_height(), id(c_yellow));

          it.print(-1, -2, id(f20b), id(c_gray), TextAlign::TOP_LEFT, "Rom");
          it.print(it.get_width()+1, -2, id(f24b), id(c_gray), TextAlign::TOP_RIGHT, "°C");

          // Show wifi icon.
          if (id(component_wifi).is_connected()) {
            it.image(-1, it.get_height()+1, id(i_wifi), ImageAlign::BOTTOM_LEFT, id(c_green), COLOR_OFF);
          }
          // Show HA icon.
          if (id(component_api).is_connected()) {
            it.image(it.get_width()+1, it.get_height()+1, id(i_api), ImageAlign::BOTTOM_RIGHT, Color(0x00daff), COLOR_OFF);
          }

          it.strftime(it.get_width()/2, it.get_height()+3, id(f18), id(c_gray), TextAlign::BOTTOM_CENTER, "%H:%M", id(time_homeassistant).now());

sensor:
  # Combine sensors
  - platform: combination
    type: median
    id: temperature_local
    name: "Temperature"
    device_class: "temperature"
    sources:
      # ENV III
      - source: temperature_sht3xd
      - source: temperature_qmp6988
      # ENV IV
#      - source: temperature_bmp280
#      - source: temperature_sht4x
    filters:
      - or:
        - heartbeat: 900s
        - delta: 0.15

font:
  - file:
      type: gfonts
      family: Noto Sans Display
      weight: 500
    id: f14
    size: 14
    glyphs: &norwegian-glyphs [ ' ', ',', '.', ':', '%', '°', '@', '?','~',
      '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '-', '/',
      'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N',
      'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'Æ', 'Ø', 'Å',
      'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n',
      'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'æ', 'ø', 'å']
  - file:
      type: gfonts
      family: Noto Sans Display
      weight: 500
    id: f18
    size: 18
    glyphs: *norwegian-glyphs
  - file:
      type: gfonts
      family: Noto Sans Display
      weight: 500
    id: f20
    size: 20
    glyphs: *norwegian-glyphs
  - file:
      type: gfonts
      family: Noto Sans Display
      weight: 700
    id: f20b
    size: 20
    glyphs: *norwegian-glyphs
  - file:
      type: gfonts
      family: Noto Sans Display
      weight: 500
    id: f24
    size: 24
    glyphs: *norwegian-glyphs
  - file:
      type: gfonts
      family: Noto Sans Display
      weight: 700
    id: f24b
    size: 24
    glyphs: *norwegian-glyphs
  - file:
      type: gfonts
      family: Noto Sans Display
      weight: 500
    id: f32
    size: 32
    glyphs: *norwegian-glyphs
  - file:
      type: gfonts
      family: Noto Sans Display
      weight: 700
    id: f32b
    size: 32
    glyphs: *norwegian-glyphs
  - file:
      type: gfonts
      family: Noto Sans Display
      weight: 500
    id: f60
    size: 60
    glyphs: *norwegian-glyphs
  - file:
      type: gfonts
      family: Noto Sans Display
      weight: 700
    id: f60b
    size: 60
    glyphs: *norwegian-glyphs

image:
  - id: i_wifi
    file: mdi:wifi
    type: binary
    resize: 24x24
  - id: i_api
    file: mdi:home-assistant
    type: binary
    resize: 24x24