packages:
  <<: !include_dir_named common
# might be too weak for BLE ?
#  <<: !include_dir_named bluetooth
  board: !include board/m5stack_nano_c6.yaml
  grove: !include board/extension/grove_i2c.yaml
  env: !include board/module/unit_env_iv.yaml

substitutions:
  devicename: m5s-nano-c6-1d8ec8

esphome:
  comment: "M5Stack NanoC6 1d8ec8"
  name: $devicename
  friendly_name: $devicename
  project:
    version: "1.0.0"

esp32:
  framework:
    type: esp-idf
    version: 5.3.1
    platform_version: 6.9.0

# https://github.com/esphome/issues/issues/6567
external_components:
  - source: github://pr#8283
    components: [ i2c ]

sensor:
  # Combine sensors
  - platform: combination
    type: median
    id: temperature_local
    name: "Temperature"
    device_class: "temperature"
    sources:
      # ENV III
#      - source: temperature_sht3xd
#      - source: temperature_qmp6988
      # ENV IV
      - source: temperature_bmp280
      - source: temperature_sht4x
    filters:
      - or:
        - heartbeat: 900s
        - delta: 0.15
