packages:
  # --- COMMON PACKAGES ---
  <<: !include_dir_named common
  <<: !include_dir_named bluetooth

  # --- BOARD AND MODULES ---
  board: !include board/m5stack_core_s3se.yaml
  mbus_i2c: !include board/extension/mbus_i2c.yaml
  mbus_uart: !include board/extension/mbus_uart.yaml
  module_air_quality: !include board/module/module_air_quality.yaml
  module_cc1101: !include board/module/module_cc1101.yaml
  base_btc: !include board/module/base_btc.yaml

  # --- GUI PACKAGES ---
  colors: !include gui/themes/colors_night_owl.yaml
  lvgl: !include gui/240x320.yaml

substitutions:
  common:
#    log_level: WARN
#    log_baud_rate: "115200"
  device:
    name: m5s-c3se-3e3740
    location: "Simen"
    framework:
      type: esp-idf
  module:
    internal:
      i2c_bus: i2c_mbus
  display:
    home_page: page_temperature

esphome:
  comment: ${device.model} @ ${device.location}
  name: ${device.name}
  friendly_name: ${device.name}
  project:
    version: "1.0.0"

wifi:
  use_address: m5s-c3se-3e3740.local
  manual_ip: 
    gateway: 192.168.68.1
    subnet: 255.255.252.0
    static_ip: 192.168.71.67

# --- LVGL CLOCKS ---
time:
  - id: !extend time_rtc
    on_time:
      - minutes: '*'
        seconds: 0
        then:
          - script.execute: lvgl_time_update

lvgl:
  buffer_size: 40%

binary_sensor:
  # Call sensors from HA.
  - platform: homeassistant
    entity_id: binary_sensor.etg2_simen_occupancy
    id: motion_stue
  - platform: homeassistant
    entity_id: binary_sensor.etg2_gang_occupancy
    id: motion_gang
  # Turn on display while room is occupied
  - platform: template
    id: motion_detected
    lambda: !lambda |-
      if ( (id(motion_stue).state) or (id(motion_gang).state) ) {
        return true;
      } else {
        return false;
      }
    on_state: 
      then:
        - script.execute: display_on_off
