packages:
  # --- COMMON PACKAGES ---
  <<: !include_dir_named common
  <<: !include_dir_named bluetooth

  # --- BOARD AND MODULES ---
  board: !include board/m5stack_atom_s3_lite.yaml
  extension: !include board/extension/port_abc_i2c.yaml
  env_iv: !include board/module/unit_env_iv.yaml
  env_iii: !include board/module/unit_env_iii.yaml
  pir: !include board/module/unit_pir.yaml

  # --- FEATURE PACKAGES ---
  combined_env_sensors: !include features/combined_env_sensors.yaml

substitutions:
  common:
    log_level: WARN
#    log_baud_rate: "115200"
  device:
    name: m5s-as3-lite-b63eb8
    location_1: "Ute, Bod"
    location_2: "Ute, Foran"
  module:
    pir_in_pin: ${pin.ext.gpio.port_abc.in}
    env_i2c_bus: i2c_port_abc

esphome:
  comment: "M5Stack Atom S3 Lite @ Ute, Bod"
  name: ${device.name}
  friendly_name: ${device.name}
  area: ${device.location_1}
  project:
    version: "1.0.0"
  # Define areas (optional)
  areas:
    - id: area_ute_foran
      name: ${device.location_2}
  # Define devices
  devices:
    - id: device_ute_foran
      name: ${device.name}_sub
      area_id: area_ute_foran

sensor:
  # Combine sensors
  - id: !extend temperature_local
    sources:
      # Base BTC
#      - source: temperature_sht30_base_btc
      # HAT ENV III
#      - source: temperature_sht30_hat_env
#      - source: temperature_qmp6988_hat_env
      # Unit ENV III
      - source: temperature_sht30_unit_env
      - source: temperature_qmp6988_unit_env
      # Unit ENV IV
#      - source: temperature_bmp280_unit_env
#      - source: temperature_sht40_unit_env
      # Unit ENV Pro
#      - source: temperature_bme688
      # Unit CO2
#      - source: temperature_scd40_unit_co2

  - id: !extend humidity_local
    sources:
      # Base BTC
#      - source: humidity_sht30_base_btc
      # HAT ENV III
#      - source: humidity_sht30_hat_env
      # Unit ENV III
      - source: humidity_sht30_unit_env
      # Unit ENV IV
#      - source: humidity_sht40_unit_env
      # Unit ENV Pro
#      - source: humidity_bme688
      # Unit CO2
#      - source: humidity_scd40_unit_co2

  - id: !extend pressure_local
    sources:
      # HAT ENV III
#      - source: pressure_qmp6988_hat_env
      # Unit ENV III
      - source: pressure_qmp6988_unit_env
      # Unit ENV IV
#      - source: pressure_bmp280_unit_env
      # Unit ENV Pro
#      - source: pressure_bme688

  - platform: combination
    type: median
    id: temperature_ute
    device_id: device_ute_foran
    name: "Ute Temperature"
    device_class: "temperature"
    state_class: "measurement"
    sources:
      # Base BTC
#      - source: temperature_sht30_base_btc
      # HAT ENV III
#      - source: temperature_sht30_hat_env
#      - source: temperature_qmp6988_hat_env
      # Unit ENV III
#      - source: temperature_sht30_unit_env
#      - source: temperature_qmp6988_unit_env
      # Unit ENV IV
      - source: temperature_bmp280_unit_env
      - source: temperature_sht40_unit_env
      # Unit ENV Pro
#      - source: temperature_bme688
      # Unit CO2
#      - source: temperature_scd40_unit_co2
    filters:
      - or:
        - heartbeat: 900s
        - delta: 0.15

  - platform: combination
    type: median
    id: humidity_ute
    device_id: device_ute_foran
    name: "Ute Humidity"
    device_class: "humidity"
    state_class: "measurement"
    sources:
      # Base BTC
#      - source: humidity_sht30_base_btc
      # HAT ENV III
#      - source: humidity_sht30_hat_env
      # Unit ENV III
#      - source: humidity_sht30_unit_env
      # Unit ENV IV
      - source: humidity_sht40_unit_env
      # Unit ENV Pro
#      - source: humidity_bme688
      # Unit CO2
#      - source: humidity_scd40_unit_co2
    filters:
      - or:
        - heartbeat: 900s
        - delta: 0.15

  - platform: combination
    type: median
    id: pressure_ute
    device_id: device_ute_foran
    name: "Ute Pressure"
    device_class: "atmospheric_pressure"
    state_class: "measurement"
    sources:
      # HAT ENV III
#      - source: pressure_qmp6988_hat_env
      # Unit ENV III
#      - source: pressure_qmp6988_unit_env
      # Unit ENV IV
      - source: pressure_bmp280_unit_env
      # Unit ENV Pro
#      - source: pressure_bme688
    filters:
      - or:
        - heartbeat: 900s
        - delta: 0.15