packages:
  <<: !include_dir_named common
  <<: !include_dir_named bluetooth
  board: !include board/m5stack_atom_s3_lite_arduino.yaml
  hat: !include board/extension/hat_i2c.yaml
  grove: !include board/extension/grove_i2c.yaml
  env_iii: !include board/module/hat_env_iii.yaml
  env_pro: !include board/module/unit_env_pro.yaml
  co2: !include board/module/unit_co2.yaml

substitutions:
  devicename: m5s-as3-lite-9539bc
  location: "2etg, Ellen & Svein"
  i2c_grove_frequency: 40kHz

esphome:
  comment: "M5Stack Atom S3 Lite @ Ellen & Svein"
  name: $devicename
  friendly_name: $devicename
  area: $location
  project:
    version: "1.0.0"

esp32:
  framework:
    type: arduino
    version: latest

sensor:
  # Combine sensors
  - platform: combination
    type: median
    id: temperature_local
    name: "Temperature"
    device_class: "temperature"
    state_class: "measurement"
    sources:
      # ENV III
      - source: temperature_sht30_hat_env
      - source: temperature_qmp6988_hat_env
      # ENV IV
#      - source: temperature_bmp280_unit_env
#      - source: temperature_sht40_unit_env
      # ENV Pro
      - source: temperature_bme688
      # CO2
      - source: temperature_scd40_unit_co2
    filters:
      - or:
        - heartbeat: 900s
        - delta: 0.15

  - platform: combination
    type: median
    id: humidity_local
    name: "Humidity"
    device_class: "humidity"
    state_class: "measurement"
    sources:
      # ENV III
      - source: humidity_sht30_hat_env
      # ENV IV
#      - source: humidity_sht40_unit_env
      # ENV Pro
      - source: humidity_bme688
      # CO2
      - source: humidity_scd40_unit_co2
    filters:
      - or:
        - heartbeat: 900s
        - delta: 0.15

  - platform: combination
    type: median
    id: pressure_local
    name: "Pressure"
    device_class: "atmospheric_pressure"
    state_class: "measurement"
    sources:
      # ENV III
      - source: pressure_qmp6988_hat_env
      # ENV IV
#      - source: pressure_bmp280_unit_env
      # ENV Pro
      - source: pressure_bme688
    filters:
      - or:
        - heartbeat: 900s
        - delta: 0.15