packages:
  <<: !include_dir_named common
  <<: !include_dir_named bluetooth
  board: !include board/m5stack_atom_s3_lite_esp_idf.yaml
  hat: !include board/extension/hat_i2c.yaml
  env: !include board/module/hat_env_iii.yaml

substitutions:
  devicename: m5s-as3-lite-9539bc

esphome:
  comment: "M5Stack Atom S3 Lite 9539bc"
  name: $devicename
  friendly_name: $devicename
  project:
    version: "1.0.0"

esp32:
  framework:
    type: esp-idf
