packages:
  # --- COMMON PACKAGES ---
  <<: !include_dir_named common
#  <<: !include_dir_named bluetooth

  # --- BOARD AND MODULES ---
  board: !include board/m5stack_fire.yaml
  go_base: !include board/module/base_m5go_bottom.yaml
  grove_i2c: !include board/extension/grove_i2c.yaml
  env: !include board/module/unit_env_iv.yaml
  pir: !include board/module/unit_pir.yaml

  # --- GUI PACKAGES ---
  colors: !include gui/themes/colors_night_owl.yaml
  lvgl: !include gui/240x320.yaml

  # --- FEATURE PACKAGES ---
  combined_env_sensors: !include features/combined_env_sensors.yaml
  nordpool_light_alert: !include { file: features/nordpool_light_alert.yaml, vars: {
    light_id: rgb_led_m5go,
    light_brightness: 30%,
    light_flash_brightness: 40%
  }}

  # --- LVGL WIDGET PACKAGES ---
  room_temperature_widget_sensors: !include { file: gui/widgets/labels/number_sensor.yaml, vars: {
    uid: room_temp_value,
    entity_id: sensor.t22_temperature
  }}

substitutions:
  devicename: m5s-fire-a70780
  location: "2etg, Stue"
  log_level: WARN
  home_page: page_nordpool

esphome:
  comment: "M5Stack Fire @ Stue"
  name: ${devicename}
  friendly_name: ${devicename}
  area: ${location}

# --- LVGL CLOCKS ---
time:
  - id: !extend time_homeassistant
    on_time_sync:
      - script.execute: lvgl_time_update
    on_time:
      - minutes: '*'
        seconds: 0
        then:
          - script.execute: lvgl_time_update

binary_sensor:
  # Call sensors from HA.
  - platform: homeassistant
    entity_id: binary_sensor.etg2_simen_occupancy
    id: motion_simen
  - platform: homeassistant
    entity_id: binary_sensor.etg2_gang_occupancy
    id: motion_gang
  # Turn on display while room is occupied
  - platform: template
    id: motion_detected
    lambda: !lambda |-
      if ( (id(motion_simen).state) or (id(motion_gang).state) ) {
        return true;
      } else {
        return false;
      }
    on_state: 
      then:
        - script.execute: display_on_off

  # Button Left
  - id: !extend btn_a
    on_press:
      - lvgl.page.previous
  # Button Mid
  - id: !extend btn_b
    on_press:
      - script.execute: go_home
  # Button Right
  - id: !extend btn_c
    on_press:
      - lvgl.page.next

sensor:
  # Combine sensors
  - id: !extend temperature_local
    sources:
      # Base BTC
#      - source: temperature_sht30_base_btc
      # HAT ENV III
#      - source: temperature_sht30_hat_env
#      - source: temperature_qmp6988_hat_env
      # Unit ENV III
#      - source: temperature_sht30_unit_env
#      - source: temperature_qmp6988_unit_env
      # Unit ENV IV
      - source: temperature_bmp280_unit_env
      - source: temperature_sht40_unit_env
      # Unit ENV Pro
#      - source: temperature_bme688
      # Unit CO2
#      - source: temperature_scd40_unit_co2

  - id: !extend humidity_local
    sources:
      # Base BTC
#      - source: humidity_sht30_base_btc
      # HAT ENV III
#      - source: humidity_sht30_hat_env
      # Unit ENV III
#      - source: humidity_sht30_unit_env
      # Unit ENV IV
      - source: humidity_sht40_unit_env
      # Unit ENV Pro
#      - source: humidity_bme688
      # Unit CO2
#      - source: humidity_scd40_unit_co2

  - id: !extend pressure_local
    sources:
      # HAT ENV III
#      - source: pressure_qmp6988_hat_env
      # Unit ENV III
#      - source: pressure_qmp6988_unit_env
      # Unit ENV IV
      - source: pressure_bmp280_unit_env
      # Unit ENV Pro
#      - source: pressure_bme688
