packages:
  # --- COMMON PACKAGES ---
  <<: !include_dir_named common
# might be too weak for BLE ?
  <<: !include_dir_named bluetooth

  # --- BOARD AND MODULES ---
  board: !include board/m5stack_nano_c6.yaml
  grove: !include board/extension/grove_i2c.yaml
  env_iii: !include board/module/unit_env_iii.yaml
  tvoc: !include board/module/unit_tvoc.yaml

  # --- FEATURE PACKAGES ---
  combined_env_sensors: !include features/combined_env_sensors.yaml
  nordpool_light_alert: !include { file: features/nordpool_light_alert.yaml, vars: {
    light_id: rgb_led,
    light_brightness: 75%,
    light_flash_brightness: 90%
  }}

substitutions:
  common:
    log_level: WARN
#    log_baud_rate: "115200"
  device:
    name: m5s-nano-c6-1d8ec8
    location: "1etg, TV Stue"

esphome:
  comment: "M5Stack NanoC6 1d8ec8"
  name: ${device.name}
  friendly_name: ${device.name}
  area: ${device.location}
  project:
    version: "1.0.0"

i2c:
  - id: !extend i2c_grove
    scan: false

sensor:
  # Combine sensors
  - id: !extend temperature_local
    sources:
      # Base BTC
#      - source: temperature_sht30_base_btc
      # HAT ENV III
#      - source: temperature_sht30_hat_env
#      - source: temperature_qmp6988_hat_env
      # Unit ENV III
      - source: temperature_sht30_unit_env
      - source: temperature_qmp6988_unit_env
      # Unit ENV IV
#      - source: temperature_bmp280_unit_env
#      - source: temperature_sht40_unit_env
      # Unit ENV Pro
#      - source: temperature_bme688
      # Unit CO2
#      - source: temperature_scd40_unit_co2

  - id: !extend humidity_local
    sources:
      # Base BTC
#      - source: humidity_sht30_base_btc
      # HAT ENV III
#      - source: humidity_sht30_hat_env
      # Unit ENV III
      - source: humidity_sht30_unit_env
      # Unit ENV IV
#      - source: humidity_sht40_unit_env
      # Unit ENV Pro
#      - source: humidity_bme688
      # Unit CO2
#      - source: humidity_scd40_unit_co2

  - id: !extend pressure_local
    sources:
      # HAT ENV III
#      - source: pressure_qmp6988_hat_env
      # Unit ENV III
      - source: pressure_qmp6988_unit_env
      # Unit ENV IV
#      - source: pressure_bmp280_unit_env
      # Unit ENV Pro
#      - source: pressure_bme688

