packages:
  <<: !include_dir_named common
  <<: !include_dir_named bluetooth
  board: !include board/m5stack_fire.yaml
  go_base: !include board/module/base_m5go_bottom.yaml
  grove_i2c: !include board/extension/grove_i2c.yaml
  env: !include board/module/unit_env_iv.yaml
  pir: !include board/module/unit_pir.yaml
  colors: !include gui/modular/themes/colors_night_owl.yaml
  lvgl: !include gui/modular/240x320.yaml

  room_temperature_widget_sensors: !include { file: gui/modular/widgets/labels/number_sensor.yaml, vars: {
    uid: room_temp_value,
    entity_id: sensor.t22_temperature
  }}

substitutions:
  devicename: m5s-fire-a70780
  location: "2etg, Stue"
  log_level: WARN
  home_page: page_temperature

esphome:
  comment: "M5Stack Fire @ Stue"
  name: $devicename
  friendly_name: $devicename
  area: $location

lvgl:
  buffer_size: 50%
  encoders:
    enter_button: btn_b
    sensor:
      left_button: btn_a
      right_button: btn_c
  pages:
    - id: power_page
      pad_top: 34
      pad_bottom: 34
      on_load:
        - lvgl.label.update:
            id: page_title
            text: Skjerm
      <<: !include
        file: gui/modular/sections/swipe_navigation.yaml
      widgets:
        - obj:
            pad_all: 1
            align: CENTER
            height: 100%
            width: 100%
            layout:
              type: GRID
              grid_columns: [FR(1), FR(1), FR(1), FR(1), FR(1), FR(1), FR(1), FR(1), FR(1)]
              grid_rows: [FR(18), FR(136), FR(14)]
            widgets:
              - label:
                  id: lbl_nordpool_price_0
                  text: "?"
                  grid_cell_column_pos: 0
                  grid_cell_row_pos: 0
                  grid_cell_x_align: start
                  grid_cell_y_align: center
                  text_align: left
                  text_font: font_md
                  text_color: c_text_p
              - label:
                  id: lbl_nordpool_time_0
                  text: "?"
                  grid_cell_column_pos: 0
                  grid_cell_row_pos: 2
                  grid_cell_x_align: start
                  grid_cell_y_align: center
                  text_align: left
                  text_font: font_sm
                  text_color: c_text_s

              - label:
                  id: lbl_nordpool_price_4
                  text: "?"
                  grid_cell_column_pos: 4
                  grid_cell_row_pos: 0
                  grid_cell_x_align: center
                  grid_cell_y_align: center
                  text_align: center
                  text_font: font_md
                  text_color: c_text_p
              - label:
                  id: lbl_nordpool_time_4
                  text: "?"
                  grid_cell_column_pos: 4
                  grid_cell_row_pos: 2
                  grid_cell_x_align: center
                  grid_cell_y_align: center
                  text_align: center
                  text_font: font_sm
                  text_color: c_text_s

              - label:
                  id: lbl_nordpool_price_8
                  text: "?"
                  grid_cell_column_pos: 8
                  grid_cell_row_pos: 0
                  grid_cell_x_align: end
                  grid_cell_y_align: center
                  text_align: right
                  text_font: font_md
                  text_color: c_text_p
              - label:
                  id: lbl_nordpool_time_8
                  text: "?"
                  grid_cell_column_pos: 8
                  grid_cell_row_pos: 2
                  grid_cell_x_align: end
                  grid_cell_y_align: center
                  text_align: right
                  text_font: font_sm
                  text_color: c_text_s

              - bar:
                  id: bar_nordpool_price_0
                  grid_cell_column_pos: 0
                  grid_cell_row_pos: 1
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  width: 34
                  height: 100%
                  value: 150
                  min_value: 0
                  max_value: 300
              - bar:
                  id: bar_nordpool_price_1
                  grid_cell_column_pos: 1
                  grid_cell_row_pos: 1
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  width: 34
                  height: 100%
                  value: 150
                  min_value: 0
                  max_value: 300
              - bar:
                  id: bar_nordpool_price_2
                  grid_cell_column_pos: 2
                  grid_cell_row_pos: 1
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  width: 34
                  height: 100%
                  value: 150
                  min_value: 0
                  max_value: 300
              - bar:
                  id: bar_nordpool_price_3
                  grid_cell_column_pos: 3
                  grid_cell_row_pos: 1
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  width: 34
                  height: 100%
                  value: 150
                  min_value: 0
                  max_value: 300
              - bar:
                  id: bar_nordpool_price_4
                  grid_cell_column_pos: 4
                  grid_cell_row_pos: 1
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  width: 34
                  height: 100%
                  value: 150
                  min_value: 0
                  max_value: 300
              - bar:
                  id: bar_nordpool_price_5
                  grid_cell_column_pos: 5
                  grid_cell_row_pos: 1
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  width: 34
                  height: 100%
                  value: 150
                  min_value: 0
                  max_value: 300
              - bar:
                  id: bar_nordpool_price_6
                  grid_cell_column_pos: 6
                  grid_cell_row_pos: 1
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  width: 34
                  height: 100%
                  value: 150
                  min_value: 0
                  max_value: 300
              - bar:
                  id: bar_nordpool_price_7
                  grid_cell_column_pos: 7
                  grid_cell_row_pos: 1
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  width: 34
                  height: 100%
                  value: 150
                  min_value: 0
                  max_value: 300
              - bar:
                  id: bar_nordpool_price_8
                  grid_cell_column_pos: 8
                  grid_cell_row_pos: 1
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: STRETCH
                  width: 34
                  height: 100%
                  value: 150
                  min_value: 0
                  max_value: 300

binary_sensor:
  # Call sensors from HA.
  - platform: homeassistant
    entity_id: binary_sensor.etg2_stue_occupancy
    id: motion_stue
  - platform: homeassistant
    entity_id: binary_sensor.etg2_gang_occupancy
    id: motion_gang
  # Turn on display while room is occupied
  - platform: template
    id: motion_detected
    lambda: !lambda |-
      if ( (id(motion_stue).state) or (id(motion_gang).state) ) {
        return true;
      } else {
        return false;
      }
    on_state: 
      then:
        - script.execute: display_on_off

sensor:
  # Combine sensors
  - platform: combination
    type: median
    id: temperature_local
    name: "Temperature"
    device_class: "temperature"
    state_class: "measurement"
    sources:
      # ENV III
#      - source: temperature_sht30_hat_env
#      - source: temperature_qmp6988_hat_env
      # ENV IV
      - source: temperature_bmp280_unit_env
      - source: temperature_sht40_unit_env
      # ENV Pro
#      - source: temperature_bme688
      # CO2
#      - source: temperature_scd40_unit_co2
    filters:
      - or:
        - heartbeat: 900s
        - delta: 0.15

#  - platform: homeassistant
#    entity_id: sensor.waveshare_nordpool_future_offset
#    id: nordpool_sensor
  - platform: homeassistant
    entity_id: sensor.waveshare_nordpool_future_offset
    attribute: price0
    id: nordpool_price_0
    on_value: 
      then:
        - lvgl.label.update:
            id: lbl_nordpool_price_0
            text:
              format: "%.0f"
              args: [ 'x' ]
        - lvgl.bar.update:
            id: bar_nordpool_price_0
            value: !lambda return x;
  - platform: homeassistant
    entity_id: sensor.waveshare_nordpool_future_offset
    attribute: price0
    id: nordpool_price_1
    on_value:
      then:
        - lvgl.bar.update:
            id: bar_nordpool_price_1
            value: !lambda return x;
  - platform: homeassistant
    entity_id: sensor.waveshare_nordpool_future_offset
    attribute: price0
    id: nordpool_price_2
    on_value:
      then:
        - lvgl.bar.update:
            id: bar_nordpool_price_2
            value: !lambda return x;
  - platform: homeassistant
    entity_id: sensor.waveshare_nordpool_future_offset
    attribute: price0
    id: nordpool_price_3
    on_value:
      then:
        - lvgl.bar.update:
            id: bar_nordpool_price_3
            value: !lambda return x;
  - platform: homeassistant
    entity_id: sensor.waveshare_nordpool_future_offset
    attribute: price4
    id: nordpool_price_4
    on_value:
      then:
        - lvgl.label.update:
            id: lbl_nordpool_price_4
            text:
              format: "%.0f"
              args: [ 'x' ]
        - lvgl.bar.update:
            id: bar_nordpool_price_4
            value: !lambda return x;
  - platform: homeassistant
    entity_id: sensor.waveshare_nordpool_future_offset
    attribute: price4
    id: nordpool_price_5
    on_value:
      then:
        - lvgl.bar.update:
            id: bar_nordpool_price_5
            value: !lambda return x;
  - platform: homeassistant
    entity_id: sensor.waveshare_nordpool_future_offset
    attribute: price4
    id: nordpool_price_6
    on_value:
      then:
        - lvgl.bar.update:
            id: bar_nordpool_price_6
            value: !lambda return x;
  - platform: homeassistant
    entity_id: sensor.waveshare_nordpool_future_offset
    attribute: price4
    id: nordpool_price_7
    on_value:
      then:
        - lvgl.bar.update:
            id: bar_nordpool_price_7
            value: !lambda return x;
  - platform: homeassistant
    entity_id: sensor.waveshare_nordpool_future_offset
    attribute: price8
    id: nordpool_price_8
    on_value:
      then:
        - lvgl.label.update:
            id: lbl_nordpool_price_8
            text:
              format: "%.0f"
              args: [ 'x' ]
        - lvgl.bar.update:
            id: bar_nordpool_price_8
            value: !lambda return x;
  - platform: combination
    id: nordpool_price_max
    type: max
    sources:
      - source: nordpool_price_0
      - source: nordpool_price_1
      - source: nordpool_price_2
      - source: nordpool_price_3
      - source: nordpool_price_4
      - source: nordpool_price_5
      - source: nordpool_price_6
      - source: nordpool_price_7
      - source: nordpool_price_8
#    on_value:
#      then:
#        - lvgl.bar.update:
#            id:
#              - bar_nordpool_price_0
#              - bar_nordpool_price_1
#              - bar_nordpool_price_2
#              - bar_nordpool_price_3
#              - bar_nordpool_price_4
#              - bar_nordpool_price_5
#              - bar_nordpool_price_6
#              - bar_nordpool_price_7
#              - bar_nordpool_price_8
#            max_value: !lambda return (int)x + 10;
#            min_value: !lambda return id(nordpool_price_min).state;
  - platform: combination
    id: nordpool_price_min
    type: min
    sources:
      - source: nordpool_price_0
      - source: nordpool_price_1
      - source: nordpool_price_2
      - source: nordpool_price_3
      - source: nordpool_price_4
      - source: nordpool_price_5
      - source: nordpool_price_6
      - source: nordpool_price_7
      - source: nordpool_price_8
#    on_value:
#      then:
#        - lvgl.bar.update:
#            id:
#              - bar_nordpool_price_0
#              - bar_nordpool_price_1
#              - bar_nordpool_price_2
#              - bar_nordpool_price_3
#              - bar_nordpool_price_4
#              - bar_nordpool_price_5
#              - bar_nordpool_price_6
#              - bar_nordpool_price_7
#              - bar_nordpool_price_8
#            min_value: !lambda return (int)x - 10;
#            max_value: !lambda return id(nordpool_price_max).state;

text_sensor:
  # Strings from Home Assistant
  - platform: homeassistant
    entity_id: sensor.waveshare_nordpool_future_offset
    attribute: time0
    id: nordpool_time_0
    on_value:
      then:
        - lvgl.label.update:
            id: lbl_nordpool_time_0
            text: !lambda return id(nordpool_time_0).state;
  - platform: homeassistant
    entity_id: sensor.waveshare_nordpool_future_offset
    attribute: time4
    id: nordpool_time_4
    on_value:
      then:
        - lvgl.label.update:
            id: lbl_nordpool_time_4
            text: !lambda return id(nordpool_time_4).state;
  - platform: homeassistant
    entity_id: sensor.waveshare_nordpool_future_offset
    attribute: time8
    id: nordpool_time_8
    on_value:
      then:
        - lvgl.label.update:
            id: lbl_nordpool_time_8
            text: !lambda return id(nordpool_time_8).state;
