packages:
  # --- COMMON PACKAGES ---
  <<: !include_dir_named common
  <<: !include_dir_named bluetooth

  # --- BOARD AND MODULES ---
  board: !include board/m5stack_atom_s3.yaml
  extension: !include board/extension/port_abc_i2c.yaml
  env: !include board/module/unit_env_iv.yaml
  pir: !include board/module/unit_pir.yaml

  # --- FEATURE PACKAGES ---
  combined_env_sensors: !include features/combined_env_sensors.yaml

  # --- GUI PACKAGES ---
  colors: !include gui/themes/colors_night_owl.yaml
  lvgl: !include gui/128x128.yaml

  # --- LVGL WIDGET PACKAGES ---
  room_temperature_widget_sensors:
    !include {
      file: gui/widgets/labels/number_sensor.yaml,
      vars: { uid: room_temp_value, entity_id: sensor.etg2_bod_tc_heatindex },
    }
  fridge_temperature_widget_sensors:
    !include {
      file: gui/widgets/labels/number_sensor.yaml,
      vars: { uid: fridge_temp_value, entity_id: sensor.etg2_bod_kjoleskap_temp_temperature },
    }
  freezer_temperature_widget_sensors:
    !include {
      file: gui/widgets/labels/number_sensor.yaml,
      vars: { uid: freezer_temp_value, entity_id: sensor.etg2_bod_fryser_temp_temperature },
    }

substitutions:
  common:
    log_level: WARN
#    log_baud_rate: "115200"
  device:
    name: m5s-as3-b5c828
    location: "2etg, Bod"
  module:
    pir_in_pin: ${pin.ext.gpio.port_abc.in}
    env_i2c_bus: i2c_port_abc
    gyro_i2c_bus: i2c_port_abc
  display:
    home_page: page_temperature

esphome:
  comment: "M5Stack Atom S3 @ Bod"
  name: ${device.name}
  friendly_name: ${device.name}
  area: ${device.location}
  project:
    version: "1.0.0"

# --- LVGL CLOCKS ---
time:
  - id: !extend time_homeassistant
    on_time_sync:
      - script.execute: lvgl_time_update
    on_time:
      - minutes: '*'
        seconds: 0
        then:
          - script.execute: lvgl_time_update

binary_sensor:
  - id: !extend btn_display
    on_press:
      - lvgl.page.next

  # Turn on display while room is occupied
  - platform: homeassistant
    entity_id: binary_sensor.etg2_bod_occupancy
    id: motion_detected
    on_state: 
      then:
        - script.execute: display_on_off

sensor:
  # Combine sensors
  - id: !extend temperature_local
    sources:
      # Base BTC
#      - source: temperature_sht30_base_btc
      # HAT ENV III
#      - source: temperature_sht30_hat_env
#      - source: temperature_qmp6988_hat_env
      # Unit ENV III
#      - source: temperature_sht30_unit_env
#      - source: temperature_qmp6988_unit_env
      # Unit ENV IV
      - source: temperature_bmp280_unit_env
      - source: temperature_sht40_unit_env
      # Unit ENV Pro
#      - source: temperature_bme688
      # Unit CO2
#      - source: temperature_scd40_unit_co2

  - id: !extend humidity_local
    sources:
      # Base BTC
#      - source: humidity_sht30_base_btc
      # HAT ENV III
#      - source: humidity_sht30_hat_env
      # Unit ENV III
#      - source: humidity_sht30_unit_env
      # Unit ENV IV
      - source: humidity_sht40_unit_env
      # Unit ENV Pro
#      - source: humidity_bme688
      # Unit CO2
#      - source: humidity_scd40_unit_co2

  - id: !extend pressure_local
    sources:
      # HAT ENV III
#      - source: pressure_qmp6988_hat_env
      # Unit ENV III
#      - source: pressure_qmp6988_unit_env
      # Unit ENV IV
      - source: pressure_bmp280_unit_env
      # Unit ENV Pro
#      - source: pressure_bme688

lvgl:
  buffer_size: 15%
  pages:
    - id: !remove page_temperature
    - id: page_temperature
      pad_top: 24
      pad_bottom: 0
      on_load:
        - lvgl.label.update:
            id: lbl_page_title
            text: "\U000F0510" # thermometer-lines
      <<: !include
        file: gui/functions/swipe_navigation.yaml
      widgets:
        - obj:
            pad_top: 0
            pad_bottom: 6
            pad_left: 3
            pad_right: 3
            scrollable: false
            width: 100%
            height: 100%
            border_width: 0
            radius: 0
            align: CENTER
            layout:
              type: FLEX
              flex_flow: COLUMN
              flex_align_cross: CENTER
              flex_align_main: SPACE_EVENLY
              flex_align_track: CENTER
              pad_column: 0
              pad_row: 0
            widgets:
              - obj:
                  pad_all: 0
                  width: 128
                  height: SIZE_CONTENT
                  layout:
                    type: FLEX
                    flex_flow: ROW
                    flex_align_cross: CENTER
                    flex_align_main: SPACE_AROUND
                    pad_column: 0
                    pad_row: 0
                  widgets:
                    # Fridge temperature
                    - obj:
                        pad_all: 0
                        width: SIZE_CONTENT
                        height: SIZE_CONTENT
                        layout:
                          type: FLEX
                          flex_flow: COLUMN
                          flex_align_main: CENTER
                          flex_align_cross: START
                          flex_align_track: START
                          pad_column: 0
                          pad_row: 0
                        widgets:
                          # Fridge icon
                          - label:
                              id: fridge_temp_icon
                              text: "\U000F0292" # fridge-bottom
                              pad_all: 0
                              text_font: mdi_sm
                              text_color: c_pink
                          # Fridge temperature value
                          - label:
                              id: fridge_temp_value_widget_text
                              text: "-째C"
                              pad_all: 0
                              text_font: font_sm
                              text_color: c_text_p
                    # Room temperature value
                    - label:
                        id: room_temp_value_widget_text
                        text: "--째C"
                        pad_all: 0
                        text_font: font_fl
                        text_color: c_text_p
                        text_align: CENTER
                    # Freezer temperature
                    - obj:
                        pad_all: 0
                        width: SIZE_CONTENT
                        height: SIZE_CONTENT
                        layout:
                          type: FLEX
                          flex_flow: COLUMN
                          flex_align_main: CENTER
                          flex_align_cross: END
                          flex_align_track: END
                          pad_column: 0
                          pad_row: 0
                        widgets:
                          # Freezer icon
                          - label:
                              id: freezer_temp_icon
                              text: "\U000F0291" # fridge-top
                              pad_all: 0
                              text_font: mdi_sm
                              text_color: c_blue
                          # Freezer temperature value
                          - label:
                              id: freezer_temp_value_widget_text
                              text: "-째C"
                              pad_all: 0
                              text_font: font_sm
                              text_color: c_text_p

              - obj:
                  pad_all: 0
                  width: 128
                  height: SIZE_CONTENT
                  layout:
                    type: FLEX
                    flex_flow: ROW
                    flex_align_cross: CENTER
                    flex_align_main: SPACE_AROUND
                    pad_column: 0
                    pad_row: 0
                  widgets:
                    - label: # thermometer icon
                        id: room_temp_icon
                        text: "\U000F050F"
                        pad_all: 0
                        text_font: mdi_lg
                        text_color: c_text_s
                    - label: # area
                        id: room_temp_area
                        text: "Rom"
                        pad_all: 0
                        text_font: font_lg
                        text_color: c_text_s
                    - label: # temperature unit
                        id: room_temp_unit
                        text: "째C"
                        pad_all: 0
                        text_font: font_lg
                        text_color: c_text_s

display:
  - id: !extend display_lcd
    dimensions:
      offset_height: 1
      offset_width: 2
    # Rotate 180deg
    transform:
      mirror_x: true
      mirror_y: true
