packages:
  # --- COMMON PACKAGES ---
  <<: !include_dir_named common
#  <<: !include_dir_named bluetooth

  # --- BOARD AND MODULES ---
  board: !include board/m5stack_core_s3se.yaml
  mbus_i2c: !include board/extension/mbus_i2c.yaml
  grove_i2c: !include board/extension/grove_i2c.yaml
  mbus_uart: !include board/extension/mbus_uart.yaml
  air_quality: !include board/module/module_air_quality.yaml
  base_btc: !include board/module/base_btc.yaml
  env_iv: !include board/module/unit_env_iv.yaml
  co2: !include board/module/unit_co2.yaml

  # --- FEATURE PACKAGES ---
  combined_env_sensors: !include features/combined_env_sensors.yaml

  # --- GUI PACKAGES ---
  colors: !include gui/themes/colors_night_owl.yaml
  lvgl: !include gui/240x320.yaml

  # --- LVGL WIDGET PACKAGES ---
  room_temperature_widget_sensors: !include { file: gui/widgets/labels/number_sensor.yaml, vars: {
    uid: room_temp_value,
    entity_id: sensor.etg2_simen_temperature
  }}

substitutions:
  common:
    log_level: WARN
#    log_baud_rate: "115200"
  device:
    name: m5s-c3se-3e3740
    location: "1etg, Kjøkken"
  module:
    internal:
      i2c_bus: i2c_mbus
  display:
    home_page: page_analog_clock

esphome:
  comment: 'M5Stack Core3 SE'
  name: ${device.name}
  friendly_name: ${device.name}
  project:
    version: "1.0.0"

# --- LVGL CLOCKS ---
time:
  - id: !extend time_homeassistant
    on_time_sync:
      - script.execute: lvgl_time_update
      - pcf8563.write_time:
    on_time:
      - minutes: '*'
        seconds: 0
        then:
          - script.execute: lvgl_time_update

lvgl:
  buffer_size: 75%
  pages:
    - id: page_airq
      pad_top: 34
      pad_bottom: 34
      on_load:
        - lvgl.label.update:
            id: lbl_page_title
            text: Luftkvalitet
      <<: !include
        file: gui/functions/swipe_navigation.yaml
      widgets:
        - obj:
            pad_top: 0
            pad_bottom: 0
            pad_left: 4
            pad_right: 4
            scrollable: false
            align: CENTER
            height: 100%
            width: 100%
            layout:
              type: GRID
              grid_columns: [FR(4), FR(3), FR(2)]
              grid_rows: [FR(1), FR(1), FR(1), FR(1), FR(1)]
            widgets:
              - label:
                  id: lbl_temp_local_l
                  text: "Temperatur: "
                  grid_cell_column_pos: 0
                  grid_cell_row_pos: 0
                  grid_cell_x_align: start
                  grid_cell_y_align: center
                  text_font: font_sm
                  text_color: c_text_s
              - label:
                  id: lbl_temp_local_value
                  text: "?"
                  grid_cell_column_pos: 1
                  grid_cell_row_pos: 0
                  grid_cell_x_align: end
                  grid_cell_y_align: center
                  text_align: right
                  text_font: font_lg
                  text_color: c_text_p
              - label:
                  id: lbl_temp_local_unit
                  text: "°C"
                  grid_cell_column_pos: 2
                  grid_cell_row_pos: 0
                  grid_cell_x_align: end
                  grid_cell_y_align: center
                  text_align: right
                  text_font: font_md
                  text_color: c_text_s

              - label:
                  id: lbl_co2_l
                  text: "Karbondioksid: "
                  grid_cell_column_pos: 0
                  grid_cell_row_pos: 1
                  grid_cell_x_align: start
                  grid_cell_y_align: center
                  text_font: font_sm
                  text_color: c_text_s
              - label:
                  id: lbl_co2_value
                  text: "?"
                  grid_cell_column_pos: 1
                  grid_cell_row_pos: 1
                  grid_cell_x_align: end
                  grid_cell_y_align: center
                  text_align: right
                  text_font: font_lg
                  text_color: c_text_p
              - label:
                  id: lbl_co2_unit
                  text: "ppm"
                  grid_cell_column_pos: 2
                  grid_cell_row_pos: 1
                  grid_cell_x_align: end
                  grid_cell_y_align: center
                  text_align: right
                  text_font: font_md
                  text_color: c_text_s

              - label:
                  id: lbl_pm1_l
                  text: "Svevestøv 1.0: "
                  grid_cell_column_pos: 0
                  grid_cell_row_pos: 2
                  grid_cell_x_align: start
                  grid_cell_y_align: center
                  text_font: font_sm
                  text_color: c_text_s
              - label:
                  id: lbl_pm1_value
                  text: "?"
                  grid_cell_column_pos: 1
                  grid_cell_row_pos: 2
                  grid_cell_x_align: end
                  grid_cell_y_align: center
                  text_align: right
                  text_font: font_lg
                  text_color: c_text_p
              - label:
                  id: lbl_pm1_unit
                  text: "µg/m³"
                  grid_cell_column_pos: 2
                  grid_cell_row_pos: 2
                  grid_cell_x_align: end
                  grid_cell_y_align: center
                  text_align: right
                  text_font: font_md
                  text_color: c_text_s

              - label:
                  id: lbl_pm25_l
                  text: "Svevestøv 2.5: "
                  grid_cell_column_pos: 0
                  grid_cell_row_pos: 3
                  grid_cell_x_align: start
                  grid_cell_y_align: center
                  text_font: font_sm
                  text_color: c_text_s
              - label:
                  id: lbl_pm25_value
                  text: "?"
                  grid_cell_column_pos: 1
                  grid_cell_row_pos: 3
                  grid_cell_x_align: end
                  grid_cell_y_align: center
                  text_align: right
                  text_font: font_lg
                  text_color: c_text_p
              - label:
                  id: lbl_pm25_unit
                  text: "µg/m³"
                  grid_cell_column_pos: 2
                  grid_cell_row_pos: 3
                  grid_cell_x_align: end
                  grid_cell_y_align: center
                  text_align: right
                  text_font: font_md
                  text_color: c_text_s

              - label:
                  id: lbl_pm10_l
                  text: "Svevestøv 10.0: "
                  grid_cell_column_pos: 0
                  grid_cell_row_pos: 4
                  grid_cell_x_align: start
                  grid_cell_y_align: center
                  text_font: font_sm
                  text_color: c_text_s
              - label:
                  id: lbl_pm10_value
                  text: "?"
                  grid_cell_column_pos: 1
                  grid_cell_row_pos: 4
                  grid_cell_x_align: end
                  grid_cell_y_align: center
                  text_align: right
                  text_font: font_lg
                  text_color: c_text_p
              - label:
                  id: lbl_pm10_unit
                  text: "µg/m³"
                  grid_cell_column_pos: 2
                  grid_cell_row_pos: 4
                  grid_cell_x_align: end
                  grid_cell_y_align: center
                  text_align: right
                  text_font: font_md
                  text_color: c_text_s

binary_sensor:
  # Call sensors from HA.
  - platform: homeassistant
    entity_id: binary_sensor.etg2_stue_occupancy
    id: motion_stue
  - platform: homeassistant
    entity_id: binary_sensor.etg2_gang_occupancy
    id: motion_gang
  # Turn on display while room is occupied
  - platform: template
    id: motion_detected
    lambda: !lambda |-
      if ( (id(motion_stue).state) or (id(motion_gang).state) ) {
        return true;
      } else {
        return false;
      }
    on_state: 
      then:
        - script.execute: display_on_off

sensor:
  # Combine sensors
  - id: !extend temperature_local
    sources:
      # Base BTC
      - source: temperature_sht30_base_btc
      # HAT ENV III
#      - source: temperature_sht30_hat_env
#      - source: temperature_qmp6988_hat_env
      # Unit ENV III
#      - source: temperature_sht30_unit_env
#      - source: temperature_qmp6988_unit_env
      # Unit ENV IV
      - source: temperature_bmp280_unit_env
      - source: temperature_sht40_unit_env
      # Unit ENV Pro
#      - source: temperature_bme688
      # Unit CO2
      - source: temperature_scd40_unit_co2
    on_value: 
      then:
        - lvgl.label.update:
            id: lbl_temp_local_value
            text:
              format: "%.1f"
              args: [ 'x' ]

  - id: !extend humidity_local
    sources:
      # Base BTC
      - source: humidity_sht30_base_btc
      # HAT ENV III
#      - source: humidity_sht30_hat_env
      # Unit ENV III
#      - source: humidity_sht30_unit_env
      # Unit ENV IV
      - source: humidity_sht40_unit_env
      # Unit ENV Pro
#      - source: humidity_bme688
      # Unit CO2
      - source: humidity_scd40_unit_co2

  - id: !extend pressure_local
    sources:
      # HAT ENV III
#      - source: pressure_qmp6988_hat_env
      # Unit ENV III
#      - source: pressure_qmp6988_unit_env
      # Unit ENV IV
      - source: pressure_bmp280_unit_env
      # Unit ENV Pro
#      - source: pressure_bme688

  # extend sensors to update lvgl
  - id: !extend unit_co2_scd40_sensor
    co2:
      on_value:
        then:
          - lvgl.label.update:
              id: lbl_co2_value
              text:
                format: "%.0f"
                args: [ 'x' ]
  - id: !extend pmsx003_sensor
    pm_1_0:
      on_value:
        then:
          - lvgl.label.update:
              id: lbl_pm1_value
              text:
                format: "%.1f"
                args: [ 'x' ]
    pm_2_5:
      on_value:
        then:
          - lvgl.label.update:
              id: lbl_pm25_value
              text:
                format: "%.1f"
                args: [ 'x' ]
    pm_10_0:
      on_value:
        then:
          - lvgl.label.update:
              id: lbl_pm10_value
              text:
                format: "%.1f"
                args: [ 'x' ]
