packages:
  # --- COMMON PACKAGES ---
  <<: !include_dir_named common
  <<: !include_dir_named bluetooth

  # --- BOARD AND MODULES ---
  board: !include board/m5stack_atom_s3_lite.yaml
  hat: !include board/extension/hat_i2c.yaml
  grove: !include board/extension/grove_i2c.yaml
  env_iii: !include board/module/hat_env_iii.yaml
  env_pro: !include board/module/unit_env_pro.yaml
  co2: !include board/module/unit_co2.yaml

  # --- FEATURE PACKAGES ---
  combined_env_sensors: !include features/combined_env_sensors.yaml

substitutions:
  devicename: m5s-as3-lite-9539bc
  location: "2etg, Ellen & Svein"
  i2c_grove_frequency: 40kHz
  log_level: WARN

esphome:
  comment: "M5Stack Atom S3 Lite @ Ellen & Svein"
  name: ${devicename}
  friendly_name: ${devicename}
  area: ${location}
  project:
    version: "1.0.0"

sensor:
  # Combine sensors
  - id: !extend temperature_local
    sources:
      # Base BTC
#      - source: temperature_sht30_base_btc
      # HAT ENV III
      - source: temperature_sht30_hat_env
      - source: temperature_qmp6988_hat_env
      # Unit ENV III
#      - source: temperature_sht30_unit_env
#      - source: temperature_qmp6988_unit_env
      # Unit ENV IV
#      - source: temperature_bmp280_unit_env
#      - source: temperature_sht40_unit_env
      # Unit ENV Pro
      - source: temperature_bme688
      # Unit CO2
      - source: temperature_scd40_unit_co2

  - id: !extend humidity_local
    sources:
      # Base BTC
#      - source: humidity_sht30_base_btc
      # HAT ENV III
      - source: humidity_sht30_hat_env
      # Unit ENV III
#      - source: humidity_sht30_unit_env
      # Unit ENV IV
#      - source: humidity_sht40_unit_env
      # Unit ENV Pro
      - source: humidity_bme688
      # Unit CO2
      - source: humidity_scd40_unit_co2

  - id: !extend pressure_local
    sources:
      # HAT ENV III
      - source: pressure_qmp6988_hat_env
      # Unit ENV III
#      - source: pressure_qmp6988_unit_env
      # Unit ENV IV
#      - source: pressure_bmp280_unit_env
      # Unit ENV Pro
      - source: pressure_bme688
