packages:
  # --- COMMON PACKAGES ---
  <<: !include_dir_named common
#  <<: !include_dir_named bluetooth

  # --- BOARD AND MODULES ---
  board: !include board/m5stack_coreink.yaml
#  internal_i2c: !include board/extension/internal_i2c.yaml
  hat: !include board/extension/hat_i2c.yaml
  grove: !include board/extension/grove_i2c.yaml
  env_iii: !include board/module/hat_env_iii.yaml
  env_iv: !include board/module/unit_env_iv.yaml
  co2: !include board/module/unit_co2.yaml

substitutions:
  devicename: m5s-coreink-9fc2c8
  location: "2etg, Simen"
  i2c_grove_frequency: 40kHz
  log_level: WARN

esphome:
  comment: "M5Stack CoreInk @ Simen"
  name: $devicename
  friendly_name: $devicename
  area: $location
  project: 
    version: "1.0.0"
  on_boot:
    - priority: -100
      then:
        - component.update: display_eink
        - wait_until:
            condition:
              lambda: 'return id(data_updated) == true;'
        # Wait a bit longer so all the items are received
        - delay: 5s
        - logger.log: "Initial sensor data received: Refreshing display..."
        - lambda: 'id(initial_data_received) = true;'
        - display.page.show: page_room
        - script.execute: update_screen

display:
  - id: !extend display_eink
    rotation: 90
    pages:
#      - id: page_black
#        lambda: |-
#          // Fill background.
#          it.fill(COLOR_ON);
#      - id: page_white
#        lambda: |-
#          // Fill background.
#          it.fill(COLOR_OFF);
      - id: page_local
        lambda: |-
          // Fill background.
          it.fill( COLOR_ON );

          //it.graph( 0, 0, id(graph_temperature_local), COLOR_OFF );
          
          // NAV
          it.image( (it.get_width()/14)*2 , 0, id(i_home), ImageAlign::TOP_CENTER, COLOR_OFF, COLOR_ON );
          it.image( (it.get_width()/14)*4 , 0, id(i_refresh), ImageAlign::TOP_CENTER, COLOR_OFF, COLOR_ON );
          it.image( (it.get_width()/14)*6 , 0, id(i_next), ImageAlign::TOP_CENTER, COLOR_OFF, COLOR_ON );
          // PAGE
          it.print( it.get_width(), 0, id(f25b), COLOR_OFF, TextAlign::TOP_RIGHT, "Enhet" );

          // THERMOMETER
          it.image( 0, it.get_height()/2, id(i_temp), ImageAlign::LEFT, COLOR_OFF, COLOR_ON );
          // TEMPERATURE
          it.printf( it.get_width()/2, it.get_height()/2, id(f120b), COLOR_OFF, TextAlign::CENTER, "%2.0f", id(temperature_local).state );
          // UNIT
          it.print( it.get_width(), it.get_height()/2, id(f25b), COLOR_OFF, TextAlign::RIGHT, "°C" );

          // Show wifi icon.
          if ( id(component_wifi).is_connected() ) {
            it.image( 0, it.get_height(), id(i_wifi), ImageAlign::BOTTOM_LEFT, COLOR_OFF, COLOR_ON );
          }
          // Show HA icon.
          if ( id(component_api).is_connected() ) {
            it.image( it.get_width(), it.get_height(), id(i_api), ImageAlign::BOTTOM_RIGHT, COLOR_OFF, COLOR_ON );
          }

          // Refresh Timestamp
          // Code by EnsconcE from https://community.home-assistant.io/t/esphome-show-time/348903
          char str[17];
          time_t currTime = id(time_homeassistant).now().timestamp;
          strftime( str, sizeof(str), "%H:%M", localtime(&currTime) );
          it.printf( it.get_width()/2, it.get_height(), id(f18), COLOR_OFF, TextAlign::BOTTOM_CENTER, "@ %s", str );
      - id: page_info
        lambda: |-
          // Fill background.
          it.fill( COLOR_OFF );

          // NAV
          it.image( (it.get_width()/14)*2 , 0, id(i_home), ImageAlign::TOP_CENTER, COLOR_ON, COLOR_OFF );
          it.image( (it.get_width()/14)*4 , 0, id(i_refresh), ImageAlign::TOP_CENTER, COLOR_ON, COLOR_OFF );
          it.image( (it.get_width()/14)*6 , 0, id(i_next), ImageAlign::TOP_CENTER, COLOR_ON, COLOR_OFF );
          // PAGE
          it.image( it.get_width(), 0, id(i_info), ImageAlign::TOP_RIGHT, COLOR_ON, COLOR_OFF );
          
          // BATTERY
          it.print( 0, 57, id(f18), COLOR_ON, TextAlign::BOTTOM_LEFT, "Batteri: " );
          it.printf( it.get_width() - 15, 55, id(f20b), COLOR_ON, TextAlign::BOTTOM_RIGHT, "%.2f", id(bat_adc).state );
          it.print( it.get_width(), 57, id(f16), COLOR_ON, TextAlign::BOTTOM_RIGHT, "V" );

          // DEVICE
          //it.print( it.get_width()/2, 70, id(f20), COLOR_ON, TextAlign::BOTTOM_CENTER, "ESPHome" );
          // NAME
          it.printf( it.get_width()/2, 87, id(f20), COLOR_ON, TextAlign::BOTTOM_CENTER, "%s", App.get_name().c_str() );

          // NETWORK
          //it.print( it.get_width()/2, 110, id(f20), COLOR_ON, TextAlign::BOTTOM_CENTER, "Nettverk" );
          // SSID
          it.printf( it.get_width()/2, 117, id(f20b), COLOR_ON, TextAlign::BOTTOM_CENTER, "%s", id(sensor_ssid).state.c_str() );
          // IP
          it.printf( it.get_width()/2, 143, id(f20b), COLOR_ON, TextAlign::BOTTOM_CENTER, "%s", id(sensor_ip_address).state.c_str() );
          // MAC
          it.printf( it.get_width()/2, 169, id(f20b), COLOR_ON, TextAlign::BOTTOM_CENTER, "%s", id(sensor_mac_address).state.c_str() );

          // Show wifi icon.
          if ( id(component_wifi).is_connected() ) {
            it.image( 0, it.get_height(), id(i_wifi), ImageAlign::BOTTOM_LEFT, COLOR_ON, COLOR_OFF );
          }
          // Show HA icon.
          if ( id(component_api).is_connected() ) {
            it.image( it.get_width(), it.get_height(), id(i_api), ImageAlign::BOTTOM_RIGHT, COLOR_ON, COLOR_OFF );
          }

          // Refresh Timestamp
          // Code by EnsconcE from https://community.home-assistant.io/t/esphome-show-time/348903
          char str[17];
          time_t currTime = id(time_homeassistant).now().timestamp;
          strftime( str, sizeof(str), "%H:%M", localtime(&currTime) );
          it.printf( it.get_width()/2, it.get_height(), id(f18), COLOR_ON, TextAlign::BOTTOM_CENTER, "@ %s", str );
      - id: page_room
        lambda: |-
          // Fill background.
          it.fill(COLOR_OFF);

          // Show loading screen before data is received.
          if ( id(initial_data_received) == false ) {
            it.printf( it.get_width()/2, it.get_height()/2, id(f20b), COLOR_ON, TextAlign::CENTER, "Venter på data..." );
          } else {

            // NAV
            it.image( (it.get_width()/14)*2 , 0, id(i_home), ImageAlign::TOP_CENTER, COLOR_ON, COLOR_OFF );
            it.image( (it.get_width()/14)*4 , 0, id(i_refresh), ImageAlign::TOP_CENTER, COLOR_ON, COLOR_OFF );
            it.image( (it.get_width()/14)*6 , 0, id(i_next), ImageAlign::TOP_CENTER, COLOR_ON, COLOR_OFF );
            // PAGE
            it.print( it.get_width(), 0, id(f25b), COLOR_ON, TextAlign::TOP_RIGHT, "Rom" );

            // GRAPH
            // it.graph( 0, 0, id(graph_temperature_room), COLOR_ON );
            
            // THERMOMETER
            it.image( 0, it.get_height()/2, id(i_temp), ImageAlign::LEFT, COLOR_ON, COLOR_OFF );
            // TEMPERATURE
            it.printf( it.get_width()/2, it.get_height()/2, id(f120b), COLOR_ON, TextAlign::CENTER, "%2.0f", id(temperature_feels_like).state );
            // UNIT
            it.print( it.get_width(), it.get_height()/2, id(f25b), COLOR_ON, TextAlign::RIGHT, "°C" );

            // Show wifi icon.
            if ( id(component_wifi).is_connected() ) {
              it.image( 0, it.get_height(), id(i_wifi), ImageAlign::BOTTOM_LEFT, COLOR_ON, COLOR_OFF );
            }
            // Show HA icon.
            if ( id(component_api).is_connected() ) {
              it.image( it.get_width(), it.get_height(), id(i_api), ImageAlign::BOTTOM_RIGHT, COLOR_ON, COLOR_OFF );
            }

            // Refresh Timestamp
            // Code by EnsconcE from https://community.home-assistant.io/t/esphome-show-time/348903
            char str[17];
            time_t currTime = id(time_homeassistant).now().timestamp;
            strftime( str, sizeof(str), "%H:%M", localtime(&currTime) );
            it.printf( it.get_width()/2, it.get_height(), id(f18), COLOR_ON, TextAlign::BOTTOM_CENTER, "@ %s", str );
          }

font:
  - file:
      type: gfonts
      family: Noto Sans Display
      weight: 500
    id: f16
    size: 16
    glyphs: &norwegian-glyphs [ ' ', ',', '.', ':', '%', '°', '@', '?','~',
      '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '-', '/',
      'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N',
      'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'Æ', 'Ø', 'Å',
      'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n',
      'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'æ', 'ø', 'å']
  - file:
      type: gfonts
      family: Noto Sans Display
      weight: 500
    id: f18
    size: 18
    glyphs: *norwegian-glyphs
  - file:
      type: gfonts
      family: Noto Sans Display
      weight: 500
    id: f20
    size: 20
    glyphs: *norwegian-glyphs
  - file:
      type: gfonts
      family: Noto Sans Display
      weight: 800
    id: f20b
    size: 20
    glyphs: *norwegian-glyphs
  - file:
      type: gfonts
      family: Noto Sans Display
      weight: 700
    id: f25b
    size: 25
    glyphs: *norwegian-glyphs
  - file:
      type: gfonts
      family: Noto Sans Display
      weight: 600
    id: f120b
    size: 120
    glyphs: *norwegian-glyphs

image:
  - id: i_wifi
    file: mdi:wifi
    type: binary
    resize: 28x28
  - id: i_api
    file: mdi:home-assistant
    type: binary
    resize: 28x28

  - id: i_refresh
    file: mdi:refresh
    type: binary
    resize: 28x28
  - id: i_next
    file: mdi:arrow-right-thick
    type: binary
    resize: 28x28
  - id: i_home
    file: mdi:home
    type: binary
    resize: 28x28

  - id: i_info
    file: mdi:information
    type: binary
    resize: 28x28

  - id: i_temp
    file: mdi:thermometer
    type: binary
    resize: 28x28

#graph:
#  - id: graph_temperature_room
#    duration: 8h
#    x_grid: 15min
#    y_grid: 1.0
#    width: 200
#    height: 50
#    border: false
#    traces:
#      - sensor: temperature_feels_like
#        line_thickness: 6
#        continuous: true
#  - id: graph_temperature_local
#    duration: 6h
#    x_grid: 15min
#    y_grid: 1.0
#    width: 200
#    height: 70
#    border: false
#    traces:
#      - sensor: temperature_local
#        line_thickness: 6
#        continuous: true

# Check if person is home
binary_sensor:
  - platform: homeassistant
    entity_id: binary_sensor.etg2_occupancy
    id: motion_detected

  # Stick Up
  - id: !extend stick_up
    on_press:
      - display.page.show: page_local
      - script.execute: update_screen
  # Stick Press
  - id: !extend stick_press
    on_press:
      - script.execute: update_screen
  # Stick Down
  - id: !extend stick_down
    on_press:
      - display.page.show_next: display_eink
      - script.execute: update_screen

sensor:
  # Call sensors from HA.
#  - platform: homeassistant
#    entity_id: sensor.etg2_simen_temperature
#    id: temperature_homeassistant
#    on_value:
#      then:
#        - lambda: 'id(data_updated) = true;'
  - platform: homeassistant
    entity_id: sensor.etg2_simen_tc_heatindex
    id: temperature_feels_like
    on_value:
      then:
        - lambda: 'id(data_updated) = true;'

  # Combine sensors
  - platform: combination
    type: median
    id: temperature_local
    name: "Temperature"
    device_class: "temperature"
    state_class: "measurement"
    sources:
      # ENV III
      - source: temperature_sht30_hat_env
      - source: temperature_qmp6988_hat_env
      # ENV IV
      - source: temperature_bmp280_unit_env
      - source: temperature_sht40_unit_env
      # ENV Pro
#      - source: temperature_bme688
      # CO2
      - source: temperature_scd40_unit_co2
    filters:
      - or:
        - heartbeat: 900s
        - delta: 0.15
    on_value:
      then:
        - lambda: 'id(data_updated) = true;'

  - platform: combination
    type: median
    id: humidity_local
    name: "Humidity"
    device_class: "humidity"
    state_class: "measurement"
    sources:
      # ENV III
      - source: humidity_sht30_hat_env
      # ENV IV
      - source: humidity_sht40_unit_env
      # ENV Pro
#      - source: humidity_bme688
      # CO2
      - source: humidity_scd40_unit_co2
    filters:
      - or:
        - heartbeat: 900s
        - delta: 0.15

  - platform: combination
    type: median
    id: pressure_local
    name: "Pressure"
    device_class: "atmospheric_pressure"
    state_class: "measurement"
    sources:
      # ENV III
      - source: pressure_qmp6988_hat_env
      # ENV IV
      - source: pressure_bmp280_unit_env
      # ENV Pro
#      - source: pressure_bme688
    filters:
      - or:
        - heartbeat: 900s
        - delta: 0.15