packages:
  # --- COMMON PACKAGES ---
  <<: !include_dir_named common
  <<: !include_dir_named bluetooth

  # --- BOARD AND MODULES ---
  board: !include board/m5stack_atom_matrix.yaml

substitutions:
  common:
    log_level: WARN
#    log_baud_rate: "115200"
  device:
    name: m5s-a-m-54bbac
    location: "Storage"
    framework:
      type: esp-idf

esphome:
  comment: ${device.model} @ ${device.location}
  name: ${device.name}
  friendly_name: ${device.name}
  area: ${device.location}
  project:
    version: "1.0.0"

wifi:
  use_address: m5s-a-m-54bbac.local
  manual_ip: 
    gateway: 192.168.68.1
    subnet: 255.255.252.0
    static_ip: 192.168.71.45

display:
  - id: !extend display_matrix
    pages:
      - id: page_bulls_eye_b
        lambda: |-
          // Draw a bulls-eye pattern
          it.rectangle(0, 0, 5, 5, id(c_red));
          it.rectangle(1, 1, 3, 3, id(c_green));
          it.draw_pixel_at(2, 2, id(c_blue));
      - id: page_bulls_eye_g
        lambda: |-
          // Draw a bulls-eye pattern
          it.rectangle(0, 0, 5, 5, id(c_blue));
          it.rectangle(1, 1, 3, 3, id(c_red));
          it.draw_pixel_at(2, 2, id(c_green));
      - id: page_bulls_eye_r
        lambda: |-
          // Draw a bulls-eye pattern
          it.rectangle(0, 0, 5, 5, id(c_green));
          it.rectangle(1, 1, 3, 3, id(c_blue));
          it.draw_pixel_at(2, 2, id(c_red));
      - id: page_a
        lambda: |-
          it.print(0, 0, id(font_5x5), id(c_cyan), "A");
      - id: page_b
        lambda: |-
          it.print(0, 0, id(font_5x5), id(c_magenta), "B");
      - id: page_c
        lambda: |-
          it.print(0, 0, id(font_5x5), id(c_yellow), "C");
