packages:
  # --- COMMON PACKAGES ---
  <<: !include_dir_named common
#  <<: !include_dir_named bluetooth

  # --- BOARD AND MODULES ---
  board: !include board/m5stack_air_quality.yaml
  internal_i2c: !include board/extension/internal_i2c.yaml
  grove_i2c: !include board/extension/grove_i2c.yaml
  env_iv: !include board/module/unit_env_iv.yaml

  # --- FEATURE PACKAGES ---
  combined_env_sensors: !include features/combined_env_sensors.yaml

substitutions:
  devicename: m5s-air-quality-b62db0
  location: "2etg, Gang"
  log_level: WARN
  home_page: page_info

esphome:
  comment: "M5Stack AirQuality @ Trapp"
  name: $devicename
  friendly_name: $devicename
  area: $location
  project:
    version: "1.0.0"

display:
  # 200 x 200 resolution
  - id: !extend display_eink
    pages:
      - id: page_local
        lambda: |-
          // Set graph color
          id(trace_temperature_room)->set_line_color( id(epaper_text_color) );

          // Fill background.
          it.fill(id(epaper_text_color));

          //it.graph( 0, 0, id(graph_temperature_local), id(epaper_bg_color) );
            
          it.print( it.get_width()/2, 0, id(f26b), id(epaper_bg_color), TextAlign::TOP_CENTER, "Enhet" );
          it.printf( it.get_width()/2, it.get_height()/2, id(f130b), id(epaper_bg_color), TextAlign::CENTER, "%2.0f", id(temperature_local).state );

          it.printf( 0, 0, id(f20), id(epaper_bg_color), TextAlign::TOP_LEFT, "%.1f", id(temperature_scd40_aq).state );

          it.printf( it.get_width(), 0, id(f20), id(epaper_bg_color), TextAlign::TOP_RIGHT, "%.1f", id(temperature_sen55).state );

          // Show wifi icon.
          if (id(component_wifi).is_connected()) {
            it.image( 0, it.get_height()+5, id(i_wifi), ImageAlign::BOTTOM_LEFT, id(epaper_bg_color), id(epaper_text_color) );
          }
          // Show HA icon.
          if (id(component_api).is_connected()) {
            it.image( it.get_width(), it.get_height()+5, id(i_api), ImageAlign::BOTTOM_RIGHT, id(epaper_bg_color), id(epaper_text_color) );
          }

          // Refresh Timestamp
          // Code by EnsconcE from https://community.home-assistant.io/t/esphome-show-time/348903
          char str[17];
          time_t currTime = id(time_homeassistant).now().timestamp;
          strftime(str, sizeof(str), "%H:%M", localtime(&currTime));
          it.printf( it.get_width()/2, it.get_height()+3, id(f14), id(epaper_bg_color), TextAlign::BOTTOM_CENTER, "@ %s", str );
      - id: page_info
        lambda: |-
          // Fill background.
          it.fill(id(epaper_bg_color));

          it.print( 0, -1, id(f20b), id(epaper_text_color), TextAlign::TOP_LEFT, "PM 1: " );
          it.print( 0, 25, id(f20b), id(epaper_text_color), TextAlign::TOP_LEFT, "PM 2.5: " );
          it.print( 0, 51, id(f20b), id(epaper_text_color), TextAlign::TOP_LEFT, "PM 4: " );
          it.print( 0, 77, id(f20b), id(epaper_text_color), TextAlign::TOP_LEFT, "PM 10: " );
          it.print( 0, 103, id(f20b), id(epaper_text_color), TextAlign::TOP_LEFT, "CO2: " );
          it.print( 0, 129, id(f20b), id(epaper_text_color), TextAlign::TOP_LEFT, "VOC: " );
          it.print( 0, 155, id(f20b), id(epaper_text_color), TextAlign::TOP_LEFT, "NOx: " );

          it.printf( it.get_width()-55, -2, id(f26b), id(epaper_text_color), TextAlign::TOP_RIGHT, "%.1f", id(pm1_0_sen55).state );
          it.print( it.get_width(), 0, id(f18), id(epaper_text_color), TextAlign::TOP_RIGHT, "µg/m³" );

          it.printf( it.get_width()-55, 24, id(f26b), id(epaper_text_color), TextAlign::TOP_RIGHT, "%.1f", id(pm2_5_sen55).state );
          it.print( it.get_width(), 26, id(f18), id(epaper_text_color), TextAlign::TOP_RIGHT, "µg/m³" );

          it.printf( it.get_width()-55, 50, id(f26b), id(epaper_text_color), TextAlign::TOP_RIGHT, "%.1f", id(pm4_0_sen55).state );
          it.print( it.get_width(), 52, id(f18), id(epaper_text_color), TextAlign::TOP_RIGHT, "µg/m³" );

          it.printf( it.get_width()-55, 76, id(f26b), id(epaper_text_color), TextAlign::TOP_RIGHT, "%.1f", id(pm10_0_sen55).state );
          it.print( it.get_width(), 78, id(f18), id(epaper_text_color), TextAlign::TOP_RIGHT, "µg/m³" );

          it.printf( it.get_width()-55, 102, id(f26b), id(epaper_text_color), TextAlign::TOP_RIGHT, "%.0f", id(co2_scd40_aq).state );
          it.print( it.get_width(), 104, id(f18), id(epaper_text_color), TextAlign::TOP_RIGHT, "ppm" );

          it.printf( it.get_width()-55, 128, id(f26b), id(epaper_text_color), TextAlign::TOP_RIGHT, "%.0f", id(voc_sen55).state );
          it.print( it.get_width(), 130, id(f18), id(epaper_text_color), TextAlign::TOP_RIGHT, "ppb" );

          it.printf( it.get_width()-55, 154, id(f26b), id(epaper_text_color), TextAlign::TOP_RIGHT, "%.0f", id(nox_sen55).state );
          it.print( it.get_width(), 156, id(f18), id(epaper_text_color), TextAlign::TOP_RIGHT, "ppb" );

          // Show wifi icon.
          if (id(component_wifi).is_connected()) {
            it.image(0, it.get_height()+6, id(i_wifi), ImageAlign::BOTTOM_LEFT, id(epaper_text_color), id(epaper_bg_color));
          }
          // Show HA icon.
          if (id(component_api).is_connected()) {
            it.image(it.get_width(), it.get_height()+6, id(i_api), ImageAlign::BOTTOM_RIGHT, id(epaper_text_color), id(epaper_bg_color));
          }

          // Refresh Timestamp
          // Code by EnsconcE from https://community.home-assistant.io/t/esphome-show-time/348903
          char str[17];
          time_t currTime = id(time_homeassistant).now().timestamp;
          strftime(str, sizeof(str), "%H:%M", localtime(&currTime));
          it.printf( it.get_width()/2, it.get_height()+3, id(f14), id(epaper_text_color), TextAlign::BOTTOM_CENTER, "@ %s", str );
      - id: page_room
        lambda: |-
          // Set graph color
          id(trace_temperature_room)->set_line_color( id(epaper_text_color) );
          
          // Fill background.
          it.fill(id(epaper_bg_color));

          // Show loading screen before data is received.
          if (id(initial_data_received) == false) {
            it.printf(it.get_width()/2, it.get_height()/2, id(f20b), id(epaper_text_color), TextAlign::CENTER, "Venter på data...");
          } else {

            it.graph(0, 0, id(graph_temperature_room), id(epaper_text_color));
            
            it.print(0, 45, id(f20), id(epaper_text_color), TextAlign::TOP_LEFT, "Rom");
            it.print(it.get_width(), 45, id(f26b), id(epaper_text_color), TextAlign::TOP_RIGHT, "°C");
            it.printf(it.get_width()/2, 166, id(f130b), id(epaper_text_color), TextAlign::BASELINE_CENTER, "%2.0f", id(temperature_feels_like).state);

            // Show wifi icon.
            if (id(component_wifi).is_connected()) {
              it.image(0, it.get_height()+5, id(i_wifi), ImageAlign::BOTTOM_LEFT, id(epaper_text_color), id(epaper_bg_color));
            }
            // Show HA icon.
            if (id(component_api).is_connected()) {
              it.image(it.get_width(), it.get_height()+5, id(i_api), ImageAlign::BOTTOM_RIGHT, id(epaper_text_color), id(epaper_bg_color));
            }

            // Refresh Timestamp
            // Code by EnsconcE from https://community.home-assistant.io/t/esphome-show-time/348903
            char str[17];
            time_t currTime = id(time_homeassistant).now().timestamp;
            strftime(str, sizeof(str), "%H:%M", localtime(&currTime));
            it.printf(it.get_width()/2, it.get_height()+3, id(f14), id(epaper_text_color), TextAlign::BOTTOM_CENTER, "@ %s", str);
          }

font:
  - file:
      type: gfonts
      family: Noto Sans Display
      weight: 500
    id: f14
    size: 14
    glyphs: &norwegian-glyphs [ ' ', ',', '.', ':', '%', '°', '@', '?','~',
      '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '-', '/', 'µ', '³',
      'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N',
      'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'Æ', 'Ø', 'Å',
      'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n',
      'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'æ', 'ø', 'å']
  - file:
      type: gfonts
      family: Noto Sans Display
      weight: 500
    id: f18
    size: 18
    glyphs: *norwegian-glyphs
  - file:
      type: gfonts
      family: Noto Sans Display
      weight: 500
    id: f20
    size: 20
    glyphs: *norwegian-glyphs
  - file:
      type: gfonts
      family: Noto Sans Display
      weight: 800
    id: f20b
    size: 20
    glyphs: *norwegian-glyphs
  - file:
      type: gfonts
      family: Noto Sans Display
      weight: 700
    id: f26b
    size: 26
    glyphs: *norwegian-glyphs
  - file:
      type: gfonts
      family: Noto Sans Display
      weight: 600
    id: f130b
    size: 130
    glyphs: *norwegian-glyphs

image:
  - id: i_wifi
    file: mdi:wifi
    type: binary
    resize: 28x28
  - id: i_api
    file: mdi:home-assistant
    type: binary
    resize: 28x28

# Check if person is home
binary_sensor:
  - platform: homeassistant
    entity_id: binary_sensor.etg2_occupancy
    id: motion_detected

graph:
  - id: graph_temperature_room
    duration: 8h
#    x_grid: 15min
#    y_grid: 1.0
    width: 200
    height: 50
    border: false
    traces:
      - id: trace_temperature_room
        sensor: temperature_feels_like
        line_thickness: 6
        continuous: true
#  - id: graph_temperature_local
#    duration: 6h
#    x_grid: 15min
#    y_grid: 1.0
#    width: 200
#    height: 50
#    border: false
#    traces:
#      - sensor: temperature_local
#        line_thickness: 6
#        continuous: true

sensor:
  # Call sensors from HA.
  - platform: homeassistant
    entity_id: sensor.etg2_gang_temperature
    id: temperature_homeassistant
    on_value:
      then:
        - lambda: 'id(data_updated) = true;'
  - platform: homeassistant
    entity_id: sensor.etg2_ellen_svein_tc_heatindex
    id: temperature_feels_like
    on_value:
      then:
        - lambda: 'id(data_updated) = true;'

  # Combine sensors
  - id: !extend temperature_local
    sources:
      # Base BTC
#      - source: temperature_sht30_base_btc
      # HAT ENV III
#      - source: temperature_sht30_hat_env
#      - source: temperature_qmp6988_hat_env
      # Unit ENV III
#      - source: temperature_sht30_unit_env
#      - source: temperature_qmp6988_unit_env
      # Unit ENV IV
      - source: temperature_bmp280_unit_env
      - source: temperature_sht40_unit_env
      # Unit ENV Pro
#      - source: temperature_bme688
      # Unit CO2
#      - source: temperature_scd40_unit_co2
      # Gyro
#      - source: temperature_mpu6886
      # AirQuality
      - source: temperature_sen55
      - source: temperature_scd40_aq
    on_value:
      then:
        - lambda: 'id(data_updated) = true;'

  - id: !extend humidity_local
    sources:
      # Base BTC
#      - source: humidity_sht30_base_btc
      # HAT ENV III
#      - source: humidity_sht30_hat_env
      # Unit ENV III
#      - source: humidity_sht30_unit_env
      # Unit ENV IV
      - source: humidity_sht40_unit_env
      # Unit ENV Pro
#      - source: humidity_bme688
      # Unit CO2
#      - source: humidity_scd40_unit_co2
      # AirQuality
      - source: humidity_sen55
      - source: humidity_scd40_aq
    on_value:
      then:
        - lambda: 'id(data_updated) = true;'

  - id: !extend pressure_local
    sources:
      # HAT ENV III
#      - source: pressure_qmp6988_hat_env
      # Unit ENV III
#      - source: pressure_qmp6988_unit_env
      # Unit ENV IV
      - source: pressure_bmp280_unit_env
      # Unit ENV Pro
#      - source: pressure_bme688
    on_value:
      then:
        - lambda: 'id(data_updated) = true;'