packages:
  # --- COMMON PACKAGES ---
  <<: !include_dir_named common
  <<: !include_dir_named bluetooth

  # --- BOARD AND MODULES ---
  board: !include board/m5stack_fire.yaml
  go_base: !include board/module/base_m5go_bottom.yaml
  grove_i2c: !include board/extension/grove_i2c.yaml
  env: !include board/module/unit_env_iv.yaml
  pir: !include board/module/unit_pir.yaml

  # --- GUI PACKAGES ---
  colors: !include gui/themes/colors_night_owl.yaml
  lvgl: !include gui/240x320.yaml

  # --- LVGL WIDGET PACKAGES ---
  room_temperature_widget_sensors: !include { file: gui/widgets/labels/number_sensor.yaml, vars: {
    uid: room_temp_value,
    entity_id: sensor.t22_temperature
  }}

substitutions:
  devicename: m5s-fire-a70780
  location: "2etg, Stue"
  log_level: WARN
  home_page: page_temperature

esphome:
  comment: "M5Stack Fire @ Stue"
  name: $devicename
  friendly_name: $devicename
  area: $location

binary_sensor:
  # Call sensors from HA.
  - platform: homeassistant
    entity_id: binary_sensor.etg2_stue_occupancy
    id: motion_stue
  - platform: homeassistant
    entity_id: binary_sensor.etg2_gang_occupancy
    id: motion_gang
  # Turn on display while room is occupied
  - platform: template
    id: motion_detected
    lambda: !lambda |-
      if ( (id(motion_stue).state) or (id(motion_gang).state) ) {
        return true;
      } else {
        return false;
      }
    on_state: 
      then:
        - script.execute: display_on_off

sensor:
  # Combine sensors
  - platform: combination
    type: median
    id: temperature_local
    name: "Temperature"
    device_class: "temperature"
    state_class: "measurement"
    sources:
      # ENV III
#      - source: temperature_sht30_hat_env
#      - source: temperature_qmp6988_hat_env
      # ENV IV
      - source: temperature_bmp280_unit_env
      - source: temperature_sht40_unit_env
      # ENV Pro
#      - source: temperature_bme688
      # CO2
#      - source: temperature_scd40_unit_co2
    filters:
      - or:
        - heartbeat: 900s
        - delta: 0.15
