packages:
  # --- COMMON PACKAGES ---
  <<: !include_dir_named common
#  <<: !include_dir_named bluetooth

  # --- BOARD AND MODULES ---
  board: !include board/m5stack_core_s3se.yaml
  mbus_i2c: !include board/extension/mbus_i2c.yaml
  grove_i2c: !include board/extension/grove_i2c.yaml
  mbus_uart: !include board/extension/mbus_uart.yaml
  air_quality: !include board/module/module_air_quality.yaml
  base_btc: !include board/module/base_btc.yaml
  env_iv: !include board/module/unit_env_iv.yaml
  co2: !include board/module/unit_co2.yaml

  # --- FEATURE PACKAGES ---
  combined_env_sensors: !include features/combined_env_sensors.yaml

  # --- GUI PACKAGES ---
  colors: !include gui/themes/colors_night_owl.yaml
  lvgl: !include gui/240x320.yaml

  # --- LVGL WIDGET PACKAGES ---
  room_temperature_widget_sensors: !include { file: gui/widgets/labels/number_sensor.yaml, vars: {
    uid: room_temp_value,
    entity_id: sensor.etg2_stue_temperature
  }}

substitutions:
  common:
    log_level: WARN
#    log_baud_rate: "0"
  device:
    name: m5s-c3se-e93464
    location: "2etg, Stue"
  module:
    internal:
      i2c_bus: i2c_mbus
  display:
    home_page: page_temperature

esphome:
  comment: 'M5Stack Core3 SE @ Stue'
  name: ${device.name}
  friendly_name: ${device.name}
  area: ${device.location}
  project:
    version: "1.0.0"

# --- LVGL CLOCKS ---
time:
  - id: !extend time_homeassistant
    on_time_sync:
      - script.execute: lvgl_time_update
      - pcf8563.write_time:
    on_time:
      - minutes: '*'
        seconds: 0
        then:
          - script.execute: lvgl_time_update

lvgl:
  buffer_size: 75%
  pages:
    - id: page_airq
      pad_top: 32
      pad_bottom: 32
      on_load:
        - lvgl.label.update:
            id: lbl_page_title
            text: Luftkvalitet
      <<: !include
        file: gui/functions/swipe_navigation.yaml
      widgets:
        - obj:
            pad_top: 1
            pad_bottom: 1
            pad_left: 4
            pad_right: 4
            scrollable: false
            align: CENTER
            height: 100%
            width: 100%
            layout:
              type: FLEX
              flex_flow: COLUMN
              flex_align_main: SPACE_EVENLY
              flex_align_cross: CENTER
              flex_align_track: CENTER
              pad_row: 0
              pad_column: 0
            widgets:
              # --- Row 1: Temperature ---
              - obj:
                  # This is a container for a single row
                  width: 100%
                  height: SIZE_CONTENT
                  pad_all: 0
                  pad_left: 4
                  pad_right: 4
                  layout:
                    type: FLEX
                    flex_flow: ROW
                    flex_align_main: SPACE_BETWEEN
                    flex_align_cross: CENTER
                    pad_row: 0
                    pad_column: 0
                  widgets:
                    # Descriptor Label
                    - label:
                        id: lbl_temp_local_l
                        text: "Temperatur: "
                        pad_left: 4
                        pad_right: 4
                        text_font: font_sm
                        text_color: c_text_s
                    # Value Label
                    - label:
                        id: lbl_temp_local_value
                        text: "?"
                        pad_right: 4
                        text_font: font_lg
                        text_color: c_text_p
                    # Unit Label
                    - label:
                        id: lbl_temp_local_unit
                        text: "°C"
                        text_font: font_md
                        text_color: c_text_s

              # --- Row 2: Carbonmonoxide ---
              - obj:
                  width: 100%
                  height: SIZE_CONTENT
                  pad_all: 0
                  pad_left: 4
                  pad_right: 4
                  layout:
                    type: FLEX
                    flex_flow: ROW
                    flex_align_main: SPACE_BETWEEN
                    flex_align_cross: CENTER
                    pad_row: 0
                    pad_column: 0
                  widgets:
                    # Descriptor Label
                    - label:
                        id: lbl_co2_l
                        text: "Karbondioksid: "
                        pad_left: 4
                        pad_right: 4
                        text_font: font_sm
                        text_color: c_text_s
                    # Value Label
                    - label:
                        id: lbl_co2_value
                        text: "?"
                        pad_right: 4
                        text_font: font_lg
                        text_color: c_text_p
                    # Unit Label
                    - label:
                        id: lbl_co2_unit
                        text: "ppm"
                        text_font: font_md
                        text_color: c_text_s

              # --- Row 3: PM1.0 ---
              - obj:
                  width: 100%
                  height: SIZE_CONTENT
                  pad_all: 0
                  pad_left: 4
                  pad_right: 4
                  layout:
                    type: FLEX
                    flex_flow: ROW
                    flex_align_main: SPACE_BETWEEN
                    flex_align_cross: CENTER
                    pad_row: 0
                    pad_column: 0
                  widgets:
                    # Descriptor Label
                    - label:
                        id: lbl_pm1_l
                        text: "Svevestøv 1.0: "
                        pad_left: 4
                        pad_right: 4
                        text_font: font_sm
                        text_color: c_text_s
                    # Value Label
                    - label:
                        id: lbl_pm1_value
                        text: "?"
                        pad_right: 4
                        text_font: font_lg
                        text_color: c_text_p
                    # Unit Label
                    - label:
                        id: lbl_pm1_unit
                        text: "µg/m³"
                        text_font: font_md
                        text_color: c_text_s

              # --- Row 4: PM2.5 ---
              - obj:
                  width: 100%
                  height: SIZE_CONTENT
                  pad_all: 0
                  pad_left: 4
                  pad_right: 4
                  layout:
                    type: FLEX
                    flex_flow: ROW
                    flex_align_main: SPACE_BETWEEN
                    flex_align_cross: CENTER
                    pad_row: 0
                    pad_column: 0
                  widgets:
                    # Descriptor Label
                    - label:
                        id: lbl_pm25_l
                        text: "Svevestøv 2.5: "
                        pad_left: 4
                        pad_right: 4
                        text_font: font_sm
                        text_color: c_text_s
                    # Value Label
                    - label:
                        id: lbl_pm25_value
                        text: "?"
                        pad_right: 4
                        text_font: font_lg
                        text_color: c_text_p
                    # Unit Label
                    - label:
                        id: lbl_pm25_unit
                        text: "µg/m³"
                        text_font: font_md
                        text_color: c_text_s

              # --- Row 5: PM10.0 ---
              - obj:
                  width: 100%
                  height: SIZE_CONTENT
                  pad_all: 0
                  pad_left: 4
                  pad_right: 4
                  layout:
                    type: FLEX
                    flex_flow: ROW
                    flex_align_main: SPACE_BETWEEN
                    flex_align_cross: CENTER
                    pad_row: 0
                    pad_column: 0
                  widgets:
                    # Descriptor Label
                    - label:
                        id: lbl_pm10_l
                        text: "Svevestøv 10.0: "
                        pad_left: 4
                        pad_right: 4
                        text_font: font_sm
                        text_color: c_text_s
                    # Value Label
                    - label:
                        id: lbl_pm10_value
                        text: "?"
                        pad_right: 4
                        text_font: font_lg
                        text_color: c_text_p
                    # Unit Label
                    - label:
                        id: lbl_pm10_unit
                        text: "µg/m³"
                        text_font: font_md
                        text_color: c_text_s

binary_sensor:
  # Call sensors from HA.
  - platform: homeassistant
    entity_id: binary_sensor.etg2_stue_occupancy
    id: motion_stue
  - platform: homeassistant
    entity_id: binary_sensor.etg2_gang_occupancy
    id: motion_gang
  # Turn on display while room is occupied
  - platform: template
    id: motion_detected
    lambda: !lambda |-
      if ( (id(motion_stue).state) or (id(motion_gang).state) ) {
        return true;
      } else {
        return false;
      }
    on_state: 
      then:
        - script.execute: display_on_off

sensor:
  # Combine sensors
  - id: !extend temperature_local
    sources:
      # Base BTC
      - source: temperature_sht30_base_btc
      # HAT ENV III
#      - source: temperature_sht30_hat_env
#      - source: temperature_qmp6988_hat_env
      # Unit ENV III
#      - source: temperature_sht30_unit_env
#      - source: temperature_qmp6988_unit_env
      # Unit ENV IV
      - source: temperature_bmp280_unit_env
      - source: temperature_sht40_unit_env
      # Unit ENV Pro
#      - source: temperature_bme688
      # Unit CO2
      - source: temperature_scd40_unit_co2
    on_value: 
      then:
        - lvgl.label.update:
            id: lbl_temp_local_value
            text:
              format: "%.1f"
              args: [ 'x' ]

  - id: !extend humidity_local
    sources:
      # Base BTC
      - source: humidity_sht30_base_btc
      # HAT ENV III
#      - source: humidity_sht30_hat_env
      # Unit ENV III
#      - source: humidity_sht30_unit_env
      # Unit ENV IV
      - source: humidity_sht40_unit_env
      # Unit ENV Pro
#      - source: humidity_bme688
      # Unit CO2
      - source: humidity_scd40_unit_co2

  - id: !extend pressure_local
    sources:
      # HAT ENV III
#      - source: pressure_qmp6988_hat_env
      # Unit ENV III
#      - source: pressure_qmp6988_unit_env
      # Unit ENV IV
      - source: pressure_bmp280_unit_env
      # Unit ENV Pro
#      - source: pressure_bme688

  # extend sensors to update lvgl
  - id: !extend unit_co2_scd40_sensor
    co2:
      on_value:
        then:
          - lvgl.label.update:
              id: lbl_co2_value
              text:
                format: "%.0f"
                args: [ 'x' ]
  - id: !extend pmsx003_sensor
    pm_1_0:
      on_value:
        then:
          - lvgl.label.update:
              id: lbl_pm1_value
              text:
                format: "%.1f"
                args: [ 'x' ]
    pm_2_5:
      on_value:
        then:
          - lvgl.label.update:
              id: lbl_pm25_value
              text:
                format: "%.1f"
                args: [ 'x' ]
    pm_10_0:
      on_value:
        then:
          - lvgl.label.update:
              id: lbl_pm10_value
              text:
                format: "%.1f"
                args: [ 'x' ]
