packages:
  <<: !include_dir_named common
  <<: !include_dir_named bluetooth
  board: !include board/m5stack_atom_s3_lite.yaml
  hat: !include board/extension/hat_i2c.yaml
  grove: !include board/extension/grove_i2c.yaml
  env_iii: !include board/module/hat_env_iii.yaml
  env_iv: !include board/module/unit_env_iv.yaml

substitutions:
  devicename: m5s-as3-lite-953844

esphome:
  comment: "M5Stack Atom S3 Lite 953844"
  name: $devicename
  friendly_name: $devicename
  project:
    version: "1.0.0"

esp32:
#  framework:
#    type: arduino
  framework:
    type: esp-idf

sensor:
  # Combine sensors
  - platform: combination
    type: median
    id: temperature_local
    name: "Temperature"
    device_class: "temperature"
    state_class: "measurement"
    sources:
      # ENV III
      - source: temperature_sht3xd
      - source: temperature_qmp6988
      # ENV IV
      - source: temperature_bmp280
      - source: temperature_sht4x
    filters:
      - or:
        - heartbeat: 900s
        - delta: 0.15