packages:
  <<: !include_dir_named common
# might be too weak for BLE ?
  <<: !include_dir_named bluetooth
  board: !include board/m5stack_nano_c6.yaml
  grove: !include board/extension/grove_i2c.yaml
  env_iii: !include board/module/unit_env_iii.yaml
  tvoc: !include board/module/unit_tvoc.yaml

substitutions:
  devicename: m5s-nano-c6-1d8ec8
  location: "1etg, TV Stue"
  log_level: WARN

esphome:
  comment: "M5Stack NanoC6 1d8ec8"
  name: $devicename
  friendly_name: $devicename
  area: $location
  project:
    version: "1.0.0"

esp32:
  framework:
    type: esp-idf
    version: 5.4.0
    platform_version: espressif32 @ 6.10.0

i2c:
  - id: !extend i2c_grove
    scan: false

sensor:
  # Combine sensors
  - platform: combination
    type: median
    id: temperature_local
    name: "Temperature"
    device_class: "temperature"
    state_class: "measurement"
    sources:
      # ENV III
      - source: temperature_sht30_unit_env
      - source: temperature_qmp6988_unit_env
      # ENV IV
#      - source: temperature_bmp280_unit_env
#      - source: temperature_sht40_unit_env
      # ENV Pro
#      - source: temperature_bme688
      # CO2
#      - source: temperature_scd40_unit_co2
    filters:
      - or:
        - heartbeat: 900s
        - delta: 0.15

  - platform: combination
    type: median
    id: humidity_local
    name: "Humidity"
    device_class: "humidity"
    state_class: "measurement"
    sources:
      # ENV III
      - source: humidity_sht30_unit_env
      # ENV IV
#      - source: humidity_sht40_unit_env
      # ENV Pro
#      - source: humidity_bme688
      # CO2
#      - source: humidity_scd40_unit_co2
    filters:
      - or:
        - heartbeat: 900s
        - delta: 0.15

  - platform: combination
    type: median
    id: pressure_local
    name: "Pressure"
    device_class: "atmospheric_pressure"
    state_class: "measurement"
    sources:
      # ENV III
      - source: pressure_qmp6988_unit_env
      # ENV IV
#      - source: pressure_bmp280_unit_env
      # ENV Pro
#      - source: pressure_bme688
    filters:
      - or:
        - heartbeat: 900s
        - delta: 0.15
