packages:
  # --- COMMON PACKAGES ---
  <<: !include_dir_named common
#  <<: !include_dir_named bluetooth

  # --- BOARD AND MODULES ---
  board: !include board/m5stack_stickc_plus2.yaml
  hat: !include board/extension/hat_i2c.yaml
  env_iii: !include board/module/hat_env_iii.yaml
#  grove: !include board/extension/grove_i2c.yaml
#  co2: !include board/module/unit_co2.yaml
#  multiplexer: !include board/extension/unit_pa_hub.yaml

  # --- GUI PACKAGES ---
  colors: !include gui/themes/colors_night_owl.yaml
  lvgl: !include gui/135x240.yaml

  # --- LVGL WIDGET PACKAGES ---
  room_temperature_widget_sensors: !include { file: gui/widgets/labels/number_sensor.yaml, vars: {
    uid: room_temp_value,
    entity_id: sensor.t22_temperature
  }}

substitutions:
  devicename: m5s-stickc-plus2-9a09b0
  log_level: WARN
#  log_baud_rate: "115200"
  location: "1etg, Bad"
  home_page: page_temperature

esphome:
  comment: "M5Stack StickC Plus2 @ Bad"
  name: $devicename
  friendly_name: $devicename
  area: $location
  project: 
    version: "1.0.0"

# --- LVGL CLOCKS ---
time:
  - id: !extend time_homeassistant
    on_time_sync:
      - script.execute: lvgl_time_update
    on_time:
      - minutes: '*'
        seconds: 0
        then:
          - script.execute: lvgl_time_update

lvgl:
  buffer_size: 75%

# 1.14 inch, 135*240 Colorful TFT LCD, ST7789v2
#display:
#  - id: !extend display_lcd
    # Rotate 270 swap dimensions
#    dimensions:
#      height: 135
#      width: 240
#      offset_height: 52
#      offset_width: 40
#    transform:
#      swap_xy: true
#      mirror_y: true

binary_sensor:
  # Call sensors from HA.
  - platform: homeassistant
    entity_id: binary_sensor.etg2_simen_occupancy
    id: motion_simen
  - platform: homeassistant
    entity_id: binary_sensor.etg2_gang_occupancy
    id: motion_gang
  # Turn on display while room is occupied
  - platform: template
    id: motion_detected
    lambda: !lambda |-
      if ( (id(motion_simen).state) or (id(motion_gang).state) ) {
        return true;
      } else {
        return false;
      }
    on_state: 
      then:
        - script.execute: display_on_off

  # Side Button
  - id: !extend button_side
    on_press:
      - script.execute: go_home
  # Front Button
  - id: !extend button_front
    on_press:
      - lvgl.page.next

sensor:
  # UNIT KMeterISO
#  - platform: kmeteriso
#    i2c_id: i2c_pa_hub_c0
#    id: kmeteriso_0_sensor
#    temperature:
#      id: temperature_kmeteriso_0
#      name: "Temperature KMeterISO 0"
#      device_class: "temperature"
#      state_class: "measurement"
#      filters:
#        - sliding_window_moving_average:
#            window_size: 10
#            send_every: 5
#    internal_temperature:
#      id: temperature_kmeteriso_0_internal
#      name: "Temperature KMeterISO 0 Internal"
#      device_class: "temperature"
#      state_class: "measurement"
#      disabled_by_default: true
#      filters:
#        - sliding_window_moving_average:
#            window_size: 20
#            send_every: 10
#    update_interval: 3s

#  - platform: kmeteriso
#    i2c_id: i2c_pa_hub_c1
#    id: kmeteriso_1_sensor
#    temperature:
#      id: temperature_kmeteriso_1
#      name: "Temperature KMeterISO 1"
#      device_class: "temperature"
#      state_class: "measurement"
#      filters:
#        - sliding_window_moving_average:
#            window_size: 10
#            send_every: 5
#    internal_temperature:
#      id: temperature_kmeteriso_1_internal
#      name: "Temperature KMeterISO 1 Internal"
#      device_class: "temperature"
#      state_class: "measurement"
#      disabled_by_default: true
#      filters:
#        - sliding_window_moving_average:
#            window_size: 20
#            send_every: 10
#    update_interval: 3s

  # Combine sensors
#  - platform: combination
#    type: median
#    id: temperature_kmeteriso_mix
#    name: "Temperature KMeterISO Mix"
#    device_class: "temperature"
#    state_class: "measurement"
#    sources:
      # KMeterISO
#      - source: temperature_kmeteriso_0
#      - source: temperature_kmeteriso_1
#    filters:
#      - or:
#        - heartbeat: 900s
#        - delta: 0.15

  - platform: combination
    type: median
    id: temperature_local
    name: "Temperature"
    device_class: "temperature"
    state_class: "measurement"
    sources:
      # ENV III
      - source: temperature_sht30_hat_env
      - source: temperature_qmp6988_hat_env
      # ENV IV
#      - source: temperature_bmp280_unit_env
#      - source: temperature_sht40_unit_env
      # ENV Pro
#      - source: temperature_bme688
      # CO2
#      - source: temperature_scd40_unit_co2
    filters:
      - or:
        - heartbeat: 900s
        - delta: 0.15

  - platform: combination
    type: median
    id: humidity_local
    name: "Humidity"
    device_class: "humidity"
    state_class: "measurement"
    sources:
      # ENV III
      - source: humidity_sht30_hat_env
      # ENV IV
#      - source: humidity_sht40_unit_env
      # ENV Pro
#      - source: humidity_bme688
      # CO2
#      - source: humidity_scd40_unit_co2
    filters:
      - or:
        - heartbeat: 900s
        - delta: 0.15

  - platform: combination
    type: median
    id: pressure_local
    name: "Pressure"
    device_class: "atmospheric_pressure"
    state_class: "measurement"
    sources:
      # ENV III
      - source: pressure_qmp6988_hat_env
      # ENV IV
#      - source: pressure_bmp280_unit_env
      # ENV Pro
#      - source: pressure_bme688
    filters:
      - or:
        - heartbeat: 900s
        - delta: 0.15