packages:
  <<: !include_dir_named common
  <<: !include_dir_named bluetooth
  board: !include board/m5stack_atom_s3u_arduino.yaml
  grove: !include board/extension/grove_i2c.yaml
  env: !include board/module/unit_env_pro.yaml

substitutions:
  devicename: m5s-as3u-b62a18
  location: "1etg, Kjøkken"
  log_level: WARN

esphome:
  comment: "M5Stack Atom S3U @ Kjøkken"
  name: $devicename
  friendly_name: $devicename
  area: $location
  project:
    version: "1.0.0"

esp32:
  framework:
    type: arduino
