packages:
  <<: !include_dir_named common
  <<: !include_dir_named bluetooth
  board: !include board/m5stack_atom_s3_lite.yaml
  hat: !include board/extension/hat_i2c.yaml
  grove: !include board/extension/grove_i2c.yaml
  env_iii: !include board/module/hat_env_iii.yaml
  co2: !include board/module/unit_co2.yaml
  tvoc: !include board/module/unit_tvoc.yaml

substitutions:
  devicename: m5s-as3-lite-953844
  location: "1etg, TV Stue"
  log_level: WARN

esphome:
  comment: "M5Stack Atom S3 Lite @ TV Stue"
  name: $devicename
  friendly_name: $devicename
  area: $location
  project:
    version: "1.0.0"

esp32:
  framework:
    type: esp-idf

wifi:
  enable_btm: true
  enable_rrm: true

sensor:
  # Combine sensors
  - platform: combination
    type: median
    id: temperature_local
    name: "Temperature"
    device_class: "temperature"
    state_class: "measurement"
    sources:
      # ENV III
      - source: temperature_sht30_hat_env
      - source: temperature_qmp6988_hat_env
      # CO2
      - source: temperature_scd40_unit_co2
    filters:
      - or:
        - heartbeat: 900s
        - delta: 0.15

  - platform: combination
    type: median
    id: humidity_local
    name: "Humidity"
    device_class: "humidity"
    state_class: "measurement"
    sources:
      # ENV III
      - source: humidity_sht30_hat_env
      # CO2
      - source: humidity_scd40_unit_co2
    filters:
      - or:
        - heartbeat: 900s
        - delta: 0.15