packages:
  # --- COMMON PACKAGES ---
  <<: !include_dir_named common

  # --- BOARD AND MODULES ---
  board: !include board/m5stack_atom_s3r_m12.yaml
  rgb_led: !include board/module/unit_rgb3.yaml

substitutions:
  common:
#    log_level: WARN
#    log_baud_rate: "115200"
  device:
    name: m5s-as3r-m12-bd2214
    location: "Storage"
    framework:
      type: esp-idf
  module:
    camera:
      model: OV3640
      resolution: 1024x768
      jpeg_quality: 20
      agc_gain_ceiling: 128x

esphome:
  comment: ${device.model} @ ${device.location}
  name: ${device.name}
  friendly_name: ${device.name}
  area: ${device.location}

wifi:
  use_address: ${device.name}.local
  manual_ip: 
    gateway: 192.168.68.1
    subnet: 255.255.252.0
    static_ip: 192.168.71.75
