packages:
  # --- COMMON PACKAGES ---
  <<: !include_dir_named common

substitutions:
  devicename: rf-link

esphome:
  comment: "Tuya 433Mhz Hub"
  name: $devicename
  friendly_name: $devicename
  project:
    name: "Tuya.RfLink"
    version: "1.0.0"

esp8266:
  board: esp01_1m

logger:
  id: component_logger
  baud_rate: 0


remote_receiver:
  pin: 4
  dump: rc_switch

remote_transmitter:
  pin: 5
  carrier_duty_percent: 100%

binary_sensor:
# Open
  - platform: remote_receiver
    id: mail_open_signal_1
    on_press:
      then:
        - switch.template.publish:
            id: mailbox_switch
            state: ON
    rc_switch_raw:
      code: "010000010111111000000110"
      protocol: 4
    filters:
      delayed_off: 100ms
  - platform: remote_receiver
    id: mail_open_signal_2
    on_press:
      then:
        - switch.template.publish:
            id: mailbox_switch
            state: ON
    rc_switch_raw:
      code: "010000010111111000000110"
      protocol: 5
    filters:
      delayed_off: 100ms
  - platform: remote_receiver
    id: mail_open_signal_3
    on_press:
      then:
        - switch.template.publish:
            id: mailbox_switch
            state: ON
    rc_switch_raw:
      code: "000001010111111000000110"
      protocol: 4
    filters:
      delayed_off: 100ms
  - platform: remote_receiver
    id: mail_open_signal_4
    on_press:
      then:
        - switch.template.publish:
            id: mailbox_switch
            state: ON
    rc_switch_raw:
      code: "010001010111110000000110"
      protocol: 4
    filters:
      delayed_off: 100ms
  - platform: remote_receiver
    id: mail_open_signal_5
    on_press:
      then:
        - switch.template.publish:
            id: mailbox_switch
            state: ON
    rc_switch_raw:
      code: "0100010101111"
      protocol: 4
    filters:
      delayed_off: 100ms
  - platform: remote_receiver
    id: mail_open_signal_6
    on_press:
      then:
        - switch.template.publish:
            id: mailbox_switch
            state: ON
    rc_switch_raw:
      code: "000001010111111000000110"
      protocol: 5
    filters:
      delayed_off: 100ms
# Close
  - platform: remote_receiver
    id: mail_close_signal_1
    on_press:
      then:
        - switch.template.publish:
            id: mailbox_switch
            state: OFF
    rc_switch_raw:
      code: "010000010111111000000110"
      protocol: 4
    filters:
      delayed_off: 100ms
  - platform: remote_receiver
    id: mail_close_signal_2
    on_press:
      then:
        - switch.template.publish:
            id: mailbox_switch
            state: OFF
    rc_switch_raw:
      code: "010000010111111000000110"
      protocol: 5
    filters:
      delayed_off: 100ms

  - platform: template
    id: mailbox_sensor
    name: "Postkasse"
    device_class: opening
    publish_initial_state: true
    lambda: |-
      if (id(mailbox_switch).state) {
        return true;
      } else {
        return false;
      }

switch:
  - platform: template
    id: mailbox_switch
    name: "Mailbox switch"
    optimistic: true
    turn_on_action:
      - binary_sensor.template.publish:
          id: mailbox_sensor
          state: ON
    turn_off_action:
      - binary_sensor.template.publish:
          id: mailbox_sensor
          state: OFF