packages:
  # --- COMMON PACKAGES ---
  <<: !include_dir_named common
  <<: !include_dir_named bluetooth

  # --- BOARD AND MODULES ---
  board: !include board/sunton-8048s043c.yaml

  # --- GUI PACKAGES ---
  colors: !include gui/themes/colors_night_owl.yaml
  lvgl: !include gui/480x800.yaml

  # --- LVGL WIDGET PACKAGES ---
  room_temperature_widget_sensors: !include { file: gui/widgets/labels/number_sensor.yaml, vars: {
    uid: room_temp_value,
    entity_id: sensor.etg2_simen_temperature
  }}

substitutions:
  common:
    log_level: INFO
#    log_baud_rate: "115200"
  device:
    name: s8048s043c-89f954
    framework:
      type: esp-idf
  display:
    home_page: page_analog_clock

esphome:
  comment: 'Sunton 4.3"'
  name: ${device.name}
  friendly_name: ${device.name}
  project:
    version: "1.0.0"

# --- LVGL CLOCKS ---
time:
  - id: !extend time_homeassistant
    on_time_sync:
      - script.execute: lvgl_time_update
    on_time:
      - minutes: '*'
        seconds: 0
        then:
          - script.execute: lvgl_time_update

light:
  - id: !extend backlight_light
    on_state:
      - lvgl.slider.update:
          id: backlight_slider
          value: !lambda return (int(id(backlight_light).remote_values.get_brightness() * 100));
      - lvgl.label.update:
          id: backlight_label
          text:
            format: "%d %%"
            args: [ '(int(id(backlight_light).remote_values.get_brightness() * 100))' ]

lvgl:
  pages:
    - id: page_screen
      pad_top: 44
      pad_bottom: 44
      on_load:
        - lvgl.label.update:
            id: lbl_page_title
            text: Skjerm
      <<: !include
        file: gui/functions/swipe_navigation.yaml
      widgets:
        - obj:
            pad_all: 8
            align: CENTER
            height: 100%
            width: 100%
            widgets:
              - button:
                  id: backlight_button
                  align: top_left
                  checkable: true
                  widgets:
                    - label:
                        align: center
                        text: Backlight
                  on_click:
                    then:
                      - light.control:
                          id: backlight_light
                          state: on
                          brightness: 10%
              - label:
                  id: backlight_label
                  align: bottom_left
                  text: "?"
              - slider:
                  id: backlight_slider
                  align: right_mid
                  x: -5
                  height: 80%
                  width: 30
                  on_release:
                    then:
                      - light.control:
                          id: backlight_light
                          state: on
                          brightness: !lambda return int(x);

binary_sensor:
  # Call sensors from HA.
  - platform: homeassistant
    entity_id: binary_sensor.etg2_simen_occupancy
    id: motion_simen
  - platform: homeassistant
    entity_id: binary_sensor.etg2_gang_occupancy
    id: motion_gang
  # Turn on display while room is occupied
  - platform: template
    id: motion_detected
    lambda: !lambda |-
      if ( (id(motion_simen).state) or (id(motion_gang).state) ) {
        return true;
      } else {
        return false;
      }
    on_state: 
      then:
        - script.execute: display_on_off