packages:
  # --- COMMON PACKAGES ---
  <<: !include_dir_named common
  #  <<: !include_dir_named bluetooth

  # --- BOARD AND MODULES ---
  virtual_esp: !include board/sdl.yaml

  # --- GUI PACKAGES ---
  colors: !include gui/themes/colors_night_owl.yaml
  lvgl: !include gui/480x320.yaml

  # --- LVGL WIDGET PACKAGES ---
  room_temperature_widget_sensors:
    !include {
      file: gui/widgets/labels/number_sensor.yaml,
      vars: { uid: room_temp_value, entity_id: sensor.t22_temperature },
    }

substitutions:
  devicename: sdl-virtual-device
  log_level: INFO
  home_page: page_temperature

esphome:
  comment: "Virtual ESPHome 480x320"
  name: $devicename
  friendly_name: $devicename

display:
  - id: !extend display_sdl
    dimensions:
      height: 480
      width: 320

# --- LVGL CLOCKS ---
time:
  - id: !extend time_homeassistant
    on_time_sync:
      - script.execute: lvgl_time_update
    on_time:
      - minutes: "*"
        seconds: 0
        then:
          - script.execute: lvgl_time_update
  - id: !remove time_sntp

script:
  - id: !remove display_on_off
