packages:
  # --- COMMON PACKAGES ---
  <<: !include_dir_named common
  #  <<: !include_dir_named bluetooth

  # --- BOARD AND MODULES ---

  # --- GUI PACKAGES ---
  colors: !include gui/themes/colors_night_owl.yaml
  lvgl: !include gui/200x200.yaml

  # --- LVGL WIDGET PACKAGES ---
  room_temperature_widget_sensors:
    !include {
      file: gui/widgets/labels/number_sensor.yaml,
      vars: { uid: room_temp_value, entity_id: sensor.t22_temperature },
    }

substitutions:
  devicename: sdl-200x200
  log_level: INFO
  home_page: page_temperature

host:

esphome:
  comment: "Virtual ESPHome 200x200"
  name: $devicename
  friendly_name: $devicename

display:
  - platform: sdl
    #show_test_card: true
    dimensions:
      width: 200
      height: 200
    auto_clear_enabled: false

touchscreen:
  platform: sdl

# --- LVGL CLOCKS ---
time:
  - id: !extend time_homeassistant
    on_time_sync:
      - script.execute: lvgl_time_update
    on_time:
      - minutes: "*"
        seconds: 0
        then:
          - script.execute: lvgl_time_update

binary_sensor:
  # Keep display on
  - platform: template
    id: motion_detected
    lambda: !lambda |-
      return true;
    on_state:
      then:
        - script.execute: display_on_off

script:
  - id: !remove display_on_off
