packages:
  # --- COMMON PACKAGES ---
  <<: !include_dir_named common

  # --- BOARD AND MODULES ---
  board: !include board/seeed_xiao_esp32s3_plus.yaml
  e1002: !include board/module/display_reterminal_e1002.yaml

substitutions:
  common:
    log_level: DEBUG
#    log_baud_rate: "115200"
  device:
    name: seeed-trmnl-e1002-ec2478
    location: "Storage"
    framework:
      type: esp-idf
  display:
    home_page: page_info
    font:
      text_sm: 18
      text_md: 22
      text_lg: 26
      text_xl: 30
      text_xxl: 36
      text_hg: 44
      text_fl: 54
      icons_sm: 28
      icons_md: 40
      icons_lg: 50
      icons_xl: 64
      icons_xxl: 90

esphome:
  comment: ${device.model} @ ${device.location}
  name: ${device.name}
  friendly_name: ${device.name}
  area: ${device.location}

wifi:
  use_address: ${device.name}.local
  manual_ip: 
    gateway: 192.168.68.1
    subnet: 255.255.252.0
    static_ip: 192.168.71.37

display:
  - id: !extend display_eink
    pages:
      - id: page_image
        lambda: |-
          it.image(0, 0, id(i_selma));
      - id: page_info
        lambda: |-
          // Fill background.
          it.fill( id(epaper_bg_color) );

          // NAV
          it.image( (it.get_width()/14)*2 , 0, id(i_home), ImageAlign::TOP_CENTER, id(epaper_text_color), id(epaper_bg_color) );
          it.image( (it.get_width()/14)*4 , 0, id(i_refresh), ImageAlign::TOP_CENTER, id(epaper_text_color), id(epaper_bg_color) );
          it.image( (it.get_width()/14)*6 , 0, id(i_next), ImageAlign::TOP_CENTER, id(epaper_text_color), id(epaper_bg_color) );
          // PAGE
          it.image( 0, 0, id(i_info), ImageAlign::TOP_LEFT, id(epaper_accent1_color), id(epaper_bg_color) );
          it.print(30, 0, id(font_md), id(epaper_accent1_color), TextAlign::TOP_LEFT, "Info");
          
          // BATTERY
          it.print( 0, 57, id(font_md), id(epaper_text_color), TextAlign::BOTTOM_LEFT, "Batteri: " );
          it.printf( it.get_width() - 15, 55, id(font_lg), id(epaper_text_color), TextAlign::BOTTOM_RIGHT, "%.2f", id(battery_voltage).state );
          it.print( it.get_width(), 57, id(font_md), id(epaper_text_color), TextAlign::BOTTOM_RIGHT, "V" );

          // DEVICE
          //it.print( it.get_width()/2, 70, id(font_md), id(epaper_text_color), TextAlign::BOTTOM_CENTER, "ESPHome" );
          // NAME
          it.printf( it.get_width()/2, 87, id(font_md), id(epaper_text_color), TextAlign::BOTTOM_CENTER, "%s", App.get_name().c_str() );

          // NETWORK
          //it.print( it.get_width()/2, 110, id(font_lg), id(epaper_text_color), TextAlign::BOTTOM_CENTER, "Nettverk" );
          // SSID
          it.printf( it.get_width()/2, 117, id(font_md), id(epaper_text_color), TextAlign::BOTTOM_CENTER, "%s", id(sensor_ssid).state.c_str() );
          // IP
          it.printf( it.get_width()/2, 143, id(font_md), id(epaper_text_color), TextAlign::BOTTOM_CENTER, "%s", id(sensor_ip_address).state.c_str() );
          // MAC
          it.printf( it.get_width()/2, 169, id(font_md), id(epaper_text_color), TextAlign::BOTTOM_CENTER, "%s", id(sensor_mac_address).state.c_str() );

          // Show wifi icon.
          if ( id(component_wifi).is_connected() ) {
            it.image( 0, it.get_height(), id(i_wifi), ImageAlign::BOTTOM_LEFT, id(epaper_accent2_color), id(epaper_bg_color) );
          }
          // Show HA icon.
          if ( id(component_api).is_connected() ) {
            it.image( it.get_width(), it.get_height(), id(i_api), ImageAlign::BOTTOM_RIGHT, id(epaper_accent2_color), id(epaper_bg_color) );
          }

          // Refresh Timestamp
          // Code by EnsconcE from https://community.home-assistant.io/t/esphome-show-time/348903
          char str[17];
          time_t currTime = id(time_rtc).now().timestamp;
          strftime( str, sizeof(str), "%H:%M", localtime(&currTime) );
          it.printf( it.get_width()/2, it.get_height(), id(font_sm), id(epaper_text_color), TextAlign::BOTTOM_CENTER, "@ %s", str );
    
# Check if person is home
binary_sensor:
  - platform: homeassistant
    entity_id: binary_sensor.etg2_occupancy
    id: presence_detected

  # Home
  - id: !extend button_green
    on_press:
      - display.page.show: ${display.home_page}
      - script.execute: update_screen
  # Stick Press
  - id: !extend button_left
    on_press:
      - display.page.show_previous: display_eink
      - script.execute: update_screen
  # Stick Down
  - id: !extend button_right
    on_press:
      - display.page.show_next: display_eink
      - script.execute: update_screen

image:
  - platform: file
    id: i_wifi
    file: mdi:wifi
    type: binary
    resize: 28x28
  - platform: file
    id: i_api
    file: mdi:home-assistant
    type: binary
    resize: 28x28

  - platform: file
    id: i_refresh
    file: mdi:refresh
    type: binary
    resize: 28x28
  - platform: file
    id: i_next
    file: mdi:arrow-right-thick
    type: binary
    resize: 28x28
  - platform: file
    id: i_home
    file: mdi:home
    type: binary
    resize: 28x28

  - platform: file
    id: i_info
    file: mdi:information
    type: binary
    resize: 28x28

  - platform: file
    id: i_temp
    file: mdi:thermometer
    type: binary
    resize: 28x28

  - platform: file
    id: i_selma
    file: gui/img/selma_480x800.jpg
    type: RGB
