# Board: Seeed Studio XIAO ESP32S3 Plus
# Definition: definitions/boards/seeed_xiao_esp32_s3_plus/manifest.yaml

esphome:
  name: seeed-trmnl-e1002
  friendly_name: seeed-trmnl-e1002

esp32:
  variant: esp32s3

logger:

api:
  encryption:
    key: "x4YppBI6PIymwxvlYRSe1CirQmbx8v6p9QT7juDrV0c="

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: seeed-trmnl-e10 Fallback Hotspot
    password: "HHvtz8KoPjNm"

captive_portal:
