# https://blakadder.com/esphome-pixel-clock/
# https://github.com/lubeda/EspHoMaTriXv2/
# https://developer.lametric.com/icons

packages:
  # --- COMMON PACKAGES ---
  <<: !include_dir_named common

  # --- BOARD AND MODULES ---
  board: !include board/ulanzi_tc001.yaml

substitutions:
  common:
    log_level: WARN
#    log_baud_rate: "115200"
  device:
    name: ulanzi
    location: "TV Stue"
    framework:
      type: esp-idf

esphome:
  comment: ${device.model} @ ${device.location}
  name: ${device.name}
  friendly_name: ${device.name}
  area: ${device.location}
  project:
    version: "2.0.0"

wifi:
#  use_address: 192.168.69.76
  use_address: ${device.name}.local
  manual_ip: 
    gateway: 192.168.68.1
    subnet: 255.255.252.0
    static_ip: 192.168.71.30

ehmtxv2:
  id: rgb8x32
  icons: 
    - id: error
      lameid: 33180
    - id: lightbulb
      lameid: 52116
    - id: music
      lameid: 22046
    - id: phone
      lameid: 43641
    - id: car
      lameid: 2819
    - id: cat
      lameid: 12200
    - id: sleeping
      lameid: 4412
    - id: ha
      lameid: 7956
    - id: temp
      lameid: 12144
    - id: plug
      lameid: 48588
    - id: humidity
      lameid: 51764
    - id: electricity
      lameid: 54077
    - id: energyprice
      lameid: 54231
    - id: codered
      lameid: 4643
    - id: codeyellow
      lameid: 4642
    - id: codegreen
      lameid: 4641
    - id: doorbell
      lameid: 24800
    - id: cctv
      lameid: 15642
    - id: person
      lameid: 40354
    - id: mail
      lameid: 55030
    - id: folloren1
      lameid: 35037
    - id: folloren2
      lameid: 35034
    - id: arrow_up
      lameid: 20065
    - id: arrow_down
      lameid: 20066
    - id: vol_up
      lameid: 56194
    - id: vol_down
      lameid: 56195
    - id: vol_mute
      lameid: 56242
  on_next_screen:
    - homeassistant.event:
        event: esphome.new_screen
        data_template:
          iconname: !lambda "return icon.c_str();"
          text: !lambda "return text.c_str();"

binary_sensor:
  - platform: homeassistant
    id: powernode_mute
    entity_id: media_player.powernode_stue
    attribute: is_volume_muted
    on_state:
      then:
        - if:
            condition:
              - binary_sensor.is_off: powernode_mute
            then:
              lambda: |-
                ESP_LOGD("ehmtx", "PowerNode unmuted");
                id(rgb8x32)->icon_screen("vol_mute", "Lyd", 0, 2, true, 40,240,40);
                id(rgb8x32)->force_screen("vol_mute");
        - if:
            condition:
              - binary_sensor.is_on: powernode_mute
            then:
              lambda: |-
                ESP_LOGD("ehmtx", "PowerNode muted");
                id(rgb8x32)->icon_screen("vol_mute", "Dempet", 0, 2, true, 240,40,40);
                id(rgb8x32)->force_screen("vol_mute");

sensor:
  - platform: homeassistant
    id: powernode_vol
    entity_id: media_player.powernode_stue
    attribute: volume_level
    filters:
      - multiply: 100
      - round: 0
    on_value:
      then:
        lambda: |-
          char text[3];
          sprintf(text,"%2.0f", id(powernode_vol).state);
          ESP_LOGD("ehmtx", "PowerNode volume changed");
          id(rgb8x32)->icon_screen("vol_up", text, 0, 1, true, 240,240,240);
          id(rgb8x32)->force_screen("vol_up");

text_sensor:
  - platform: homeassistant
    id: powernode_source
    entity_id: media_player.powernode_stue
    attribute: source
    on_value:
      then:
        - if:
            condition:
              text_sensor.state:
                id: powernode_source
                state: 'Samsung TV'
            then:
              lambda: |-
                ESP_LOGD("ehmtx", "PowerNode source TV");
                id(rgb8x32)->icon_screen("arrow_up", "TV", 0, 2, true, 40,240,240);
                id(rgb8x32)->force_screen("arrow_up");
        - if:
            condition:
              text_sensor.state:
                id: powernode_source
                state: 'Denon DP400'
            then:
              lambda: |-
                ESP_LOGD("ehmtx", "PowerNode source Line-in");
                id(rgb8x32)->icon_screen("arrow_down", "Platespiller", 0, 2, true, 240,240,40);
                id(rgb8x32)->force_screen("arrow_down");
        - if:
            condition:
              not:
                or:
                  - text_sensor.state:
                      id: powernode_source
                      state: 'Denon DP400'
                  - text_sensor.state:
                      id: powernode_source
                      state: 'Samsung TV'
            then:
              lambda: |-
                ESP_LOGD("ehmtx", "PowerNode source Other");
                id(rgb8x32)->icon_screen("vol_mute", "Source ?", 0, 2, true, 240,40,240);
                id(rgb8x32)->force_screen("vol_mute");
