# https://blakadder.com/esphome-pixel-clock/
# https://github.com/lubeda/EspHoMaTriXv2/
# https://developer.lametric.com/icons

packages:
  # --- COMMON PACKAGES ---
  <<: !include_dir_named common

  # --- BOARD AND MODULES ---
  board: !include board/ulanzi_tc001.yaml

substitutions:
  devicename: ulanzi
  location: "1etg, TV Stue"
  log_level: WARN

esphome:
  comment: "Ulanzi TC001 Pixel Clock @ Stue"
  name: ${devicename}
  friendly_name: ${devicename}
  area: ${location}
  project:
    version: "2.0.0"

ehmtxv2:
  id: rgb8x32
  icons2html: true
  time_component: ehmtx_time
  time_format: "%H:%M"    # defaults "%H:%M" (use "%I:%M%p" for the US)
  date_format: "%d.%m"    # defaults "%d.%m." (use "%m.%d." for the US)
  show_seconds: false
  week_start_monday: true # default monday is first day of week, false = sunday
#  show_dow: true         # draw the day indicator on the bottom of the screen, defaults to true
#  show_date: true         # show the date for show_screen - show_clock seconds otherwise only shows the clock for show_screen seconds, defaults to true
  matrix_component: ehmtx_display
  clock_interval: 60      # show the clock at least each x seconds
  default_font_id: default_font
  default_font_yoffset: 8              # the text is aligned BASELINE_LEFT, the baseline defaults to 6
  special_font_id: special_font
  special_font_yoffset: 6              # the text is aligned BASELINE_LEFT, the baseline defaults to 6
  scroll_interval: 96    # the interval in ms to scroll the text (default=80), should be a multiple of the update_interval from the display (default: 16ms)
  frame_interval: 192     # the interval in ms to display the next anim frame (default=192), should be a multiple of the update_interval from the display (default: 16ms)
  boot_logo: "[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,63519,63519,63519,63519,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,63519,0,0,0,0,2016,0,0,0,0,0,0,0,0,0,0,31,0,0,0,0,0,0,0,0,0,63488,0,63488,0,0,0,63519,0,0,0,0,2016,2016,0,0,0,65514,0,65514,0,0,0,31,0,0,0,64512,0,0,64512,0,63488,63488,0,63488,63488,0,0,63519,63519,63519,0,0,2016,0,2016,0,65514,0,65514,0,65514,0,31,31,31,0,0,0,64512,64512,0,0,63488,63488,63488,63488,63488,0,0,63519,0,0,0,0,2016,0,2016,0,65514,0,65514,0,65514,0,0,31,0,0,0,0,64512,64512,0,0,0,63488,63488,63488,0,0,0,63519,63519,63519,63519,0,2016,0,2016,0,65514,0,65514,0,65514,0,0,0,31,31,0,64512,0,0,64512,0,0,0,63488,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]"
  icons: 
    - id: error
      lameid: 33180
    - id: lightbulb
      lameid: 52116
    - id: music
      lameid: 22046
    - id: phone
      lameid: 43641
    - id: car
      lameid: 2819
    - id: cat
      lameid: 12200
    - id: sleeping
      lameid: 4412
    - id: ha
      lameid: 7956
    - id: temp
      lameid: 12144
    - id: plug
      lameid: 48588
    - id: humidity
      lameid: 51764
    - id: electricity
      lameid: 54077
    - id: energyprice
      lameid: 54231
    - id: codered
      lameid: 4643
    - id: codeyellow
      lameid: 4642
    - id: codegreen
      lameid: 4641
    - id: doorbell
      lameid: 24800
    - id: cctv
      lameid: 15642
    - id: person
      lameid: 40354
    - id: mail
      lameid: 55030
    - id: folloren1
      lameid: 35037
    - id: folloren2
      lameid: 35034
    - id: arrow_up
      lameid: 20065
    - id: arrow_down
      lameid: 20066
    - id: vol_up
      lameid: 56194
    - id: vol_down
      lameid: 56195
    - id: vol_mute
      lameid: 56242
  on_start_running:
    then:
      lambda: |-
        ESP_LOGD(TAG, "remove default clock and set new color");
        id(rgb8x32)->set_clock_color(160,240,160);
        id(rgb8x32)->set_weekday_color(155,155,155);
        id(rgb8x32)->set_today_color(240,160,160);
  on_next_screen:
    - homeassistant.event:
        event: esphome.new_screen
        data_template:
          iconname: !lambda "return icon.c_str();"
          text: !lambda "return text.c_str();"

binary_sensor:
  - platform: homeassistant
    id: sonos_amp_mute
    entity_id: media_player.sonos_amp
    attribute: is_volume_muted
    on_state:
      then:
        - if:
            condition:
              - binary_sensor.is_off: sonos_amp_mute
            then:
              lambda: |-
                ESP_LOGD(TAG, "Sonos Amp unmuted");
                id(rgb8x32)->icon_screen("vol_mute", "Lyd", 0, 2, true, 40,240,40);
                id(rgb8x32)->force_screen("vol_mute");
        - if:
            condition:
              - binary_sensor.is_on: sonos_amp_mute
            then:
              lambda: |-
                ESP_LOGD(TAG, "Sonos Amp muted");
                id(rgb8x32)->icon_screen("vol_mute", "Dempet", 0, 2, true, 240,40,40);
                id(rgb8x32)->force_screen("vol_mute");

sensor:
  - platform: homeassistant
    id: sonos_amp_vol
    entity_id: media_player.sonos_amp
    attribute: volume_level
    filters:
      - multiply: 100
      - round: 0
    on_value:
      then:
        lambda: |-
          char text[3];
          sprintf(text,"%2.0f", id(sonos_amp_vol).state);
          ESP_LOGD(TAG, "Sonos Amp volume changed");
          id(rgb8x32)->icon_screen("vol_up", text, 0, 1, true, 240,240,240);
          id(rgb8x32)->force_screen("vol_up");

text_sensor:
  - platform: homeassistant
    id: sonos_amp_source
    entity_id: media_player.sonos_amp
    attribute: source
    on_value:
      then:
        - if:
            condition:
              text_sensor.state:
                id: sonos_amp_source
                state: 'TV'
            then:
              lambda: |-
                ESP_LOGD(TAG, "Sonos Amp source TV");
                id(rgb8x32)->icon_screen("arrow_up", "TV", 0, 2, true, 40,240,240);
                id(rgb8x32)->force_screen("arrow_up");
        - if:
            condition:
              text_sensor.state:
                id: sonos_amp_source
                state: 'Line-in'
            then:
              lambda: |-
                ESP_LOGD(TAG, "Sonos Amp source Line-in");
                id(rgb8x32)->icon_screen("arrow_down", "Platespiller", 0, 2, true, 240,240,40);
                id(rgb8x32)->force_screen("arrow_down");
        - if:
            condition:
              not:
                or:
                  - text_sensor.state:
                      id: sonos_amp_source
                      state: 'Line-in'
                  - text_sensor.state:
                      id: sonos_amp_source
                      state: 'TV'
            then:
              lambda: |-
                ESP_LOGD(TAG, "Sonos Amp source Other");
                id(rgb8x32)->icon_screen("vol_mute", "Source ?", 0, 2, true, 240,40,240);
                id(rgb8x32)->force_screen("vol_mute");

font: 
  # adapt the filename to your local settings
  - file: gui/fonts/MatrixClock-Light8.bdf
    id: default_font
    size: 8
    glyphs: &norwegian_glyphs [ '!', ' ', '"', '#', '$', '%', '&', "'", '(', ')', '*', ',', '.', '/', '[', '\', ']', '^', '`',
      '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '+', '-', ':', ';', '<', '=', '>', '?', '@', '_', '°',
      'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N',
      'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'Æ', 'Ø', 'Å',
      'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n',
      'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'æ', 'ø', 'å' ]
  - file: gui/fonts/MatrixClock-Chunky6.bdf
    id: special_font
    size: 6
    glyphs: &clock_glyphs [ '!', ' ', '"', '#', '$', '%', '&', "'", '(', ')', '*', '+', ',', '-', '.', '/',
      '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', 'A', 'P', 'M', 'T', 'a', 'p', 'm', 't' ]
