packages:
  <<: !include_dir_named common
  <<: !include_dir_named bluetooth

substitutions:
  devicename: vvb-temp-v2
  location: "1etg, Bad"

#external_components:
#  - source: github://nrandell/dallasng

esphome:
  comment: "VVB Temp V2"
  name: $devicename
  friendly_name: $devicename
  area: $location

esp32:
  board: esp32doit-devkit-v1
  framework: 
    type: esp-idf

#i2c:
#  scl: GPIO22
#  sda: GPIO21
#  scan: true
#  frequency: 100kHz
#  timeout: 11ms
#  id: bus_a

one_wire:
  - platform: gpio
    pin: GPIO4
    id: bus_b

#dallasng:
#  - pin: GPIO4
#    id: bus_b

sensor:
  - platform: dallas_temp
#  - platform: dallasng
    address: 0x1707235305e77e28
    name: "Topp Temperature"
    device_class: "temperature"
    id: dallas_topp
#    filters:
#      - or:
#        - heartbeat: 900s
#        - delta: 0.15
  - platform: dallas_temp
#  - platform: dallasng
    address: 0x7ef0d9451f64ff28
    name: "Bunn Temperature"
    device_class: "temperature"
    id: dallas_bunn
#    filters:
#      - or:
#        - heartbeat: 900s
#        - delta: 0.15
  - platform: combination
    type: median
    name: "Mix Temperature"
    device_class: "temperature"
    sources:
      - source: dallas_topp
      - source: dallas_bunn
#    filters:
#      - or:
#        - heartbeat: 900s
#        - delta: 0.15

#  - platform: bme280_i2c
#    i2c_id: bus_a
#    setup_priority: -100
#    address: 0x76
#    update_interval: 60s
#    temperature:
#      id: bme_temperature
#      oversampling: 4x
#      name: "Temperature"
#      filters:
#        - or:
#          - heartbeat: 900s
#          - delta: 0.15
#    pressure:
#      id: bme_pressure
#      oversampling: 4x
#      name: "Pressure"
#    humidity:
#      id: bme_humidity
#      oversampling: 4x
#      name: "Humidity"
#      filters:
#        - or:
#          - heartbeat: 900s
#          - delta: 0.15
