packages:
  # --- COMMON PACKAGES ---
  <<: !include_dir_named common

  # --- BOARD AND MODULES ---
  board: !include board/waveshare_esp32s3_touch_2in_cam.yaml

  # --- GUI PACKAGES ---
  colors: !include gui/themes/colors_night_owl.yaml
  lvgl: !include gui/320x240.yaml

  # --- LVGL WIDGET PACKAGES ---
  room_temperature_widget_sensors: !include { file: gui/widgets/labels/number_sensor.yaml, vars: {
    uid: room_temp_value,
    entity_id: sensor.etg2_stue_temperature
  }}

substitutions:
  common:
    log_level: DEBUG
#    log_baud_rate: "115200"
  device:
    name: waveshare-touch-2in-cam-47aaa0
    location: "Storage"
    framework:
      type: esp-idf
  display:
    home_page: page_temperature

esphome:
  comment: ${device.model} @ ${device.location}
  name: ${device.name}
  friendly_name: ${device.name}
  area: ${device.location}

wifi:
  use_address: ${device.name}.local
  manual_ip: 
    gateway: 192.168.68.1
    subnet: 255.255.252.0
    static_ip: 192.168.71.37

lvgl:
  buffer_size: 40%
  style_definitions:
    - id: circle
      radius: circle
      outline_width: 1
      outline_color: c_yellow
      align: center
    - id: dashline
      width: 100%
      height: 100%
      line_dash_width: 4
      line_dash_gap: 4
      line_color: c_yellow
  pages:
    - id: page_imu
      pad_top: 32
      pad_bottom: 32
      on_load:
        - lvgl.label.update:
            id: lbl_page_title
            text: IMU
      <<: !include
        file: gui/functions/swipe_navigation.yaml
      widgets:
        - obj:
            pad_top: 2
            pad_bottom: 2
            pad_left: 2
            pad_right: 2
            scrollable: false
            width: 100%
            height: 100%
            border_width: 0
            radius: 0
            align: CENTER
            widgets:
              - container:
                  max_height: 66
                  max_width: 66
                  styles: circle
                  bg_color: c_bg_s
                  bg_opa: cover
                  widgets:
                  - container:
                      styles: circle
                      width: 66%
                      height: 66%
                  - container:
                      styles: circle
                      width: 33%
                      height: 33%
                  - line:
                      styles: dashline
                      points:
                        - 50%,0
                        - 50%,100%
                  - line:
                      styles: dashline
                      points:
                        - {x: 0, y: 50%}
                        - [100%, 50%]
                  - container:
                      styles: circle
                      width: 10%
                      height: 10%
                      bg_color: c_gray
                      bg_opa: 50%
                  - container:
                      id: indicator_container
                      width: 100%
                      height: 100%
                      transform_pivot_x: 50%
                      transform_pivot_y: 50%
                      widgets:
                        - container:
                            id: indicator
                            styles: circle
                            width: 12%
                            height: 12%
                            bg_color: c_red
                            bg_opa: 100%
                            x: 10
                            y: 10
              - label:
                  text: R
                  align: bottom_mid
                  text_font: font_sm
                  text_color: c_dark_gray
              - label:
                  text: F
                  align: top_mid
                  text_font: font_sm
                  text_color: c_dark_gray
              - label:
                  text: L
                  align: left_mid
                  text_font: font_md
                  text_color: c_dark_gray
              - label:
                  text: R
                  align: right_mid
                  text_font: font_md
                  text_color: c_dark_gray

binary_sensor:
  # Call sensors from HA.
  - platform: homeassistant
    entity_id: binary_sensor.etg2_stue_occupancy
    id: presence1
  - platform: homeassistant
    entity_id: binary_sensor.etg2_gang_occupancy
    id: presence2
  # Turn on display while room is occupied
  - id: !extend presence_detected
    lambda: !lambda |-
      if ( (id(presence1).state) or (id(presence2).state) ) {
        return true;
      } else {
        return false;
      }

script:
  - id: update_motion
    then:
    - if:
        condition:
          lambda: return abs(id(motion_roll).state) < 1.0f && abs(id(motion_pitch).state) < 1.0f;
        then:
          lvgl.widget.update:
            id: indicator
            bg_color: c_green
            x: !lambda return (int)(clamp(id(motion_roll).state, -20.0f, 20.0f) / 20.0f * 35);
            y: !lambda return (int)(clamp(id(motion_pitch).state, -20.0f, 20.0f) / 20.0f * 35);
        else:
          lvgl.widget.update:
            id: indicator
            bg_color: c_red
            x: !lambda return (int)(clamp(id(motion_roll).state, -20.0f, 20.0f) / 20.0f * 35);
            y: !lambda return (int)(clamp(id(motion_pitch).state, -20.0f, 20.0f) / 20.0f * 35);

sensor:
  - id: !extend motion_roll
    on_value:
      script.execute: update_motion
