# Board: Waveshare ESP32-P4-WIFI6 (Waveshare)
# Definition: definitions/boards/waveshare_esp32_p4_wifi6/manifest.yaml

esphome:
  name: waveshare-p4-wifi6-xx
  friendly_name: waveshare-p4-wifi6-xx

esp32:
  variant: esp32p4
  engineering_sample: true
  flash_size: 32MB
  framework:
    type: esp-idf
    advanced:
      enable_idf_experimental_features: true

logger:
  hardware_uart: UART0

api:
  encryption:
    key: "H4UnmlDiBfjVI07+kMCQ4/Xuy8qhj6PG++AWuaLgphw="

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: waveshare-p4-wi Fallback Hotspot
    password: "onFpdfV6UDJF"

captive_portal:

esp32_hosted:
  active_high: true
  clk_pin: GPIO18
  cmd_pin: GPIO19
  d0_pin: GPIO14
  d1_pin: GPIO15
  d2_pin: GPIO16
  d3_pin: GPIO17
  reset_pin: GPIO54
  type: sdio
  variant: ESP32C6

http_request:

update:
  - platform: esp32_hosted
    type: http
    source: https://esphome.github.io/esp-hosted-firmware/manifest/esp32c6.json
    name: C6 Firmware
