---
# https://docs.m5stack.com/en/base/btc_base
# https://esphome.io/components/sensor/sht3xd.html

substitutions:
  base_btc_i2c_bus: i2c_grove

# SHT30
sensor:
  - platform: sht3xd
    i2c_id: $base_btc_i2c_bus
    id: base_btc_sht30_sensor
    temperature:
      id: temperature_sht30_base_btc
      name: "SHT30 Base BTC Temperature"
      disabled_by_default: true
      device_class: "temperature"
      state_class: "measurement"
    humidity:
      id: humidity_sht30_base_btc
      name: "SHT30 Base BTC Humidity"
      disabled_by_default: true
      device_class: "humidity"
      state_class: "measurement"
    address: 0x44
    update_interval: 20s
