---
# https://docs.m5stack.com/en/base/btc_base
# https://esphome.io/components/sensor/sht3xd.html

substitutions:
  base_btc_i2c_bus: i2c_mbus

# SHT30
sensor:
  - platform: sht3xd
    i2c_id: ${base_btc_i2c_bus}
    id: base_btc_sht30_sensor
    temperature:
      id: temperature_sht30_base_btc
      name: "SHT30 Base BTC Temperature"
      disabled_by_default: true
      device_class: "temperature"
      state_class: "measurement"
      filters:
        - sliding_window_moving_average:
            window_size: 6
            send_every: 3
    humidity:
      id: humidity_sht30_base_btc
      name: "SHT30 Base BTC Humidity"
      disabled_by_default: true
      device_class: "humidity"
      state_class: "measurement"
      filters:
        - sliding_window_moving_average:
            window_size: 6
            send_every: 3
    address: 0x44
    update_interval: 10s
