---
# https://esphome.io/components/sensor/mpu6886.html

substitutions:
  gyro_i2c_bus: i2c_internal


  # Built-in 6-axis (IMU) that also includes a temperature sensor
sensor:
  - platform: mpu6886
    i2c_id: $gyro_i2c_bus
    address: 0x68
    update_interval: 1s
    accel_x:
      id: mpu6886_accel_x
      name: "Accel X"
      disabled_by_default: true
      filters:
        - sliding_window_moving_average:
            window_size: 5
            send_every: 5
    accel_y:
      id: mpu6886_accel_y
      name: "Accel Y"
      disabled_by_default: true
      filters:
        - sliding_window_moving_average:
            window_size: 5
            send_every: 5
    accel_z:
      id: mpu6886_accel_z
      name: "Accel Z"
      disabled_by_default: true
      filters:
        - sliding_window_moving_average:
            window_size: 5
            send_every: 5
    gyro_x:
      id: mpu6886_gyro_x
      name: "Gyro X"
      disabled_by_default: true
      filters:
        - sliding_window_moving_average:
            window_size: 5
            send_every: 5
    gyro_y:
      id: mpu6886_gyro_y
      name: "Gyro Y"
      disabled_by_default: true
      filters:
        - sliding_window_moving_average:
            window_size: 5
            send_every: 5
    gyro_z:
      id: mpu6886_gyro_z
      name: "Gyro Z"
      disabled_by_default: true
      filters:
        - sliding_window_moving_average:
            window_size: 5
            send_every: 5
    temperature:
      id: temperature_mpu6886
      name: "Temperature MPU6886"
      disabled_by_default: true
      filters:
        - sliding_window_moving_average:
            window_size: 60
            send_every: 30
