---
# https://docs.m5stack.com/en/hat/hat_envIII
# https://esphome.io/components/sensor/sht3xd.html
# https://esphome.io/components/sensor/qmp6988.html

#ENV.III
sensor:
  - platform: sht3xd
    i2c_id: i2c_hat
    id: hat_env_sht30_sensor
    temperature:
      id: temperature_sht30_hat_env
      name: "Hat Env SHT30 Temperature"
      disabled_by_default: true
      device_class: "temperature"
      state_class: "measurement"
    humidity:
      id: humidity_sht30_hat_env
      name: "Hat Env SHT30 Humidity"
      disabled_by_default: true
      device_class: "humidity"
      state_class: "measurement"
    address: 0x44
    update_interval: 10s

  - platform: qmp6988
    i2c_id: i2c_hat
    id: hat_env_qmp6988_sensor
    temperature:
      id: temperature_qmp6988_hat_env
      name: "Hat Env QMP6988 Temperature"
      disabled_by_default: true
      device_class: "temperature"
      state_class: "measurement"
      oversampling: 4x
    pressure:
      id: pressure_qmp6988_hat_env
      name: "Hat Env QMP6988 Pressure"
      disabled_by_default: true
      device_class: "atmospheric_pressure"
      state_class: "measurement"
      oversampling: 4x
    address: 0x70
    update_interval: 10s
    iir_filter: 8x

  # Combination    
#  - platform: combination
#    type: median
#    id: temperature_env_iii
#    name: "Temperature ENV.III"
#    device_class: "temperature"
#    sources:
#      - source: temperature_sht30_hat_env
#      - source: temperature_qmp6988_hat_env
#    filters:
#      - lambda: "return x + id(temperature_offset_env_iii).state;"
#      - or:
#        - heartbeat: 900s
#        - delta: 0.15

# Offsets
#number:
#  - platform: template
#    id: temperature_offset_env_iii
#    name: "Temperature Offset ENV.III"
#    entity_category: config
#    unit_of_measurement: "°C"
#    disabled_by_default: true
#    min_value: -20
#    max_value: 20
#    step: 0.1
#    mode: box
#    update_interval: never
#    optimistic: true
#    restore_value: true
#    initial_value: 0
#    icon: "mdi:thermometer"
#    on_value:
#      - lambda: 'id(hat_env_sht30_sensor).update();'
#      - lambda: 'id(hat_env_qmp6988_sensor).update();'

#  - platform: template
#    id: humidity_offset_env_iii
#    name: "Humidity Offset ENV.III"
#    entity_category: config
#    unit_of_measurement: "%"
#    disabled_by_default: true
#    min_value: -50
#    max_value: 50
#    step: 0.1
#    mode: box
#    update_interval: never
#    optimistic: true
#    restore_value: true
#    initial_value: 0
#    icon: "mdi:water-percent"
#    on_value:
#      - lambda: 'id(hat_env_sht30_sensor).update();'
