---
# https://docs.m5stack.com/en/module/DualKmeter%20Module13.2
# https://github.com/m5stack/esphome-yaml/tree/main/components/dual_kmeter
# https://github.com/Chill-Division/M5Stack-ESPHome/

substitutions:
  module:
    kmeteriso_i2c_bus: i2c_mbus

external_components:
  - source: github://m5stack/esphome-yaml/components
    components: [dual_kmeter]

logger:
  logs:
    sensor.dual_kmeter: DEBUG

# Module13.2 Dual Kmeter
sensor:
  - platform: dual_kmeter
    i2c_id: ${module.kmeteriso_i2c_bus}
    id: dual_kmeter_internal_sensor
    channel: INTERNAL
    update_interval: 60s
    name: "Temperature DualKMeter Internal"
    device_class: "temperature"
    state_class: "measurement"
    disabled_by_default: true
    entity_category: diagnostic
    filters:
      - sliding_window_moving_average:
          window_size: 6
          send_every: 6
    on_value:
      - then:
          - lvgl.label.update:
              id: lbl_temp_kmeteri_value
              text:
                format: "%.1f"
                args: [ 'x' ]
  - platform: dual_kmeter
    i2c_id: ${module.kmeteriso_i2c_bus}
    id: dual_kmeter_1_sensor
    channel: KMETER_1
    update_interval: 45s
    name: "Temperature DualKMeter 1"
    device_class: "temperature"
    state_class: "measurement"
    filters:
      - sliding_window_moving_average:
          window_size: 3
          send_every: 2
    on_value:
      - then:
          - lvgl.label.update:
              id: lbl_temp_kmeter1_value
              text:
                format: "%.1f"
                args: [ 'x' ]
  - platform: dual_kmeter
    i2c_id: ${module.kmeteriso_i2c_bus}
    id: dual_kmeter_2_sensor
    channel: KMETER_2
    update_interval: 45s
    name: "Temperature DualKMeter 2"
    device_class: "temperature"
    state_class: "measurement"
    filters:
      - sliding_window_moving_average:
          window_size: 3
          send_every: 2
    on_value:
      - then:
          - lvgl.label.update:
              id: lbl_temp_kmeter2_value
              text:
                format: "%.1f"
                args: [ 'x' ]

.sizing:
  - &page_styles
    <<: !include ../../gui/styles/page_styles.yaml
    page_pad_top: 32
    page_pad_bottom: 32
    screen_height: 240
    screen_width: 320
    # Calculate the usable height for the page content area
    # (screen_height - (2 * status_bar_height) - (2 * container_pad))
    # 240 - (2 * 32) - (2 * 1) = 170
    usable_screen_height: 170
    # Calculate the usable width for the page content area
    # (screen_width - (2 * container_pad))
    # 320  (2 * 4) = 312
    usable_screen_width: 312

  - &container_styles
    <<: !include ../../gui/styles/container_styles.yaml
    container_pad_top: 1
    container_pad_bottom: 1
    container_pad_left: 4
    container_pad_right: 4
    container_scrollable: false # prevents scrollbars on pages where space is used up to the last

lvgl:
  pages:
    - <<: !include 
        file: ../../gui/pages/dual_kmeter/page.yaml
        vars:
          <<: [*page_styles, *container_styles]
          page_title: Temp Probe
