labels: [CC1101, wmbus, radio, SPI]
---
# https://docs.m5stack.com/en/module/Module_CC1101
# https://esphome.io/components/cc1101/
# https://github.com/SzczepanLeon/esphome-components/
# Does NOT work with CoreS3-SE as SPI MISO pin is shared with Display DC pin
# Does work with Fire 2.7
#
# CC1101 Wireless M-Bus package

substitutions:
  module:
    cc1101:
      frequency: "868.95MHz" # 855 ~ 925MHz supported by this chip
      water_meter_serial: !secret water_meter_serial

# Make water meter always appear as a separate device in the kitchen area
esphome:
  areas:
    - id: area_kitchen
      name: Kjøkken
  # Define devices
  devices:
    - id: sub_device_water_meter
      name: kamstrup_flowiq2200
      area_id: area_kitchen

# Enable logging for this component
logger:
  logs:
    wmbus: DEBUG
    wmbus_radio: DEBUG
    wmbus_common: DEBUG
    wmbus_meter: DEBUG
    sensor.wmbus_meter: DEBUG
    text_sensor.wmbus_meter: DEBUG

# Pull the custom wM-Bus component directly from GitHub
external_components:
  - source: github://SzczepanLeon/esphome-components@main
    components: [ wmbus_radio, wmbus_common, wmbus_meter ]

# Water meter sensors
sensor:
  # Water meter total consumption
  - platform: wmbus_meter
    parent_id: water_meter
    field: total_m3
    id: wmbus_water_total_consumption
    device_id: sub_device_water_meter
    name: "Water Total Consumption"
    unit_of_measurement: "m³"
    device_class: water
    state_class: total_increasing
    accuracy_decimals: 3
    icon: "mdi:water"
    on_value:
      - then:
          - lvgl.label.update:
              id: lbl_water_consumption_value
              text:
                format: "%.3f"
                args: [ 'x' ]

  # Target/Last month reading
  - platform: wmbus_meter
    parent_id: water_meter
    field: target_m3
    id: wmbus_water_target
    device_id: sub_device_water_meter
    name: "Water Target"
    unit_of_measurement: "m³"
    accuracy_decimals: 3
    icon: "mdi:counter"

  # Flow temperature
  - platform: wmbus_meter
    parent_id: water_meter
    field: flow_temperature_c
    id: wmbus_water_flow_temperature
    device_id: sub_device_water_meter
    name: "Water Temperature"
    unit_of_measurement: "°C"
    device_class: temperature
    accuracy_decimals: 1

  # External/Ambient temperature
  - platform: wmbus_meter
    parent_id: water_meter
    field: external_temperature_c
    id: wmbus_water_external_temperature
    device_id: sub_device_water_meter
    name: "Meter Ambient Temperature"
    unit_of_measurement: "°C"
    device_class: temperature
    entity_category: diagnostic
    disabled_by_default: true
    accuracy_decimals: 1

  # RSSI
  - platform: wmbus_meter
    parent_id: water_meter
    field: rssi_dbm
    id: wmbus_water_rssi
    device_id: sub_device_water_meter
    name: "Water Meter RSSI"
    unit_of_measurement: "dBm"
    device_class: signal_strength
    state_class: measurement
    entity_category: diagnostic
    disabled_by_default: true
    accuracy_decimals: 0
    icon: "mdi:signal"
    on_value:
      - then:
          - lvgl.label.update:
              id: lbl_water_meter_rssi_value
              text:
                format: "%.0f"
                args: [ 'x' ]

text_sensor:
  # Alarms
  - platform: wmbus_meter
    parent_id: water_meter
    field: current_alarms
    id: wmbus_water_alarms
    device_id: sub_device_water_meter
    name: "Water Meter Alarms"
    on_value:
      - then:
          - lvgl.label.update:
              id: lbl_water_meter_alarms_value
              text:
                format: "%s"
                args: [ 'x' ]

  # Status
  - platform: wmbus_meter
    parent_id: water_meter
    field: status
    id: wmbus_water_status
    device_id: sub_device_water_meter
    name: "Water Meter Status"
    entity_category: diagnostic
    on_value:
      - then:
          - lvgl.label.update:
              id: lbl_water_meter_status_value
              text:
                format: "%s"
                args: [ 'x' ]

# Same as in ../../gui/240x320.yaml
.sizing:
  - &page_styles
    <<: !include ../../gui/styles/page_styles.yaml
    page_pad_top: 32
    page_pad_bottom: 32
    screen_height: 240
    screen_width: 320
    # Calculate the usable height for the page content area
    # (screen_height - (2 * status_bar_height) - (2 * container_pad))
    # 240 - (2 * 32) - (2 * 1) = 170
    usable_screen_height: 170
    # Calculate the usable width for the page content area
    # (screen_width - (2 * container_pad))
    # 320  (2 * 4) = 312
    usable_screen_width: 312

  - &container_styles
    <<: !include ../../gui/styles/container_styles.yaml
    container_pad_top: 1
    container_pad_bottom: 1
    container_pad_left: 4
    container_pad_right: 4
    container_scrollable: false # prevents scrollbars on pages where space is used up to the last

# include lvgl page for water meter
lvgl:
  pages:
    - <<: !include 
        file: ../../gui/pages/cc1101/wmbus.yaml
        vars:
          <<: [*page_styles, *container_styles]
          page_title: Radio

# CC1101 module hardware settings
# https://github.com/SzczepanLeon/esphome-components/tree/main#radio-configuration
# https://github.com/SzczepanLeon/esphome-components/blob/main/ESP32-C3_SuperMini_CC1101.yaml
wmbus_radio:
  id: radio_cc1101_wmbus
# radio_type: Must be CC1101
  radio_type: CC1101
# cs_pin: SPI chip select pin
  cs_pin: ${pin.ext.mbus.p21}
# irq_pin: Interrupt pin (GDO0)
  irq_pin: ${pin.ext.mbus.p22}
# frequency (Optional): Operating frequency, 300–928 MHz. Defaults to 868.950 MHz
  frequency: ${module.cc1101.frequency}
  on_frame:
    - then:
        - logger.log:
            level: DEBUG
            tag: "wmbus_radio"
            format: "Frame received: RSSI=%ddBm, Mode=%s, Data=%s"
            args: [ 'frame->rssi()', 'toString(frame->link_mode())', 'frame->as_hex().c_str()' ]

# Define drivers/meters to enable
# Uncomment and list only the drivers you need to save flash space
wmbus_common:
  drivers:
#    - auto
    - flowiq2200
#    - multical21

# https://github.com/SzczepanLeon/esphome-components/blob/version_4/docs/wmbus.md
## If You want to send telegram to another machine and decode it via wmbusmeters addon.
# socket_transmitter:
#   id: socket_to_wmbusmeters
#   ip_address: 192.168.68.100 # Home Assistant IP
#   port: 7011
#   protocol: TCP # or UDP

# Define your water meter
wmbus_meter:
  - id: water_meter
    meter_id: 0x${module.cc1101.water_meter_serial}
    type: flowiq2200
    key: !secret water_meter_encryption_key
    mode:
      - C1
    on_telegram:
      - logger.log:
          level: DEBUG
          tag: "wmbus_meter"
          format: "Telegram received from water meter"
