---
# https://docs.m5stack.com/en/module/Module_CC1101
# https://esphome.io/components/cc1101/
# https://github.com/SzczepanLeon/esphome-components/tree/version_4
# Does NOT work with CoreS3-SE as SPI MISO pin is shared with Display DC pin
# Does work with Fire 2.7
#
# WIP
#

substitutions:
  module:
    cc1101:
      frequency: "868.95MHz" # 855 ~ 925MHz supported by this chip

# Pull the custom wM-Bus component directly from GitHub
external_components:
  - source: github://SzczepanLeon/esphome-components@main
    components: [ wmbus_radio, wmbus_common, wmbus_meter ]

logger:
  logs:
    wmbus_radio: DEBUG

# https://github.com/SzczepanLeon/esphome-components/tree/main#radio-configuration
wmbus_radio:
  id: radio_cc1101_wmbus
# radio_type: Must be CC1101
  radio_type: CC1101
# cs_pin: SPI chip select pin
  cs_pin: ${pin.ext.mbus.p21}
# irq_pin: Interrupt pin (GDO0)
  irq_pin: ${pin.ext.mbus.p22}
# frequency (Optional): Operating frequency, 300–928 MHz. Defaults to 868.950 MHz
  frequency: ${module.cc1101.frequency}
  on_frame:
    - then:
        - logger.log:
            format: "Frame received: RSSI=%ddBm, Mode=%s, Data=%s"
            args: [ 'frame->rssi()', 'toString(frame->link_mode())', 'frame->as_hex().c_str()' ]

# Uncomment and list only the drivers you need to save flash space
wmbus_common:
  drivers:
#    - auto
    - flowiq2200
#    - multical21

# Define your water meter
wmbus_meter:
  - id: water_meter
    meter_id: !secret water_meter_serial 53908435
    type: flowiq2200
    key: !secret water_meter_encryption_key
    mode:
      - C1
    on_telegram:
      - logger.log:
          format: "Telegram received from water meter"

# sensor:
  # Water meter total consumption
  # - platform: wmbus_meter
  #   parent_id: water_meter
  #   field: total_m3
  #   id: wmbus_water_total_consumption
  #   name: "Water Total Consumption"
  #   unit_of_measurement: "m³"
  #   device_class: water
  #   state_class: total_increasing
  #   accuracy_decimals: 3
  #   icon: "mdi:water"

  # Target/Last month reading
  # - platform: wmbus_meter
  #   parent_id: water_meter
  #   field: target_m3
  #   id: wmbus_water_target
  #   name: "Water Target"
  #   unit_of_measurement: "m³"
  #   accuracy_decimals: 3
  #   icon: "mdi:counter"

  # Flow temperature
  # - platform: wmbus_meter
  #   parent_id: water_meter
  #   field: flow_temperature_c
  #   id: wmbus_water_flow_temperature
  #   name: "Water Temperature"
  #   unit_of_measurement: "°C"
  #   device_class: temperature
  #   accuracy_decimals: 1

  # External/Ambient temperature
  # - platform: wmbus_meter
  #   parent_id: water_meter
  #   field: external_temperature_c
  #   id: wmbus_water_external_temperature
  #   name: "Meter Ambient Temperature"
  #   unit_of_measurement: "°C"
  #   device_class: temperature
  #   entity_category: diagnostic
  #   accuracy_decimals: 1

  # RSSI
  # - platform: wmbus_meter
  #   parent_id: water_meter
  #   field: rssi_dbm
  #   id: wmbus_water_rssi
  #   name: "Water Meter RSSI"
  #   unit_of_measurement: "dBm"
  #   device_class: signal_strength
  #   state_class: measurement
  #   entity_category: diagnostic
  #   accuracy_decimals: 0
  #   icon: "mdi:signal"

# text_sensor:
#   - platform: wmbus_meter
#     parent_id: water_meter
#     field: current_alarms
#     id: wmbus_water_alarms
#     name: "Water Meter Alarms"

#   - platform: wmbus_meter
#     parent_id: water_meter
#     field: status
#     id: wmbus_water_status
#     name: "Water Meter Status"

lvgl:
  pages:
    - id: page_cc1101
      pad_top: 32
      pad_bottom: 32
      on_load:
        - lvgl.label.update:
            id: lbl_page_title
            text: wM-Bus
      <<: !include
        file: ../../gui/functions/swipe_navigation.yaml
      widgets:
        - obj:
            pad_top: 1
            pad_bottom: 1
            pad_left: 4
            pad_right: 4
            scrollable: false
            align: CENTER
            height: 100%
            width: 100%
            layout:
              type: FLEX
              flex_flow: COLUMN
              flex_align_main: SPACE_EVENLY
              flex_align_cross: CENTER
              flex_align_track: CENTER
              pad_row: 0
              pad_column: 0
            widgets:
              # --- Row 1: Water Meter ---
              - obj:
                  # This is a container for a single row
                  width: 100%
                  height: SIZE_CONTENT
                  pad_all: 0
                  pad_left: 4
                  pad_right: 4
                  layout:
                    type: FLEX
                    flex_flow: ROW
                    flex_align_main: SPACE_BETWEEN
                    flex_align_cross: CENTER
                    pad_row: 0
                    pad_column: 0
                  widgets:
                    # Descriptor Label
                    - label:
                        id: lbl_water_meter_manufacturer
                        text: "Kamstrup"
                        pad_left: 4
                        pad_right: 4
                        text_font: font_sm
                        text_color: c_text_s
                    # Value Label
                    - label:
                        id: lbl_water_meter_model
                        text: "FlowIQ2200: "
                        pad_right: 4
                        text_font: font_sm
                        text_color: c_text_s
                    # Unit Label
                    - label:
                        id: lbl_water_meter_serial
                        text: !secret water_meter_serial
                        text_font: font_sm
                        text_color: c_text_p

              # --- Row 2: Water Consumption ---
              - obj:
                  # This is a container for a single row
                  width: 100%
                  height: SIZE_CONTENT
                  pad_all: 0
                  pad_left: 4
                  pad_right: 4
                  layout:
                    type: FLEX
                    flex_flow: ROW
                    flex_align_main: SPACE_BETWEEN
                    flex_align_cross: CENTER
                    pad_row: 0
                    pad_column: 0
                  widgets:
                    # Descriptor Label
                    - label:
                        id: lbl_water_consumption_l
                        text: "Totalt forbruk: "
                        pad_left: 4
                        pad_right: 4
                        text_font: font_sm
                        text_color: c_text_s
                    # Value Label
                    - label:
                        id: lbl_water_consumption_value
                        text: "?"
                        pad_right: 4
                        text_font: font_lg
                        text_color: c_text_p
                    # Unit Label
                    - label:
                        id: lbl_water_consumption_unit
                        text: "m³"
                        text_font: font_md
                        text_color: c_text_s

              # --- Row 3: Water Meter Alarms ---
              - obj:
                  width: 100%
                  height: SIZE_CONTENT
                  pad_top: 10
                  pad_bottom: 10
                  pad_left: 4
                  pad_right: 4
                  layout:
                    type: FLEX
                    flex_flow: ROW
                    flex_align_main: SPACE_BETWEEN
                    flex_align_cross: CENTER
                    pad_row: 0
                    pad_column: 0
                  widgets:
                    # Descriptor Label
                    - label:
                        id: lbl_water_meter_alarms_l
                        text: "Varsler: "
                        pad_left: 4
                        pad_right: 4
                        text_font: font_sm
                        text_color: c_text_s
                    # Value Label
                    - label:
                        id: lbl_water_meter_alarms_value
                        text: "?"
                        pad_right: 4
                        text_font: font_md
                        text_color: c_text_p
                    # Unit Label
                    - label:
                        id: lbl_water_meter_alarms_spacer
                        text: " "
                        text_font: font_sm
                        text_color: c_text_s

              # --- Row 4: RSSI & Status ---
              - obj:
                  width: 100%
                  height: SIZE_CONTENT
                  pad_all: 0
                  pad_left: 4
                  pad_right: 4
                  layout:
                    type: FLEX
                    flex_flow: ROW
                    flex_align_main: SPACE_BETWEEN
                    flex_align_cross: CENTER
                    pad_row: 0
                    pad_column: 0
                  widgets:
                    - obj:
                        width: 60%
                        height: SIZE_CONTENT
                        pad_all: 0
                        pad_left: 10
                        pad_right: 0
                        layout:
                          type: FLEX
                          flex_flow: ROW
                          flex_align_main: END
                          flex_align_cross: CENTER
                          pad_row: 0
                          pad_column: 0
                        widgets:
                          # Descriptor Label
                          - label:
                              id: lbl_water_meter_status_l
                              text: "Status: "
                              pad_left: 4
                              pad_right: 4
                              text_font: font_sm
                              text_color: c_text_s
                          # Value Label
                          - label:
                              id: lbl_water_meter_status_value
                              text: "?"
                              pad_left: 4
                              text_font: font_md
                              text_color: c_text_p
                    - obj:
                        width: 40%
                        height: SIZE_CONTENT
                        pad_all: 0
                        pad_left: 0
                        pad_right: 10
                        layout:
                          type: FLEX
                          flex_flow: ROW
                          flex_align_main: START
                          flex_align_cross: CENTER
                          pad_row: 0
                          pad_column: 0
                        widgets:
                          # Descriptor Label
                          - label:
                              id: lbl_water_meter_rssi_l
                              text: "RSSI: "
                              pad_left: 4
                              pad_right: 4
                              text_font: font_sm
                              text_color: c_text_s
                          # Value Label
                          - label:
                              id: lbl_water_meter_rssi_value
                              text: "?"
                              pad_left: 4
                              pad_right: 4
                              text_font: font_md
                              text_color: c_text_p
                          # Unit Label
                          - label:
                              id: lbl_water_meter_rssi_unit
                              text: "dBm"
                              pad_left: 4
                              pad_right: 4
                              text_font: font_sm
                              text_color: c_text_s
