---
# https://docs.m5stack.com/en/module/Module_CC1101
# https://esphome.io/components/cc1101/

substitutions:
  module:
    cc1101:
      # General settings
      frequency: "868.95MHz"
      output_power: "-20"
      modulation_type: "GFSK"
      symbol_rate: "2400"
      # Tuner settings
      filter_bandwidth: "58.0kHz"
      fsk_deviation: "25.4kHz"
      # Packet Mode settings
      packet_mode: "true"
      num_preamble: "0"

logger:
  logs:
    cc1101: DEBUG

# Module CC1101
cc1101:
  id: radio_cc1101
  # Hardware settings
  cs_pin: ${pin.ext.mbus.p8}
  gdo0_pin:
    number: ${pin.ext.mbus.p2}
#    allow_other_uses: true
#  gdo2_pin: ${pin.ext.mbus.p22}
  # General settings
  frequency: ${module.cc1101.frequency}
  output_power: ${module.cc1101.output_power}
  modulation_type: ${module.cc1101.modulation_type}
  symbol_rate: ${module.cc1101.symbol_rate}
  # Tuner settings
  filter_bandwidth: ${module.cc1101.filter_bandwidth}
  fsk_deviation: ${module.cc1101.fsk_deviation}
  # Packet Mode settings
  packet_mode: ${module.cc1101.packet_mode}
  packet_length: 0
  num_preamble: ${module.cc1101.num_preamble}
  on_packet:
    - then:
        - lambda: |-
            // format_hex_pretty safely returns a std::string, .c_str() formats it for the logger
            ESP_LOGD("cc1101",
                  "packet %s freq_offset %.0f Hz rssi %.1f dBm lqi %u",
                  format_hex_pretty(x).c_str(),
                  freq_offset,
                  rssi,
                  lqi);
        # Set Last packet RSSI
        - sensor.template.publish:
            id: cc1101_rssi
            state: !lambda 'return rssi;'
        # Set Last packet LQI
        - sensor.template.publish:
            id: cc1101_lqi
            state: !lambda 'return lqi;'

#remote_transmitter:
#  pin:
#    number: ${pin.ext.mbus.p2}  # Must match GDO0
#    allow_other_uses: true
#  carrier_duty_percent: 100%
#  on_transmit:
#    then:
#      - cc1101.begin_tx:
#  on_complete:
#    then:
#      - cc1101.begin_rx:

#remote_receiver:
#  pin: ${pin.ext.mbus.p22}  # Must match GDO2

esphome:
  on_boot:
    # Sync CC1101 settings on boot (in case we changed them from Home Assistant)
    - priority: -10
      then:
        - cc1101.set_frequency:
            value: !lambda "return id(cc1101_frequency).state * 1e6;"
        - cc1101.set_output_power:
            value: !lambda "return id(cc1101_output_power).state;"
        - if:
            condition:
              select.is:
                id: cc1101_modulation_type
                options: "ASK/OOK"
            then:
              - cc1101.set_modulation_type:
                  value: ASK/OOK
        - if:
            condition:
              select.is:
                id: cc1101_modulation_type
                options: "2-FSK"
            then:
              - cc1101.set_modulation_type:
                  value: 2-FSK
        - if:
            condition:
              select.is:
                id: cc1101_modulation_type
                options: "4-FSK"
            then:
              - cc1101.set_modulation_type:
                  value: 4-FSK
        - if:
            condition:
              select.is:
                id: cc1101_modulation_type
                options: "GFSK"
            then:
              - cc1101.set_modulation_type:
                  value: GFSK
        - if:
            condition:
              select.is:
                id: cc1101_modulation_type
                options: "MSK"
            then:
              - cc1101.set_modulation_type:
                  value: MSK

# Adjustments
number:
  # Change frequency from Home Assistant
  - platform: template
    id: cc1101_frequency
    name: "CC1101 Frequency"
    entity_category: config
    device_class: frequency
    unit_of_measurement: MHz
    min_value: 300
    max_value: 928
    step: 0.01
    restore_value: true
    optimistic: true
    initial_value: 868.95
    mode: box
    disabled_by_default: true
    on_value:
      - then:
          - cc1101.set_frequency:
              value: !lambda "return x * 1e6;"
  # Change output power from Home Assistant
  - platform: template
    id: cc1101_output_power
    name: "CC1101 Output Power"
    entity_category: config
    device_class: signal_strength
    unit_of_measurement: dBm
    min_value: -30
    max_value: 10
    step: 1
    restore_value: true
    optimistic: true
    initial_value: -20
    mode: box
    disabled_by_default: true
    on_value:
      - then:
          - cc1101.set_output_power:
              value: !lambda "return x;"
select:
  # Change modulation type from Home Assistant
  - platform: template
    id: cc1101_modulation_type
    name: "CC1101 Modulation Type"
    icon: "mdi:signal-variant"
    entity_category: config
    options:
      - "ASK/OOK"
      - "2-FSK"
      - "4-FSK"
      - "GFSK"
      - "MSK"
    restore_value: true
    optimistic: true
    initial_option: "GFSK"
    disabled_by_default: true
    on_value:
      - then:
          - if:
              condition:
                lambda: 'return x == "ASK/OOK";'
              then:
                - cc1101.set_modulation_type:
                    value: ASK/OOK
          - if:
              condition:
                lambda: 'return x == "2-FSK";'
              then:
                - cc1101.set_modulation_type:
                    value: 2-FSK
          - if:
              condition:
                lambda: 'return x == "4-FSK";'
              then:
                - cc1101.set_modulation_type:
                    value: 4-FSK
          - if:
              condition:
                lambda: 'return x == "GFSK";'
              then:
                - cc1101.set_modulation_type:
                    value: GFSK
          - if:
              condition:
                lambda: 'return x == "MSK";'
              then:
                - cc1101.set_modulation_type:
                    value: MSK
  # Change symbol rate from Home Assistant
  - platform: template
    id: cc1101_symbol_rate
    name: "CC1101 Symbol Rate"
    icon: "mdi:speedometer"
    entity_category: config
    options:
      - "1200"
      - "2400"
      - "4800"
      - "9600"
      - "19200"
      - "38400"
      - "48000"
    restore_value: true
    optimistic: true
    initial_option: "2400"
    disabled_by_default: true
    on_value:
      - then:
          - cc1101.set_symbol_rate:
              # std::stoi converts the string 'x' to an integer
              value: !lambda "return std::stoi(x);"
  # Change RX attenuation from Home Assistant
  - platform: template
    id: cc1101_rx_attenuation
    name: "CC1101 RX Attenuation"
    icon: "mdi:broadcast"
    entity_category: config
    options:
      - "0dB"
      - "6dB"
      - "12dB"
      - "18dB"
    restore_value: true
    optimistic: true
    initial_option: "0dB"
    disabled_by_default: true
    on_value:
      - then:
          - if:
              condition:
                lambda: 'return x == "0dB";'
              then:
                - cc1101.set_rx_attenuation:
                    value: 0dB
          - if:
              condition:
                lambda: 'return x == "6dB";'
              then:
                - cc1101.set_rx_attenuation:
                    value: 6dB
          - if:
              condition:
                lambda: 'return x == "12dB";'
              then:
                - cc1101.set_rx_attenuation:
                    value: 12dB
          - if:
              condition:
                lambda: 'return x == "18dB";'
              then:
                - cc1101.set_rx_attenuation:
                    value: 18dB
switch:
  # Enable/disable RX mode from Home Assistant
  - platform: template
    id: cc1101_rx
    name: "CC1101 Receive"
    icon: "mdi:email-arrow-left"
    entity_category: config
    restore_mode: restore_default_on
    optimistic: true
    disabled_by_default: true
    on_turn_on:
      - then:
          - cc1101.begin_rx:
    on_turn_off:
      - then:
          - cc1101.set_idle:
button:
  # Put CC1101 into idle mode from Home Assistant
  - platform: template
    id: cc1101_idle
    name: "CC1101 Idle"
    icon: "mdi:email-lock"
    entity_category: config
    on_press:
      - then:
          - cc1101.set_idle:
          - switch.turn_off: cc1101_rx

# Diagnostics
sensor:
  # Last Packet RSSI
  - platform: template
    id: cc1101_rssi
    name: "CC1101 Last RSSI"
    update_interval: never
    device_class: signal_strength
    entity_category: diagnostic
    unit_of_measurement: dBm
    state_class: measurement
    accuracy_decimals: 1
    disabled_by_default: true
    filters:
      - throttle: 2s
  # Last Packet LQI
  - platform: template
    id: cc1101_lqi
    name: "CC1101 Last LQI"
    icon: "mdi:link-variant"
    update_interval: never
    unit_of_measurement: "LQI"
    entity_category: diagnostic
    state_class: measurement
    accuracy_decimals: 0
    disabled_by_default: true
    filters:
      - throttle: 2s