---
# https://docs.m5stack.com/en/module/PM2.5%20AIR%20QUALITY%20KIT%20(Excluding%20Core)
# https://esphome.io/components/sensor/pmsx003.html
# https://github.com/Chill-Division/M5Stack-ESPHome/

substitutions:
  module:
    air_quality_uart_bus: uart_mbus

# Module Air Quality
sensor:
  - platform: pmsx003
    type: PMSX003
    id: pmsx003_sensor
    uart_id: ${module.air_quality_uart_bus}
    update_interval: 120s
    pm_1_0:
      id: pm1_pmsa003
      name: "PM1 PMSA003"
      device_class: "pm1"
      state_class: "measurement"
      filters:
        - sliding_window_moving_average:
            window_size: 3
            send_every: 1
      on_value:
        - then:
            - lvgl.label.update:
                id: lbl_pm1_value
                text:
                  format: "%.1f"
                  args: [ 'x' ]
    pm_2_5:
      id: pm_25_pmsa003
      name: "PM2.5 PMSA003"
      device_class: "pm25"
      state_class: "measurement"
      filters:
        - sliding_window_moving_average:
            window_size: 3
            send_every: 1
      on_value:
        - then:
            - lvgl.label.update:
                id: lbl_pm25_value
                text:
                  format: "%.1f"
                  args: [ 'x' ]
    pm_10_0:
      id: pm_10_pmsa003
      name: "PM10 PMSA003"
      device_class: "pm10"
      state_class: "measurement"
      filters:
        - sliding_window_moving_average:
            window_size: 3
            send_every: 1
      on_value:
        - then:
            - lvgl.label.update:
                id: lbl_pm10_value
                text:
                  format: "%.1f"
                  args: [ 'x' ]

.sizing:
  - &page_styles
    <<: !include ../../gui/styles/page_styles.yaml
    page_pad_top: 32
    page_pad_bottom: 32
    screen_height: 240
    screen_width: 320
    # Calculate the usable height for the page content area
    # (screen_height - (2 * status_bar_height) - (2 * container_pad))
    # 240 - (2 * 32) - (2 * 1) = 170
    usable_screen_height: 170
    # Calculate the usable width for the page content area
    # (screen_width - (2 * container_pad))
    # 320  (2 * 4) = 312
    usable_screen_width: 312

  - &container_styles
    <<: !include ../../gui/styles/container_styles.yaml
    container_pad_top: 1
    container_pad_bottom: 1
    container_pad_left: 4
    container_pad_right: 4
    container_scrollable: false # prevents scrollbars on pages where space is used up to the last

lvgl:
  pages:
    - <<: !include 
        file: ../../gui/pages/air_quality/page.yaml
        vars:
          <<: [*page_styles, *container_styles]
          page_title: Luftkvalitet
