labels: [esp32_camera]
---
# https://wiki.seeedstudio.com/xiao_esp32s3_getting_started
# https://esphome.io/components/esp32_camera/
# Seeed XIAO ESP32S3 Sense HAT

substitutions:
  extension:
    i2c:
      internal:
        frequency: 200kHz
  module:
    camera:
      pixel_format: JPEG
      resolution: 800x600
      jpeg_quality: 20
      max_framerate: 2fps
      idle_framerate: 0.1fps
      agc_gain_ceiling: 64x
      wb_mode: auto

# Common Camera Settings
packages:
  camera: !include esp32_camera.yaml

i2c:
# Cam
  - id: i2c_cam
    sda: ${pin.cam.sda}
    scl: ${pin.cam.scl}
    frequency: ${extension.i2c.internal.frequency}
#    timeout: 5ms
    scan: true

esp32_camera:
  i2c_id: i2c_cam
  # PINS
  external_clock:
    pin: ${pin.cam.m_clk}
    frequency: 20MHz
  data_pins:
    - ${pin.cam.y2}
    - ${pin.cam.y3}
    - ${pin.cam.y4}
    - ${pin.cam.y5}
    - ${pin.cam.y6}
    - ${pin.cam.y7}
    - ${pin.cam.y8}
    - ${pin.cam.y9}
  vsync_pin: ${pin.cam.vs}
  href_pin: ${pin.cam.hs}
  pixel_clock_pin: ${pin.cam.p_clk}

  vertical_flip: false
  horizontal_mirror: false
  frame_buffer_count: 2 # defaults to 1
  # Exposure
  aec2: true # defaults to false
  ae_level: 2

# If NOT JPEG pixel_format
#camera_encoder:
#  type: esp32_camera
#  quality: 70
#  buffer_size: 524288
#  buffer_expand_size: 2097152