---
# https://docs.m5stack.com/en/unit/KMeterISO%20Unit
# https://esphome.io/components/sensor/kmeteriso

substitutions:
  kmeteriso_i2c_bus: i2c_grove

# UNIT PIR
sensor:
  - platform: kmeteriso
    i2c_id: $kmeteriso_i2c_bus
    id: kmeteriso_sensor
    temperature:
      id: temperature_kmeteriso
      name: "Temperature KMeterISO"
      device_class: "temperature"
    internal_temperature:
      id: temperature_kmeteriso_internal
      name: "Temperature KMeterISO Internal"
      device_class: "temperature"
