labels: [VL53L0X, distance, i2c]
---
# https://docs.m5stack.com/en/unit/Unit-ToF4M
# https://esphome.io/components/sensor/vl53l0x/
# WIP

substitutions:
  module:
    tof_i2c_bus: i2c_grove

# UNIT ToF4M
sensor:
  - platform: vl53l1x # variant not currently supported
    i2c_id: ${module.tof_i2c_bus}
    id: tof_distance
    signal_rate_limit: 0.25
    long_range: false
    timeout: 10ms
    timing_budget: 33000us
    name: "ToF4M Distance"
    update_interval: 1s
