---
# https://docs.m5stack.com/en/unit/DLight%20Unit
# https://esphome.io/components/sensor/bh1750.html

# Unit DLight
sensor:
  - platform: bh1750
    i2c_id: i2c_grove
    id: light_bh1750_unit
    name: "Unit Illuminance"
    device_class: "illuminance"
    state_class: "measurement"
    filters:
      - sliding_window_moving_average:
          window_size: 6
          send_every: 3
    address: 0x23
    update_interval: 5s