labels: [BH1750, illuminance, i2c]
---
# https://docs.m5stack.com/en/unit/DLight%20Unit
# https://esphome.io/components/sensor/bh1750.html

substitutions:
  module:
    dlight_i2c_bus: i2c_grove

# Unit DLight
sensor:
  - platform: bh1750
    i2c_id: ${module.dlight_i2c_bus}
    id: light_bh1750_unit
    name: "Unit Illuminance"
    device_class: "illuminance"
    state_class: "measurement"
    filters:
      - sliding_window_moving_average:
          window_size: 6
          send_every: 3
    address: 0x23
    update_interval: 5s
