---
# https://docs.m5stack.com/en/unit/co2
# https://esphome.io/components/sensor/scd4x.html

substitutions:
  co2_i2c_bus: i2c_grove

# UNIT CO2
sensor:
  - platform: scd4x
    i2c_id: $co2_i2c_bus
    id: unit_co2_scd40_sensor
    co2:
      id: co2_scd40_unit_co2
      name: "Unit CO2 SCD40 Co2"
      device_class: "carbon_dioxide"
      state_class: "measurement"
    temperature:
      id: temperature_scd40_unit_co2
      name: "Unit CO2 SCD40 Temperature"
      disabled_by_default: true
      device_class: "temperature"
      state_class: "measurement"
    humidity:
      id: humidity_scd40_unit_co2
      name: "Unit CO2 SCD40 Humidity"
      disabled_by_default: true
      device_class: "humidity"
      state_class: "measurement"
    altitude_compensation: 145m
#    ambient_pressure_compensation_source:
    address: 0x62
    update_interval: 30s
