labels: [VL53L0X, distance, i2c]
---
# https://docs.m5stack.com/en/unit/TOF
# https://docs.m5stack.com/en/unit/Unit%20Mini%20ToF-90
# https://esphome.io/components/sensor/vl53l0x/

substitutions:
  module:
    tof_i2c_bus: i2c_grove

# UNIT ToF/-90
sensor:
  - platform: vl53l1x # variant not currently supported
    i2c_id: ${module.tof_i2c_bus}
    id: tof_distance
    signal_rate_limit: 0.25
    long_range: false
    timeout: 10ms
    timing_budget: 33000us
    name: "ToF Distance"
    update_interval: 500ms
    filters:
      - filter_out: nan
      - lambda: |-
          if (x == 0) {
          return {};  // This filters out the reading
          } else {
          return x;   // This passes the reading through
          }
      - sliding_window_moving_average:
          window_size: 3
          send_every: 4
