---
# https://docs.m5stack.com/en/unit/co2
# https://esphome.io/components/sensor/scd4x.html

substitutions:
  co2_i2c_bus: i2c_grove

# UNIT CO2
sensor:
  - platform: scd4x
    i2c_id: $co2_i2c_bus
    id: scd40_sensor
    co2:
      id: co2_scd40
      name: "CO2 SCD40"
      device_class: "carbon_dioxide"
    temperature:
      id: temperature_scd40
      name: "Temperature SCD40"
      disabled_by_default: true
      device_class: "temperature"
    humidity:
      id: humidity_scd40
      name: "Humidity SCD40"
      disabled_by_default: true
      device_class: "humidity"
    altitude_compensation: 145m
#    ambient_pressure_compensation_source:
    address: 0x62
    update_interval: 30s
