labels: [A3144E, gpio]
---
# https://docs.m5stack.com/en/unit/hall
# https://esphome.io/components/binary_sensor/gpio/

substitutions:
  module:
    hall_in_pin: ${pin.ext.gpio.grove.in}

# UNIT Hall
binary_sensor:
  - platform: gpio
    id: hall_sensor
    pin:
      number: ${module.hall_in_pin}
      mode:
        input: true
    filters:
      - delayed_on_off: 250ms
      - delayed_off: !lambda 'return id(hall_off_latency).state * 1000;'
    name: "Hall Sensor"
    device_class: opening

# Adjustable off delay
number:
  - platform: template
    id: hall_off_latency
    name: "Hall Off Latency"
    icon: mdi:clock-end
    entity_category: config
    unit_of_measurement: s
    min_value: 0
    max_value: 30
    step: 1
    restore_value: true
    optimistic: true
    initial_value: 0
    mode: slider
