---
# https://docs.m5stack.com/en/unit/tvoc
# https://esphome.io/components/sensor/sgp30.html

substitutions:
  module:
    tvoc_i2c_bus: i2c_grove

# UNIT TVOC/eCO2
sensor:
  - platform: sgp30
    i2c_id: ${module.tvoc_i2c_bus}
    id: unit_tvoc_sgp30_sensor
    eco2:
      id: eco2_sgp30
      name: "eCO2 SGP30"
      device_class: "carbon_dioxide"
      state_class: "measurement"
      filters:
        - sliding_window_moving_average:
            window_size: 30
            send_every: 30
    tvoc:
      id: tvoc_sgp30
      name: "TVOC SGP30"
      device_class: "volatile_organic_compounds_parts"
      state_class: "measurement"
      unit_of_measurement: "ppm"
      filters:
        # PPB to PPM
        - multiply: 0.001
        - sliding_window_moving_average:
            window_size: 30
            send_every: 30
    address: 0x58
    update_interval: 1s
    compensation:
      temperature_source: temperature_local
      humidity_source: humidity_local
