---
# https://esphome.io/cookbook/lvgl#theme-and-style-definitions
# LVGL Night Owl
#
# DARK
#

substitutions:
  default_font: MONSERRAT_16

lvgl:
  disp_bg_color: 0x000000
  bg_color: 0x000000
  default_font: $default_font
  theme:
    label:
      text_font: $default_font
      text_color: 0xFDF6EB
    obj:
      bg_color: 0x000000
      bg_opa: TRANS
    bar:
      bg_color: 0x1D3B53
      indicator:
        bg_color: 0xc792ea
    button:
      bg_color: 0x1D3B53
      bg_opa: COVER
      border_color: 0x0B253A
      border_width: 1
      text_color: 0xFDF6EB
      pressed: # set some button colors to be different in pressed state
        bg_color: 0x5f7e97
      checked: # set some button colors to be different in checked state
        bg_color: 0x0B253A
        text_color: 0xff2c83
    buttonmatrix:
      bg_opa: TRANSP
      border_color: 0x0B253A
      border_width: 0
      text_color: 0xFDF6EB
      pad_all: 0
      items: # set all your buttonmatrix buttons to use your custom defined styles and font
        bg_color: 0x1D3B53
        bg_opa: COVER
        border_color: 0x0B253A
        border_width: 1
        text_color: 0xFDF6EB
        text_font: $default_font
        pressed:
          bg_color: 0x5f7e97
        checked:
          bg_color: 0x0B253A
          text_color: 0xff2c83
    switch:
      bg_color: 0x637777
      bg_grad_color: 0x5f7e97
      bg_grad_dir: VER
      bg_opa: 80%
      checked:
        bg_color: 0xc792ea
        bg_grad_color: 0x7e57c2
        bg_grad_dir: VER
        bg_opa: COVER
      knob:
        bg_color: 0xEEE8D5
        bg_opa: COVER
        checked:
          bg_color: 0xFDF6EB
    slider:
      border_width: 1
      border_opa: 15%
      bg_color: 0x637777
      bg_opa: 25%
      indicator:
        bg_color: 0xc792ea
        bg_opa: COVER
      knob:
        bg_color: 0xc792ea
        bg_opa: COVER
        border_color: 0x7e57c2
        border_width: 1
        text_color: 0xFDF6EB
    tabview:
      border_color: 0x0B253A
#      items:
#        text_color: 0xFDF6EB
  style_definitions:
    - id: header_footer
      bg_color: 0x1D3B53
      bg_opa: COVER
      border_opa: TRANSP
      radius: 0
      pad_all: 0
      pad_row: 0
      pad_column: 0
      border_color: 0x0B253A
      text_color: 0xFDF6EB
      width: 100%
      height: 30
    - id: date_style
      align: center
      text_color: 0x637777
      color: 0x637777
      radius: 4
      pad_all: 2