globals:
  - id: nordpool_points_y
    type: int[9]
    restore_value: no
    initial_value: FILL IN INITAL SCALED BASELINE Y POINTS HERE
  - id: nordpool_points_x
    type: int[9]
    restore_value: yes
    initial_value: FILL IN INITAL SPACED X POINTS HERE

sensor:
  - platform: combination
    id: nordpool_price_max
    type: max
    sources:
      - source: nordpool_price_0
      - source: nordpool_price_1
      - source: nordpool_price_2
      - source: nordpool_price_3
      - source: nordpool_price_4
      - source: nordpool_price_5
      - source: nordpool_price_6
      - source: nordpool_price_7
      - source: nordpool_price_8
    on_value:
      - script.execute: update_price_chart

script:
  - id: update_price_chart
    mode: single
    then:
      - lambda: |-
          modified script as before to insert values into the globals
      - delay: 5s
      - lvgl.line.update:
          id: lvgl_nordpool_line
          points:
            # Extend to fill points
            - x: !lambda return nordpool_points_x[0];
              y: !lambda return nordpool_points_y[0];
            - x: !lambda return nordpool_points_x[1];
              y: !lambda return nordpool_points_y[1];