# Functions to update the NordPool LVGL page

globals:
  # These arrays will store the coordinates for the line graph's points.
  - id: nordpool_points_y
    type: int[9]
    restore_value: no
    initial_value: '{0, 10, 20, 30, 40, 50, 60, 70, 80}'
  - id: nordpool_points_x
    type: int[9]
    restore_value: no
    initial_value: '{0, 10, 20, 30, 40, 50, 60, 70, 80}'

esphome:
  # On boot, run the script to calculate the initial graph layout.
  on_boot:
    priority: -10.0 # Run before the display subsystem starts
    then:
      - script.execute: nordpool_initialize_graph_layout

script:
  - id: nordpool_initialize_graph_layout
    then:
      - lambda: |-
          // This script runs on boot to set the initial X and Y coordinates.
          const float graph_container_h = nordpool_grid_row_2_height;
          const float graph_container_w = usable_page_width;
          const float line_w = nordpool_line_width;
          const float inset = line_w / 2.0;

          const float graph_drawable_h = graph_container_h - line_w;
          const float graph_drawable_w = graph_container_w - line_w;

          const int mid_y = (int)round(inset + graph_drawable_h / 2.0);

          // Calculate and store initial X and Y points
          for (int i = 0; i < 9; ++i) {
            float x_coord = i * (graph_drawable_w - 1) / 8.0;
            id(nordpool_points_x)[i] = (int)round(inset + x_coord);
            id(nordpool_points_y)[i] = mid_y;
          }

  - id: nordpool_update_chart
    mode: single
    then:
      - lambda: |-
          // STEP 1: Calculate all Y coordinates and save them to the global array.
          float prices[9];
          prices[0] = id(nordpool_price_0).state;
          prices[1] = id(nordpool_price_1).state;
          prices[2] = id(nordpool_price_2).state;
          prices[3] = id(nordpool_price_3).state;
          prices[4] = id(nordpool_price_4).state;
          prices[5] = id(nordpool_price_5).state;
          prices[6] = id(nordpool_price_6).state;
          prices[7] = id(nordpool_price_7).state;
          prices[8] = id(nordpool_price_8).state;

          float min_p = id(nordpool_price_min).state;
          float max_p = id(nordpool_price_max).state;

          if (isnan(min_p) || isnan(max_p)) { return; }
          for (int i = 0; i < 9; ++i) {
            if (isnan(prices[i])) { return; }
          }

          const float graph_container_h = nordpool_grid_row_2_height;
          const float line_w = nordpool_line_width;
          const float inset = line_w / 2.0;
          const float graph_drawable_h = graph_container_h - line_w;

          for (int i = 0; i < 9; ++i) {
            if (max_p == min_p) {
              id(nordpool_points_y)[i] = (int)round(graph_container_h / 2.0);
            } else {
              float scaled_y = graph_drawable_h - ((prices[i] - min_p) / (max_p - min_p) * graph_drawable_h);
              id(nordpool_points_y)[i] = (int)round(inset + scaled_y);
            }
          }
          // ADD THIS LINE FOR DEBUGGING
          ESP_LOGD("update_chart", "Calculated Y-Points: %d, %d, %d, %d, %d, %d, %d, %d, %d",
                id(nordpool_points_y)[0], id(nordpool_points_y)[1], id(nordpool_points_y)[2],
                id(nordpool_points_y)[3], id(nordpool_points_y)[4], id(nordpool_points_y)[5],
                id(nordpool_points_y)[6], id(nordpool_points_y)[7], id(nordpool_points_y)[8]);
      - delay: 1s
      - lvgl.line.update:
          # STEP 2: Redraw the line using the new values from the global arrays.
          id: lvgl_nordpool_line
          points:
            - x: !lambda return id(nordpool_points_x)[0];
              y: !lambda return id(nordpool_points_y)[0];
            - x: !lambda return id(nordpool_points_x)[1];
              y: !lambda return id(nordpool_points_y)[1];
            - x: !lambda return id(nordpool_points_x)[2];
              y: !lambda return id(nordpool_points_y)[2];
            - x: !lambda return id(nordpool_points_x)[3];
              y: !lambda return id(nordpool_points_y)[3];
            - x: !lambda return id(nordpool_points_x)[4];
              y: !lambda return id(nordpool_points_y)[4];
            - x: !lambda return id(nordpool_points_x)[5];
              y: !lambda return id(nordpool_points_y)[5];
            - x: !lambda return id(nordpool_points_x)[6];
              y: !lambda return id(nordpool_points_y)[6];
            - x: !lambda return id(nordpool_points_x)[7];
              y: !lambda return id(nordpool_points_y)[7];
            - x: !lambda return id(nordpool_points_x)[8];
              y: !lambda return id(nordpool_points_y)[8];

sensor:
  # All your homeassistant sensors for prices 0 through 8 go here
  # This setup ensures each widget is updated when its corresponding sensor value changes.
  - platform: homeassistant
    id: nordpool_price_0
    entity_id: sensor.waveshare_nordpool_future_offset
    attribute: price0
    on_value:
      - lvgl.label.update:
          id: lbl_nordpool_price_0
          text:
            format: "%.0f"
            args: [ 'x' ]
  - platform: homeassistant
    id: nordpool_price_1
    entity_id: sensor.waveshare_nordpool_future_offset
    attribute: price1
  - platform: homeassistant
    id: nordpool_price_2
    entity_id: sensor.waveshare_nordpool_future_offset
    attribute: price2
    on_value:
      - lvgl.label.update:
          id: lbl_nordpool_price_2
          text:
            format: "%.0f"
            args: [ 'x' ]
  - platform: homeassistant
    id: nordpool_price_3
    entity_id: sensor.waveshare_nordpool_future_offset
    attribute: price3
  - platform: homeassistant
    id: nordpool_price_4
    entity_id: sensor.waveshare_nordpool_future_offset
    attribute: price4
    on_value:
      - lvgl.label.update:
          id: lbl_nordpool_price_4
          text:
            format: "%.0f"
            args: [ 'x' ]
  - platform: homeassistant
    id: nordpool_price_5
    entity_id: sensor.waveshare_nordpool_future_offset
    attribute: price5
  - platform: homeassistant
    id: nordpool_price_6
    entity_id: sensor.waveshare_nordpool_future_offset
    attribute: price6
    on_value:
      - lvgl.label.update:
          id: lbl_nordpool_price_6
          text:
            format: "%.0f"
            args: [ 'x' ]
  - platform: homeassistant
    id: nordpool_price_7
    entity_id: sensor.waveshare_nordpool_future_offset
    attribute: price7
  - platform: homeassistant
    id: nordpool_price_8
    entity_id: sensor.waveshare_nordpool_future_offset
    attribute: price8
    on_value:
      - lvgl.label.update:
          id: lbl_nordpool_price_8
          text:
            format: "%.0f"
            args: [ 'x' ]

  # Combination sensors to find the min and max price across all points
  - platform: combination
    id: nordpool_price_min
    type: min
    sources:
      - source: nordpool_price_0
      - source: nordpool_price_1
      - source: nordpool_price_2
      - source: nordpool_price_3
      - source: nordpool_price_4
      - source: nordpool_price_5
      - source: nordpool_price_6
      - source: nordpool_price_7
      - source: nordpool_price_8
  - platform: combination
    id: nordpool_price_max
    type: max
    sources:
      - source: nordpool_price_0
      - source: nordpool_price_1
      - source: nordpool_price_2
      - source: nordpool_price_3
      - source: nordpool_price_4
      - source: nordpool_price_5
      - source: nordpool_price_6
      - source: nordpool_price_7
      - source: nordpool_price_8
    on_value:
      # When the max price changes (meaning any price has changed), run the update script.
      - script.execute: nordpool_update_chart

text_sensor:
  # All your homeassistant text_sensors for the time labels go here
  - platform: homeassistant
    id: nordpool_time_0
    entity_id: sensor.waveshare_nordpool_future_offset
    attribute: time0
    on_value:
      - lvgl.label.update:
          id: lbl_nordpool_time_0
          text: !lambda return id(nordpool_time_0).state;
  - platform: homeassistant
    id: nordpool_time_2
    entity_id: sensor.waveshare_nordpool_future_offset
    attribute: time2
    on_value:
      - lvgl.label.update:
          id: lbl_nordpool_time_2
          text: !lambda return id(nordpool_time_2).state;
  - platform: homeassistant
    id: nordpool_time_4
    entity_id: sensor.waveshare_nordpool_future_offset
    attribute: time4
    on_value:
      - lvgl.label.update:
          id: lbl_nordpool_time_4
          text: !lambda return id(nordpool_time_4).state;
  - platform: homeassistant
    id: nordpool_time_6
    entity_id: sensor.waveshare_nordpool_future_offset
    attribute: time6
    on_value:
      - lvgl.label.update:
          id: lbl_nordpool_time_6
          text: !lambda return id(nordpool_time_6).state;
  - platform: homeassistant
    id: nordpool_time_8
    entity_id: sensor.waveshare_nordpool_future_offset
    attribute: time8
    on_value:
      - lvgl.label.update:
          id: lbl_nordpool_time_8
          text: !lambda return id(nordpool_time_8).state;
