---
# PINs for ESP32 upesy_wroom

substitutions:
  # i2c
  i2c_int_sda_pin: GPIO21
  i2c_int_scl_pin: GPIO22
  # UART
  uart0_tx__pin: GPIO1
  uart0_rx_pin: GPIO3
  uart2_tx__pin: GPIO17
  uart2_rx_pin: GPIO16
  # SPI
  hspi_clk_pin: GPIO14
  hspi_mosi_pin: GPIO13
  hspi_miso_pin: GPIO12
  hspi_cs_pin: GPIO15
  spi_clk_pin: GPIO18
  spi_mosi_pin: GPIO23
  spi_miso_pin: GPIO19
  spi_cs_pin: GPIO5

  # DAC
  dac1_pin: GPIO25
  dac2_pin: GPIO26
  # ADC
  adc1_0_pin: GPIO36
  adc1_3_pin: GPIO39
  adc1_4_pin: GPIO32
  adc1_5_pin: GPIO33
  adc1_6_pin: GPIO34
  adc1_7_pin: GPIO35
  adc2_0_pin: GPIO4
  adc2_2_pin: GPIO2
  adc2_3_pin: GPIO15
  adc2_4_pin: GPIO13
  adc2_5_pin: GPIO12
  adc2_6_pin: GPIO14
  adc2_7_pin: GPIO27
  adc2_8_pin: GPIO25
  adc2_9_pin: GPIO26
  # Deep sleep GPIO
  rtc_gpio0_pin: GPIO36
  rtc_gpio3_pin: GPIO39
  rtc_gpio4_pin: GPIO34
  rtc_gpio5_pin: GPIO35
  rtc_gpio6_pin: GPIO25
  rtc_gpio7_pin: GPIO26
  rtc_gpio8_pin: GPIO33
  rtc_gpio9_pin: GPIO32
  rtc_gpio10_pin: GPIO4
  rtc_gpio12_pin: GPIO2
  rtc_gpio13_pin: GPIO15
  rtc_gpio14_pin: GPIO13
  rtc_gpio15_pin: GPIO12
  rtc_gpio16_pin: GPIO14
  rtc_gpio17_pin: GPIO27
  # SD
  sd_cmd_pin: GPIO15
  sd_clk_pin: GPIO14
  sd_dat1_pin: GPIO4
  sd_dat2_pin: GPIO12
  sd_dat3_pin: GPIO13
  # Touch
  touch0_pin: GPIO4
  touch2_pin: GPIO2
  touch3_pin: GPIO15
  touch4_pin: GPIO13
  touch5_pin: GPIO12
  touch6_pin: GPIO14
  touch7_pin: GPIO27
  touch8_pin: GPIO33
  touch9_pin: GPIO32