---
# PINs for Freenove ESP32-S3-WROOM-CAM
# Model:  esp32-s3 n16r8
# Light:  WS2812 RGB
# FLASH:  16MB
# PSRAM:  8MB
# https://github.com/s60sc/ESP32-CAM_MJPEG2SD/blob/master/camera_pins.h#L336
# https://docs.freenove.com/projects/fnk0085/en/latest/index.html

substitutions:
  pin:
    light:
      led: GPIO2
      rgb: GPIO48
    int:
      spi:
        clk: GPIO39
        mosi: GPIO38
        miso: GPIO40
        cs: GPIO38
      i2c:
        sda: GPIO4
        scl: GPIO5
    cam:
      y0: nc
      y1: nc
      y2: GPIO11
      y3: GPIO9
      y4: GPIO8
      y5: GPIO10
      y6: GPIO12
      y7: GPIO18
      y8: GPIO17
      y9: GPIO16
      vs: GPIO6
      hs: GPIO7
      p_clk: GPIO13
      m_clk: GPIO15
      rst: -1
      pwr: -1
    card:
      d0: GPIO40
      d1: GPIO41
      d2: GPIO14
      d3: GPIO47
      cs: GPIO38
      cmd: GPIO38
      clk: GPIO39
    
    ext:
      h1:
        p1: 3v3
        p2: en
        p3: GPIO4
        p4: GPIO5
        p5: GPIO6
        p6: GPIO7
        p7: GPIO15
        p8: GPIO16
        p9: GPIO17
        p10: GPIO18
        p11: GPIO8
        p12: GPIO3
        p13: GPIO46
        p14: GPIO9
        p15: GPIO10
        p16: GPIO11
        p17: GPIO12
        p18: GPIO13
        p19: GPIO14
        p20: GND
      h2:
        p1: GPIO43
        p2: GPIO44
        p3: GPIO1
        p4: GPIO2
        p5: GPIO42
        p6: GPIO41
        p7: GPIO40
        p8: GPIO39
        p9: GPIO38
        p10: GPIO37
        p11: GPIO36
        p12: GPIO35
        p13: GPIO0
        p14: GPIO45
        p15: GPIO48
        p16: GPIO47
        p17: GPIO21
        p18: GPIO20
        p19: GPIO19
        p20: GND
