---
# PINs for ESP32_S3-n16r8_CAM
# Model:  esp32-s3 n16r8
# Light:  Single Flash
# FLASH:  16MB
# PSRAM:  8MB

substitutions:
  pin:
    # light:
    #   led: GPIO2
    #   flash: GPIO3
    # int:
    #   spi:
    #     clk: GPIO39
    #     mosi: GPIO38
    #     miso: GPIO2
    #     cs: GPIO38
    #   i2c:
    #     sda: GPIO4
    #     scl: GPIO5
    # cam:
    #   y0: nc
    #   y1: nc
    #   y2: GPIO11
    #   y3: GPIO9
    #   y4: GPIO8
    #   y5: GPIO10
    #   y6: GPIO12
    #   y7: GPIO18
    #   y8: GPIO17
    #   y9: GPIO16
    #   vs: GPIO6
    #   hs: GPIO7
    #   p_clk: GPIO13
    #   m_clk: GPIO15
    #   pwr: nc
    # card:
    #   d0: GPIO40
    #   d1: nc
    #   d2: nc
    #   d3: nc
    #   cs: GPIO38
    #   cmd: GPIO38
    #   clk: GPIO39
    
    ext:
      h1:
        p1: 3v3
        p2: GPIO16
        p3: GPIO0
        p4: gnd
        p5: 5v
        p6: u0rx
        p7: u0tx
        p8: gnd
      h2:
        p1: 5v
        p2: gnd
        p3: GPIO12
        p4: GPIO13
        p5: GPIO15
        p6: GPIO14
        p7: GPIO2
        p8: GPIO4

# OrderID:  3075049747013317
