---
# PINs for Sunton module ESP32-S3 with Guition 3.5" display

substitutions:
  pin:
    int:
      i2c:
        sda: GPIO4
        scl: GPIO8
      spi:
        clk: GPIO47
        dat1: GPIO21
        dat2: GPIO48
        dat3: GPIO40
        dat4: GPIO39
        disp:
          cs: GPIO45
        card:
          clk: GPIO12
          mosi: GPIO11
          miso: GPIO13
          cs: GPIO10
      bat_feedback: GPIO5
    
    light:
      disp_bl: GPIO1
    
    audio:
      i2s_lrclk: GPIO2
      i2s_bclk: GPIO42
      i2s_mclk: GPIO00
      i2s_dout: GPIO41
    
    ext:
      i2c:
        hc100:
          sda: GPIO18
          scl: GPIO17
        jst125:
          sda: GPIO17
          scl: GPIO18
        grove:
          sda: GPIO17
          scl: GPIO18
      uart:
        hc100:
          tx: GPIO17
          rx: GPIO18
        jst125:
          tx: GPIO18
          rx: GPIO17
        grove:
          tx: GPIO17
          rx: GPIO18
      gpio:
        hc100:
          in: GPIO17
          out: GPIO18
        jst125:
          in: GPIO18
          out: GPIO17
        grove:
          in: GPIO17
          out: GPIO18
      jst125:
        p1: GPIO5
        p2: GPIO6
        p3: GPIO7
        p4: GPIO15
        p5: GPIO16
        p6: GPIO46
        p7: GPIO9
        p8: GPIO14
    
    btn:
      boot: GPIO0

# Internal
  # I2C
  i2c_int_sda_pin: GPIO4 # io04
  i2c_int_scl_pin: GPIO8 # io08
  # SPI quad
  spi_clk_pin: GPIO47 # io47
  spi_data1_pin: GPIO21 # io21
  spi_data2_pin: GPIO48 # io48
  spi_data3_pin: GPIO40 # io40
  spi_data4_pin: GPIO39 # io39
  disp_cs_pin: GPIO45 # io45
  # SD Card
  card_clk_pin: GPIO12 # io12
  card_cs_pin: GPIO10 # io10
  card_mosi_pin: GPIO11 # io11
  card_miso_pin: GPIO13 # io13
  # i2s Audio
  i2s_lrclk_pin: GPIO2 # io2
  i2s_bclk_pin: GPIO42 # io42
  i2s_mclk_pin: GPIO00 # io00

# Extended IO
  # i2s Audio
  i2s_dout_pin: GPIO41 # io41
  # HC1.0 4pin
  i2c_hc100_sda_pin: GPIO18 # io18
  i2c_hc100_scl_pin: GPIO17 # io17
  in_hc100_pin: GPIO17
  out_hc100_pin: GPIO18
  tx_hc100_pin: GPIO17
  rx_hc100_pin: GPIO18
  # JST1.25 4pin
  i2c_jst125_sda_pin: GPIO17 # io17
  i2c_jst125_scl_pin: GPIO18 # io18
  i2c_grove_sda_pin: GPIO17 # io17
  i2c_grove_scl_pin: GPIO18 # io18
  in_jst125_pin: GPIO18
  out_jst125_pin: GPIO17
  tx_jst125_pin: GPIO18
  rx_jst125_pin: GPIO17
  # JST1.25 8pin
  jst125_1_pin: GPIO5 # io5
  jst125_2_pin: GPIO6 # io6
  jst125_3_pin: GPIO7 # io7
  jst125_4_pin: GPIO15 # io15
  jst125_5_pin: GPIO16 # io16
  jst125_6_pin: GPIO46 # io46
  jst125_7_pin: GPIO9 # io9
  jst125_8_pin: GPIO14 # io14

# Button
  boot_pin: GPIO0 # io00
# LED
  disp_bl_pin: GPIO1 # io01
# Power MOS
  bat_feedback: GPIO5 # io05