---
# https://docs.m5stack.com/en/core/StickS3
# PINs for m5stack StickS3

substitutions:
  pin:
    btn:
      power: GPIO35
      side: GPIO12
      front: GPIO11

    int:
      i2c:
        sda: GPIO47
        scl: GPIO48
        int: GPIO4
      spi:
        clk: GPIO40
        mosi: GPIO39
        disp:
          cs: GPIO41
          dc: GPIO45
          rst: GPIO21
          bl: GPIO38
      pwr_mos: GPIO4
      bat_feedback: GPIO0
    
    light:
      disp_bl: GPIO38
      ir:
        rx: GPIO42
        tx: GPIO46
    
    audio:
      i2s_lrclk: GPIO15
      i2s_bclk: GPIO17
      i2s_mclk: GPIO18
      i2s_din: GPIO16
      i2s_dout: GPIO14
      spk: GPIO14
      mic: GPIO16
    
    m5pm1:
      chg_stat: GPIO0
      irq: GPIO1
      l3b_en: GPIO2
      spk_pulse: GPIO3
      imu_int: GPIO4
    
    ext:
      i2c:
        grove:
          sda: GPIO9
          scl: GPIO10
        hat:
          sda: GPIO43
          scl: GPIO6
        hat2:
          sda: GPIO8
          scl: boot
      uart:
        grove:
          tx: GPIO10
          rx: GPIO9
        hat:
          tx: GPIO43
          rx: GPIO6
        hat2:
          tx: GPIO8
          rx: boot
      gpio:
        grove:
          in: GPIO10
          out: GPIO9
        hat:
          in: GPIO7
          out: GPIO6
        hat2:
          in: GPIO1
          out: boot
      hat2:
        left:
          p1: gnd
          p2: 5v_ext
          p3: boot
          p4: GPIO1
          p5: GPIO8
          p6: bat
          p7: 3v3
          p8: 5v_in
        right:
          p1: GPIO5
          p2: GPIO4
          p3: GPIO6
          p4: GPIO7
          p5: GPIO43
          p6: GPIO44
          p7: GPIO2
          p8: GPIO3
        p1: gnd
        p2: GPIO5
        p3: 5v_ext
        p4: GPIO4
        p5: boot
        p6: GPIO6
        p7: GPIO1
        p8: GPIO7
        p9: GPIO8
        p10: GPIO43
        p11: bat
        p12: GPIO44
        p13: 3v3
        p14: GPIO2
        p15: 5v_in
        p16: GPIO3
