---
# https://docs.m5stack.com/en/core/fire_v2.7
# PINs for m5stack Fire

substitutions:
  pin:
    int:
      i2c:
        sda: GPIO21
        scl: GPIO22
      spi:
        clk: GPIO18
        mosi: GPIO23
        miso: GPIO19
        disp:
          cs: GPIO14
          dc: GPIO27
          reset: GPIO33
        card:
          cs: GPIO4
    
    light:
      disp_bl: GPIO32
      rgb: GPIO15
    
    audio:
      i2s_lrclk: GPIO13
      mic: GPIO34
      buzzer: GPIO25
      spk_l: GPIO25
      spk_r: GPIO26
    
    ext:
      i2c:
        mbus:
          sda: GPIO21
          scl: GPIO22
        grove:
          sda: GPIO21
          scl: GPIO22
      uart:
        mbus:
          tx: GPIO17
          rx: GPIO16
        grove:
          tx: GPIO17
          rx: GPIO16
      gpio:
        mbus:
          in: GPIO36
          out: GPIO26
        grove:
          in: GPIO36
          out: GPIO26
      mbus:
        p2: GPIO35
        p4: GPIO36
        p7: GPIO23
        p8: GPIO25
        p9: GPIO19
        p10: GPIO26
        p11: GPIO18
        p13: GPIO3
        p14: GPIO2
        p15: GPIO16
        p16: GPIO17
        p17: GPIO21
        p18: GPIO22
        p19: GPIO2
        p20: GPIO5
        p21: GPIO12
        p22: GPIO13
        p23: GPIO15
        p24: GPIO0
        p26: GPIO34

    btn:
      a: GPIO39
      b: GPIO38
      c: GPIO37


  # Internal
  i2c_int_sda_pin: GPIO21
  i2c_int_scl_pin: GPIO22
  spi_clk_pin: GPIO18
  spi_mosi_pin: GPIO23
  spi_miso_pin: GPIO19
  disp_cs_pin: GPIO14
  disp_dc_pin: GPIO27
  disp_rs_pin: GPIO33
  card_cs_pin: GPIO4
  # M-Bus
  i2c_mbus_sda_pin: GPIO21
  i2c_mbus_scl_pin: GPIO22
  tx_mbus_pin: GPIO17
  rx_mbus_pin: GPIO16
  alt_tx_pin: GPIO26
  alt_rx_pin: GPIO36
  mbus2: GPIO35
  mbus4: GPIO36
  mbus7: GPIO23
  mbus8: GPIO25
  mbus9: GPIO19
  mbus10: GPIO26
  mbus11: GPIO18
  mbus13: GPIO3
  mbus14: GPIO2
  mbus15: GPIO16
  mbus16: GPIO17
  mbus17: GPIO21
  mbus18: GPIO22
  mbus19: GPIO2
  mbus20: GPIO5
  mbus21: GPIO12
  mbus22: GPIO13
  mbus23: GPIO15
  mbus24: GPIO0
  mbus26: GPIO34
  # GROVE
  i2c_grove_sda_pin: GPIO21
  i2c_grove_scl_pin: GPIO22
  in_grove_pin: GPIO36
  out_grove_pin: GPIO26
  tx_grove_pin: GPIO17
  rx_grove_pin: GPIO16
  # Button
  button_a_pin: GPIO39
  button_b_pin: GPIO38
  button_c_pin: GPIO37
  # LED
  disp_bl_pin: GPIO32
  rgb_pin: GPIO15
  # Mic & Speaker
  i2s_lrclk_pin: GPIO13
  mic_pin: GPIO34
  spk_l_pin: GPIO25
  spk_r_pin: GPIO26
