---
# https://docs.m5stack.com/en/core/AtomS3%20Lite
# PINs for m5stack ATOM S3 Lite

substitutions:
  # GROVE
  i2c_grove_sda_pin: GPIO2
  i2c_grove_scl_pin: GPIO1
  in_grove_pin: GPIO1
  out_grove_pin: GPIO2
  tx_grove_pin: GPIO1
  rx_grove_pin: GPIO2
  # Mate HAT
  i2c_hat_sda_pin: GPIO6
  i2c_hat_scl_pin: GPIO5
  in_hat_pin: GPIO8
  out_hat_pin: GPIO7
  tx_uart_hat_pin: GPIO6
  rx_uart_hat_pin: GPIO5
  # Port ABC
  i2c_port_abc_sda_pin: GPIO38
  i2c_port_abc_scl_pin: GPIO39
  in_port_abc_pin: GPIO8
  out_port_abc_pin: GPIO7
  tx_port_abc_pin: GPIO6
  rx_port_abc_pin: GPIO5
  # Button
  button_pin: GPIO41
  # LED
  led_pin: GPIO35
  ir_pin: GPIO4
