---
# https://docs.m5stack.com/en/core/coreink
# PINs for m5stack CoreInk

substitutions:
  pin:
    int:
      i2c:
        sda: GPIO21
        scl: GPIO22
      spi:
        clk: GPIO18
        mosi: GPIO23
        miso: GPIO34
        disp:
          cs: GPIO9
          dc: GPIO15
          busy: GPIO4
          reset: GPIO0
      pwr_mos: GPIO12
      bat_feedback: GPIO35
      rtc_wakeup: GPIO19
    
    light:
      led: GPIO10
    
    audio:
      buzzer: GPIO2

    ext:
      i2c:
        mbus:
          sda: GPIO21
          scl: GPIO22
        grove:
          sda: GPIO32
          scl: GPIO33
        hat:
          sda: GPIO25
          scl: GPIO26
      uart:
        mbus:
          tx: GPIO14
          rx: GPIO23
        grove:
          tx: GPIO33
          rx: GPIO32
        hat:
          tx: GPIO25
          rx: GPIO26
      gpio:
        mbus:
          in: GPIO36
          out: GPIO26
        grove:
          in: GPIO33
          out: GPIO32
        hat:
          in: GPIO36
          out: GPIO26
      mbus:
        p7: GPIO13
        p8: GPIO14
        p9: GPIO21
        p10: GPIO22
        p11: GPIO18
        p12: GPIO36
        p13: GPIO34
        p14: GPIO26
        p15: GPIO23
        p16: GPIO25

    btn:
      stick:
        up: GPIO37
        press: GPIO38
        down: GPIO39
      top: GPIO5
      side: GPIO27

  # Internal
  i2c_int_sda_pin: GPIO21
  i2c_int_scl_pin: GPIO22
  spi_clk_pin: GPIO18
  spi_mosi_pin: GPIO23
  spi_miso_pin: GPIO34
  disp_cs_pin: GPIO9
  disp_dc_pin: GPIO15
  disp_busy_pin: GPIO4
  disp_reset_pin: GPIO0
  # M-Bus
  i2c_mbus_sda_pin: GPIO21
  i2c_mbus_scl_pin: GPIO22
  tx_mbus_pin: GPIO14
  rx_mbus_pin: GPIO23
  mbus7: GPIO13
  mbus8: GPIO14
  mbus9: GPIO21
  mbus10: GPIO22
  mbus11: GPIO18
  mbus12: GPIO36
  mbus13: GPIO34
  mbus14: GPIO26
  mbus15: GPIO23
  mbus16: GPIO25
  # GROVE
  i2c_grove_sda_pin: GPIO32
  i2c_grove_scl_pin: GPIO33
  in_grove_pin: GPIO33
  out_grove_pin: GPIO32
  tx_grove_pin: GPIO33
  rx_grove_pin: GPIO32
  # HAT
  i2c_hat_sda_pin: GPIO25
  i2c_hat_scl_pin: GPIO26
  in_hat_pin: GPIO36
  out_hat_pin: GPIO26
  tx_uart_hat_pin: GPIO25
  rx_uart_hat_pin: GPIO26
  # Button
  stick_up_pin: GPIO37
  stick_press_pin: GPIO38
  stick_down_pin: GPIO39
  button_top_pin: GPIO5
  button_side_pin: GPIO27
  # LED
  led_pin: GPIO10
  # Buzzer
  buzzer_pin: GPIO2
  # Power MOS
  pwr_mos_pin: GPIO12
  bat_feedback: GPIO35
  rtc_wakeup_pin: GPIO19
