---
# https://docs.m5stack.com/en/core/AtomS3R
# PINs for m5stack ATOM S3R

substitutions:
  pin:
    int:
      i2c:
        sda: GPIO45
        scl: GPIO0
      spi:
        clk: GPIO15
        mosi: GPIO21
        disp:
          cs: GPIO14
          dc: GPIO42
          reset: GPIO48
    
    light:
      ir: GPIO47
    
    ext:
      i2c:
        grove:
          sda: GPIO2
          scl: GPIO1
        hat:
          sda: GPIO6
          scl: GPIO5
        port_abc:
          sda: GPIO38
          scl: GPIO39
      uart:
        grove:
          tx: GPIO1
          rx: GPIO2
        hat:
          tx: GPIO6
          rx: GPIO5
        port_abc:
          tx: GPIO6
          rx: GPIO5
      gpio:
        grove:
          in: GPIO1
          out: GPIO2
        hat:
          in: GPIO8
          out: GPIO7
        port_abc:
          in: GPIO8
          out: GPIO7
    
    btn: GPIO41

  # Internal
  i2c_int_sda_pin: GPIO45
  i2c_int_scl_pin: GPIO0
  spi_clk_pin: GPIO15
  spi_mosi_pin: GPIO21
  disp_cs_pin: GPIO14
  disp_dc_pin: GPIO42
  disp_reset_pin: GPIO48
  # GROVE
  i2c_grove_sda_pin: GPIO2
  i2c_grove_scl_pin: GPIO1
  in_grove_pin: GPIO1
  out_grove_pin: GPIO2
  tx_grove_pin: GPIO1
  rx_grove_pin: GPIO2
  # Mate HAT
  i2c_hat_sda_pin: GPIO6
  i2c_hat_scl_pin: GPIO5
  in_hat_pin: GPIO8
  out_hat_pin: GPIO7
  tx_uart_hat_pin: GPIO6
  rx_uart_hat_pin: GPIO5
  # Port ABC
  i2c_port_abc_sda_pin: GPIO38
  i2c_port_abc_scl_pin: GPIO39
  in_port_abc_pin: GPIO8
  out_port_abc_pin: GPIO7
  tx_port_abc_pin: GPIO6
  rx_port_abc_pin: GPIO5
  # Button
  button_pin: GPIO41
  # LED
  ir_pin: GPIO47
