---
# https://docs.m5stack.com/en/core/StickS3
# PINs for m5stack StickS3

substitutions:
  pin:
    int:
      i2c:
        sda: GPIO47
        scl: GPIO48
      spi:
        clk: GPIO40
        mosi: GPIO39
        disp:
          cs: GPIO41
          dc: nc
          reset: GPIO21
      pwr_mos: GPIO4
      bat_feedback: GPIO0
    
    light:
      disp_bl: GPIO38
      ir:
        rx: GPIO42
        tx: GPIO46
    
    audio:
      i2s_lrclk: GPIO15
      i2s_bclk: GPIO17
      i2s_mclk: GPIO18
      i2s_din: GPIO16
      i2s_dout: GPIO14
      spk: GPIO14
      mic: GPIO16
    
    ext:
      i2c:
        grove:
          sda: GPIO9
          scl: GPIO10
        hat:
          sda: GPIO43
          scl: GPIO6
      uart:
        grove:
          tx: GPIO10
          rx: GPIO9
        hat:
          tx: GPIO43
          rx: GPIO6
      gpio:
        grove:
          in: GPIO10
          out: GPIO9
        hat:
          in: GPIO7
          out: GPIO6
    
    btn:
      power: GPIO35
      side: GPIO12
      front: GPIO11

  # Internal
  i2c_int_sda_pin: GPIO21
  i2c_int_scl_pin: GPIO22
  i2s_lrclk_pin: GPIO15
  i2s_bclk_pin: GPIO17
  i2s_mclk_pin: GPIO18
  spi_clk_pin: GPIO40
  spi_mosi_pin: GPIO39
  disp_cs_pin: GPIO41
  disp_dc_pin: nc
  disp_reset_pin: GPIO21
  # GROVE
  i2c_grove_sda_pin: GPIO9
  i2c_grove_scl_pin: GPIO10
  in_grove_pin: GPIO10
  out_grove_pin: GPIO9
  tx_grove_pin: GPIO10
  rx_grove_pin: GPIO9
  # HAT
  i2c_hat_sda_pin: GPIO43
  i2c_hat_scl_pin: GPIO6
  in_hat_pin: GPIO7
  out_hat_pin: GPIO6
  tx_uart_hat_pin: GPIO43
  rx_uart_hat_pin: GPIO6
  # Button
  button_power_pin: GPIO35
  button_side_pin: GPIO12
  button_front_pin: GPIO11
  # LED
  disp_bl_pin: GPIO38
  ir_rx_pin: GPIO42
  ir_tx_pin: GPIO46
  # Buzzer & Mic
  spk_pin: GPIO14
  mic_pin: GPIO16
  # Power MOS
  pwr_mos_pin: GPIO4
  bat_feedback_pin: GPIO0
