---
# https://docs.m5stack.com/en/core/coreink
# PINs for m5stack CoreInk

substitutions:
  # Internal
  i2c_int_sda_pin: GPIO21
  i2c_int_scl_pin: GPIO22
  spi_clk_pin: GPIO18
  spi_mosi_pin: GPIO23
  spi_miso_pin: GPIO34
  disp_cs_pin: GPIO9
  disp_dc_pin: GPIO15
  disp_busy_pin: GPIO4
  disp_reset_pin: GPIO0
  # M-Bus
  i2c_mbus_sda_pin: GPIO21
  i2c_mbus_scl_pin: GPIO22
  tx_mbus_pin: GPIO14
  rx_mbus_pin: GPIO23
  # GROVE
  i2c_grove_sda_pin: GPIO32
  i2c_grove_scl_pin: GPIO33
  in_grove_pin: GPIO33
  out_grove_pin: GPIO32
  tx_grove_pin: GPIO33
  rx_grove_pin: GPIO32
  # HAT
  i2c_hat_sda_pin: GPIO25
  i2c_hat_scl_pin: GPIO26
  in_hat_pin: GPIO36
  out_hat_pin: GPIO26
  tx_uart_hat_pin: GPIO25
  rx_uart_hat_pin: GPIO26
  # Button
  stick_up_pin: GPIO37
  stick_press_pin: GPIO38
  stick_down_pin: GPIO39
  button_top_pin: GPIO5
  button_side_pin: GPIO27
  # LED
  led_pin: GPIO10
  # Buzzer
  buzzer_pin: GPIO2
  # Power MOS
  power_mos_pin: GPIO12
  bat_feedback: GPIO35
