---
# https://docs.m5stack.com/en/core/M5StampS3%20PIN1.27
# PINs for m5stack Stamp-S3 PIN1.27

substitutions:
  pin:
    int:
      pwr_mos: GPIO46
    
    light:
      disp_bl: GPIO38
      led: GPIO21
    
    ext:
      i2c:
        sda: GPIO13
        scl: GPIO15
      uart:
        tx: GPIO43
        rx: GPIO44
      spi:
        clk: GPIO36
        mosi: GPIO35
        disp:
          cs: GPIO37
          dc: GPIO34
          reset: GPIO33
      gpio:
        p1: GPIO1
        p2: GPIO2
        p3: GPIO3
        p4: GPIO4
        p5: GPIO5
        p6: GPIO6
        p7: GPIO7
        p8: GPIO8
        p9: GPIO9
        p10: GPIO10
        p11: GPIO11
        p12: GPIO12
        p13: GPIO13
        p14: GPIO14
        p15: GPIO15
        p16: GPIO16
        p17: GPIO17
        p18: GPIO18

    btn: GPIO0
  
  # GPIO + ADC
  g1: GPIO1
  g2: GPIO2
  g3: GPIO3
  g4: GPIO4
  g5: GPIO5
  g6: GPIO6
  g7: GPIO7
  g8: GPIO8
  g9: GPIO9
  g10: GPIO10
  # GPIO
  g11: GPIO11
  g12: GPIO12
  g14: GPIO14
  # i2c
  g13: GPIO13 # SDA
  g15: GPIO15 # SCL
  # UART
  g43: GPIO43 # Tx
  g44: GPIO44 # Rx
  # OTG / Serial
  spi_clk_pin: GPIO36 # SCK
  spi_mosi_pin: GPIO35 # DAT
  disp_cs_pin: GPIO37 # CS
  disp_dc_pin: GPIO34 # RS
  disp_rst_pin: GPIO33 # RST
  disp_bl_pin: GPIO38 # BL
  g16: GPIO16
  g17: GPIO17
  g18: GPIO18
  # Button
  button_pin: GPIO0
  # LED
  led_pin: GPIO21
  # Power
  pwr_mos_pin: GPIO46
