---
# https://docs.m5stack.com/en/core/M5StickC%20PLUS2
# PINs for m5stack StickC Plus2

substitutions:
  # Internal
  i2c_int_sda_pin: GPIO21
  i2c_int_scl_pin: GPIO22
  i2s_lrclk_pin: GPIO26
  i2s_bclk_pin: GPIO0
  spi_clk_pin: GPIO13
  spi_mosi_pin: GPIO15
  disp_cs_pin: GPIO5
  disp_dc_pin: GPIO14
  disp_reset_pin: GPIO12
  # GROVE
  i2c_grove_sda_pin: GPIO32
  i2c_grove_scl_pin: GPIO33
  in_grove_pin: GPIO33
  out_grove_pin: GPIO32
  tx_grove_pin: GPIO33
  rx_grove_pin: GPIO32
  # HAT
  i2c_hat_sda_pin: GPIO0
  i2c_hat_scl_pin: GPIO26
  in_hat_pin: GPIO36
  out_hat_pin: GPIO26
  tx_uart_hat_pin: GPIO0
  rx_uart_hat_pin: GPIO26
  # Button
  button_power_pin: GPIO35
  button_side_pin: GPIO39
  button_front_pin: GPIO37
  # LED
  disp_bl_pin: GPIO27
  led_pin: GPIO19
  ir_pin: GPIO19
  # Buzzer & Mic
  buzzer_pin: GPIO2
  mic_pin: GPIO34
  # Power MOS
  power_mos_pin: GPIO4
  bat_feedback: GPIO38
