---
# https://docs.m5stack.com/en/core/M5CoreS3%20SE
# PINs for m5stack Core S3SE

substitutions:
  pin:
    int:
      i2c:
        sda: GPIO12
        scl: GPIO11
      spi:
        clk: GPIO36
        mosi: GPIO37
        miso: GPIO35
        disp:
          cs: GPIO3
          dc: GPIO35
        card:
          cs: GPIO4
#      pwr_mos: GPIO4
#      bat_feedback: GPIO38
    
#    light:
#      disp_bl: GPIO27
#      led: GPIO19
#      ir: GPIO19
    
    audio:
      i2s_lrclk: GPIO33
      i2s_wck: GPIO33
      i2s_bclk: GPIO34
      i2s_mclk: GPIO0
      i2s_din: GPIO14
      i2s_dat1: GPIO14
      i2s_dout: GPIO13
      i2s_dato: GPIO13
    
    ext:
      i2c:
        mbus:
          sda: GPIO2
          scl: GPIO1
        grove:
          sda: GPIO2
          scl: GPIO1
      uart:
        mbus:
          tx: GPIO43
          rx: GPIO44
        grove:
          tx: GPIO17
          rx: GPIO18
      gpio:
        mbus:
          in: GPIO8
          out: GPIO9
        grove:
          in: GPIO8
          out: GPIO9
      mbus:
        p2: GPIO10
        p4: GPIO8
        p7: GPIO37
        p8: GPIO5
        p9: GPIO35
        p10: GPIO9
        p11: GPIO36
        p13: GPIO44
        p14: GPIO43
        p15: GPIO18
        p16: GPIO17
        p17: GPIO12
        p18: GPIO11
        p19: GPIO2
        p20: GPIO1
        p21: GPIO6
        p22: GPIO7
        p23: GPIO13
        p24: GPIO0
        p26: GPIO14

#    btn:
#      power: GPIO35
#      side: GPIO39
#      front: GPIO37


  # Internal
  i2c_int_sda_pin: GPIO12
  i2c_int_scl_pin: GPIO11
  spi_clk_pin: GPIO36
  spi_mosi_pin: GPIO37
  spi_miso_pin: GPIO35
  disp_cs_pin: GPIO3
  disp_dc_pin: GPIO35
  card_cs_pin: GPIO4
  # M-Bus
  i2c_mbus_sda_pin: GPIO2
  i2c_mbus_scl_pin: GPIO1
  tx1_mbus_pin: GPIO43
  rx1_mbus_pin: GPIO44
  tx2_mbus_pin: GPIO17
  rx2_mbus_pin: GPIO18
  in_mbus_pin: GPIO8
  out_mbus_pin: GPIO9
  mbus2: GPIO10
  mbus4: GPIO8
  mbus7: GPIO37
  mbus8: GPIO5
  mbus9: GPIO35
  mbus10: GPIO9
  mbus11: GPIO36
  mbus13: GPIO44
  mbus14: GPIO43
  mbus15: GPIO18
  mbus16: GPIO17
  mbus17: GPIO12
  mbus18: GPIO11
  mbus19: GPIO2
  mbus20: GPIO1
  mbus21: GPIO6
  mbus22: GPIO7
  mbus23: GPIO13
  mbus24: GPIO0
  mbus26: GPIO14
  # GROVE
  i2c_grove_sda_pin: GPIO2
  i2c_grove_scl_pin: GPIO1
  in_grove_pin: GPIO8
  out_grove_pin: GPIO9
  tx_grove_pin: GPIO17
  rx_grove_pin: GPIO18
  # Button
#  button_power_pin: GPIO35
#  button_side_pin: GPIO39
#  button_front_pin: GPIO37
  # LED
#  tft_bl_pin: GPIO27
#  led_pin: GPIO19
#  ir_pin: GPIO19
  # Mic & Speaker
  i2s_lrclk_pin: GPIO33
  i2s_wck_pin: GPIO33
  i2s_bclk_pin: GPIO34
  i2s_mclk_pin: GPIO0
  i2s_din_pin: GPIO14
  i2s_dat1_pin: GPIO14
  i2s_dout_pin: GPIO13
  i2s_dato_pin: GPIO13
  # Power MOS
#  power_mos_pin: GPIO4
#  bat_feedback: GPIO38
