---
# https://docs.m5stack.com/en/core/M5NanoC6
# PINs for m5stack Nano C6

substitutions:
  pin:
    int:
      rgb_pwr: GPIO19
    
    light:
      rgb: GPIO20
      led: GPIO7
      ir: GPIO3
    
    ext:
      i2c:
        grove:
          sda: GPIO2
          scl: GPIO1
      uart:
        grove:
          tx: GPIO1
          rx: GPIO2
      gpio:
        grove:
          in: GPIO1
          out: GPIO2
    
    btn: GPIO9

  # Internal
  rgb_pwr_pin: GPIO19
  # GROVE
  i2c_grove_sda_pin: GPIO2
  i2c_grove_scl_pin: GPIO1
  in_grove_pin: GPIO1
  out_grove_pin: GPIO2
  tx_grove_pin: GPIO1
  rx_grove_pin: GPIO2
  # Button
  button_pin: GPIO9
  # LED
  led_pin: GPIO7
  rgb_pin: GPIO20
  ir_pin: GPIO3
