---
# PINs for ESP32 upesy_wroom

substitutions:
  pin:
    int:
      i2c:
        sda: GPIO21
        scl: GPIO22
      uart:
        tx0: GPIO1
        rx0: GPIO3
        tx2: GPIO17
        rx2: GPIO16
      hspi:
        clk: GPIO14
        mosi: GPIO13
        miso: GPIO12
        cs: GPIO15
      vspi:
        clk: GPIO18
        mosi: GPIO23
        miso: GPIO19
        cs: GPIO5
      dac:
        p1: GPIO25
        p2: GPIO26
      adc:
        p1_0: GPIO36
        p1_3: GPIO39
        p1_4: GPIO32
        p1_5: GPIO33
        p1_6: GPIO34
        p1_7: GPIO35
        p2_0: GPIO4
        p2_1: GPIO0
        p2_2: GPIO2
        p2_3: GPIO15
        p2_4: GPIO13
        p2_5: GPIO12
        p2_6: GPIO14
        p2_7: GPIO27
        p2_8: GPIO25
        p2_9: GPIO26
      rtc_gpio:
        p0: GPIO36
        p3: GPIO39
        p4: GPIO34
        p5: GPIO35
        p6: GPIO25
        p7: GPIO26
        p8: GPIO33
        p9: GPIO32
        p10: GPIO4
        p11: GPIO0
        p12: GPIO2
        p13: GPIO15
        p14: GPIO13
        p15: GPIO12
        p16: GPIO14
        p17: GPIO27
      card:
        cmd: GPIO15
        clk: GPIO14
        dat0: GPIO2
        dat1: GPIO4
        dat2: GPIO12
        dat3: GPIO13
      touch:
        p0: GPIO4
        p1: GPIO0
        p2: GPIO2
        p3: GPIO15
        p4: GPIO13
        p5: GPIO12
        p6: GPIO14
        p7: GPIO27
        p8: GPIO33
        p9: GPIO32
    
    light:
      led: GPIO2

  # i2c
  i2c_int_sda_pin: GPIO21
  i2c_int_scl_pin: GPIO22
  # UART
  uart0_tx__pin: GPIO1
  uart0_rx_pin: GPIO3
  uart2_tx__pin: GPIO17
  uart2_rx_pin: GPIO16
  # SPI
  hspi_clk_pin: GPIO14
  hspi_mosi_pin: GPIO13
  hspi_miso_pin: GPIO12
  hspi_cs_pin: GPIO15
  vspi_clk_pin: GPIO18
  vspi_mosi_pin: GPIO23
  vspi_miso_pin: GPIO19
  vspi_cs_pin: GPIO5
  # LED
  led_pin: GPIO2

  # DAC
  dac1_pin: GPIO25
  dac2_pin: GPIO26
  # ADC
  adc1_0_pin: GPIO36
  adc1_3_pin: GPIO39
  adc1_4_pin: GPIO32
  adc1_5_pin: GPIO33
  adc1_6_pin: GPIO34
  adc1_7_pin: GPIO35
  adc2_0_pin: GPIO4
  adc2_1_pin: GPIO0
  adc2_2_pin: GPIO2
  adc2_3_pin: GPIO15
  adc2_4_pin: GPIO13
  adc2_5_pin: GPIO12
  adc2_6_pin: GPIO14
  adc2_7_pin: GPIO27
  adc2_8_pin: GPIO25
  adc2_9_pin: GPIO26
  # Deep sleep GPIO
  rtc_gpio0_pin: GPIO36
  rtc_gpio3_pin: GPIO39
  rtc_gpio4_pin: GPIO34
  rtc_gpio5_pin: GPIO35
  rtc_gpio6_pin: GPIO25
  rtc_gpio7_pin: GPIO26
  rtc_gpio8_pin: GPIO33
  rtc_gpio9_pin: GPIO32
  rtc_gpio10_pin: GPIO4
  rtc_gpio11_pin: GPIO0
  rtc_gpio12_pin: GPIO2
  rtc_gpio13_pin: GPIO15
  rtc_gpio14_pin: GPIO13
  rtc_gpio15_pin: GPIO12
  rtc_gpio16_pin: GPIO14
  rtc_gpio17_pin: GPIO27
  # SD
  sd_cmd_pin: GPIO15
  sd_clk_pin: GPIO14
  sd_dat0_pin: GPIO2
  sd_dat1_pin: GPIO4
  sd_dat2_pin: GPIO12
  sd_dat3_pin: GPIO13
  # Touch
  touch0_pin: GPIO4
  touch1_pin: GPIO0
  touch2_pin: GPIO2
  touch3_pin: GPIO15
  touch4_pin: GPIO13
  touch5_pin: GPIO12
  touch6_pin: GPIO14
  touch7_pin: GPIO27
  touch8_pin: GPIO33
  touch9_pin: GPIO32