---
# https://www.waveshare.com/wiki/E-Paper_ESP32_Driver_Board
# PINs for Waveshare e-paper ESP32 driver board

substitutions:
  pin:
    int:
      i2c:
        sda: GPIO21
        scl: GPIO22
      uart:
        tx0: GPIO1
        rx0: GPIO3
        tx1: GPIO10
        rx1: GPIO9
        tx2: GPIO17
        rx2: GPIO16
      spi:
        clk: GPIO13
        mosi: GPIO14
        disp:
          cs: GPIO15
          dc: GPIO27
          reset: GPIO26
          busy: GPIO25
      vspi:
        clk: GPIO18
        mosi: GPIO23
        miso: GPIO19
        cs: GPIO5
      dac:
        p1: GPIO25
        p2: GPIO26
      adc:
        p0: GPIO36
        p1: GPIO39
        p2: GPIO32
        p3: GPIO33
        p4: GPIO34
        p5: GPIO35
        p6: GPIO4
        p7: GPIO0
        p8: GPIO2
        p9: GPIO15
        p10: GPIO13
        p11: GPIO12
        p12: GPIO14
        p13: GPIO27
        p14: GPIO25
        p15: GPIO26
      flash:
        cmd: GPIO11
        clk: GPIO6
        dat0: GPIO7
        dat1: GPIO8
        dat2: GPIO9
        dat3: GPIO10
      touch:
        p0: GPIO4
        p1: GPIO0
        p2: GPIO2
        p3: GPIO15
        p4: GPIO13
        p5: GPIO12
        p6: GPIO14
        p7: GPIO27
        p8: GPIO33
        p9: GPIO32

  # i2c
  i2c_sda_pin: GPIO21
  i2c_scl_pin: GPIO22
  # UART
  tx0_pin: GPIO1
  rx0_pin: GPIO3
  tx1_pin: GPIO10
  rx1_pin: GPIO9
  tx2_pin: GPIO17
  rx2_pin: GPIO16
  # SPI
  spi_clk_pin: GPIO13
  spi_mosi_pin: GPIO14
  disp_cs_pin: GPIO15
  disp_dc_pin: GPIO27
  disp_busy_pin: GPIO25
  disp_reset_pin: GPIO26
  vspi_clk_pin: GPIO18
  vspi_mosi_pin: GPIO23
  vspi_miso_pin: GPIO19
  vspi_cs_pin: GPIO5

  # DAC
  dac1_pin: GPIO25
  dac2_pin: GPIO26
  # ADC
  adc0_pin: GPIO36
  adc3_pin: GPIO39
  adc4_pin: GPIO32
  adc5_pin: GPIO33
  adc6_pin: GPIO34
  adc7_pin: GPIO35
  adc10_pin: GPIO4
  adc11_pin: GPIO0
  adc12_pin: GPIO2
  adc13_pin: GPIO15
  adc14_pin: GPIO13
  adc15_pin: GPIO12
  adc16_pin: GPIO14
  adc17_pin: GPIO27
  adc18_pin: GPIO25
  adc19_pin: GPIO26
  # Flash
  flash_cmd_pin: GPIO11
  flash_clk_pin: GPIO6
  flash_dat0_pin: GPIO7
  flash_dat1_pin: GPIO8
  flash_dat2_pin: GPIO9
  flash_dat3_pin: GPIO10
  # Touch
  touch0_pin: GPIO4
  touch1_pin: GPIO0
  touch2_pin: GPIO2
  touch3_pin: GPIO15
  touch4_pin: GPIO13
  touch5_pin: GPIO12
  touch6_pin: GPIO14
  touch7_pin: GPIO27
  touch8_pin: GPIO33
  touch9_pin: GPIO32