---
# https://www.wemos.cc/en/latest/d1/d1_mini.html
# PINs for ESP8266 Lolin D1 Mini
# Model:  ESP8266EX
# Flash:  4MB

substitutions:
  pin:
    light:
      led: GPIO2
    int:
      i2c:
        sda: GPIO4
        scl: GPIO5
      spi:
        clk: GPIO14
        miso: GPIO12
        mosi: GPIO13

    ext:
      h1:
        p1: rst
        p2: a0
        p3: GPIO16 # d0
        p4: GPIO14 # d5 SCK
        p5: GPIO12 # d6 MISO
        p6: GPIO13 # d7 MOSI
        p7: GPIO15 # d8
        p8: 3v
      h2:
        p1: tx
        p2: rx
        p3: GPIO5 # d1 SCL
        p4: GPIO4 # d2 SDA
        p5: GPIO0 # d3
        p6: GPIO2 # d4 LED
        p7: GND
        p8: 5v
      h:
        d0: GPIO16
        d1: GPIO5
        d2: GPIO4
        d3: GPIO0
        d4: GPIO2
        d5: GPIO14
        d6: GPIO12
        d7: GPIO13
        d8: GPIO15
