---
# Display auto

# extend time component
time:
  - platform: homeassistant
    id: !extend time_homeassistant
    on_time:
      - seconds: 0
        minutes: /5
        then:
          - if:
              condition:
                and:
                  - switch.is_on: display_auto
                  - lambda: 'return id(data_updated) == true;'
              then:
                - if:
                    condition:
                      binary_sensor.is_on: motion_detected
                    then:
                      - lvgl.resume:
                      - logger.log: "Sensor data updated and activity in home detected: Refreshing display..."
                      - script.execute: update_screen
                    else:
                      - lvgl.pause:
                      - logger.log: "Sensor data updated but no activity in home - skipping display refresh."
              else:
                - lvgl.pause:
                - logger.log: "No sensors updated - skipping display refresh."

switch:
  # Switch to turn on/off the display auto off feature
  - platform: template
    id: display_auto
    optimistic: true
    restore_mode: ALWAYS_ON
    name: "Display auto off"
    entity_category: config

script:
  # Script for updating screen - Refresh display and publish refresh count and time.
  - id: update_screen
    then:
      - lvgl.resume:
      - lvgl.label.update:
          id: lbl_disp_updated
          text:
            time_format: "%H:%M"
            time: !lambda return id(time_homeassistant).now();
      - lambda: 'id(data_updated) = false;'
      - component.update: display_eink
      - lambda: 'id(recorded_display_refresh) += 1;'
      - lambda: 'id(display_last_update).publish_state(id(time_homeassistant).now().timestamp);'
      - lvgl.pause:
  # Script for home screen - Refresh display and publish refresh count and time.
  - id: script_home_screen
    then:
      - lvgl.resume:
      - lvgl.page.show: page_home
      - lvgl.label.update:
          id: lbl_disp_updated
          text:
            time_format: "%H:%M"
            time: !lambda return id(time_homeassistant).now();
      - lambda: 'id(data_updated) = false;'
      - component.update: display_eink
      - lambda: 'id(recorded_display_refresh) += 1;'
      - lambda: 'id(display_last_update).publish_state(id(time_homeassistant).now().timestamp);'
      - lvgl.pause:
  # Script for next screen - Refresh display and publish refresh count and time.
  - id: script_next_screen
    then:
      - lvgl.resume:
      - lvgl.page.next:
      - lvgl.label.update:
          id: lbl_disp_updated
          text:
            time_format: "%H:%M"
            time: !lambda return id(time_homeassistant).now();
      - lambda: 'id(data_updated) = false;'
      - component.update: display_eink
      - lambda: 'id(recorded_display_refresh) += 1;'
      - lambda: 'id(display_last_update).publish_state(id(time_homeassistant).now().timestamp);'
      - lvgl.pause:

# Global variables for detecting if the display needs to be refreshed. (Thanks @paviro!)
globals:
  - id: data_updated
    type: bool
    restore_value: no
    initial_value: 'false'
  - id: initial_data_received
    type: bool
    restore_value: no
    initial_value: 'false'
  - id: recorded_display_refresh
    type: int
    restore_value: yes
    initial_value: '0'

# Buttons in Home Assistant
button:
  - platform: template
    name: "Refresh Screen"
    entity_category: config
    on_press:
      - script.execute: update_screen
  - platform: template
    name: "Next Screen"
    entity_category: config
    on_press:
      - lvgl.page.next:
      - component.update: display_eink

sensor:
  # Create sensors for monitoring remotely.
  - platform: template
    name: "Display Last Update"
    device_class: timestamp
    entity_category: "diagnostic"
    id: display_last_update
  - platform: template
    name: "Recorded Display Refresh"
    accuracy_decimals: 0
    unit_of_measurement: "Refreshes"
    state_class: "total_increasing"
    entity_category: "diagnostic"
    lambda: 'return id(recorded_display_refresh);'