esphome:
  name: ble-relay1
  friendly_name: ble-relay1

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "Y69V92HZxrAHu5ErTKByol6tlUa8Iz+vfjHRMwTSqm0="

ota:
  password: "3b57e7146594a12e43783b0138eda510"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

esp32_ble_tracker:
  scan_parameters:
    active: true

bluetooth_proxy:
  active: true
