packages:
  <<: !include_dir_named common
#  <<: !include_dir_named bluetooth
#  board: !include board/m5stack_atom_s3r_esp_idf.yaml

substitutions:
  devicename: m5s-as3r-0387f4

esphome:
  comment: "M5Stack Atom S3R 9539bc"
  name: $devicename
  friendly_name: $devicename
  platformio_options:
    build_flags:
      - "-w" # https://docs.platformio.org/en/latest/projectconf/sections/env/options/build/build_flags.html

esp32:
#  board: m5stack-atoms3
#  variant: esp32s3
#  framework:
#    type: arduino
  board: m5stack-atoms3
  variant: esp32s3
  framework:
    type: esp-idf
    version: 5.3.1
    platform_version: 6.9.0
    # Custom sdkconfig options
    sdkconfig_options: # https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/kconfig.html#config-compiler-disable-gcc12-warnings
      CONFIG_SPIFFS_DBG: n

#ENV.III
sensor:
  - platform: sht3xd
    i2c_id: hat
    temperature:
      id: temperature_sht3xd
    humidity:
      name: "Humidity"
      id: humidity
    address: 0x44
    update_interval: 30s

  - platform: qmp6988
    i2c_id: hat
    temperature:
      id: temperature_qmp6988
      oversampling: 16x
    pressure:
      name: "Pressure"
      oversampling: 16x
    address: 0x70
    update_interval: 30s
    iir_filter: 2x
    
  - platform: combination
    type: median
    id: temperature_homeassistant
    name: "Temperature"
    device_class: "temperature"
    sources:
      - source: temperature_sht3xd
      - source: temperature_qmp6988
    filters:
      - or:
        - heartbeat: 900s
        - delta: 0.15

i2c:
# Grove port
  - id: grove
    sda: 2
    scl: 1
    scan: true
# Mate HAT
  - id: hat
    sda: 6
    scl: 5
    scan: true
# Internal
  - id: internal
    sda: 0
    scl: 45
    scan: true

spi:
  clk_pin: GPIO15 #AtomS3: GPIO17
  mosi_pin: GPIO21 #AtomS3: GPIO21

#G4=IR
#remote_transmitter:
#  pin: 47
#  carrier_duty_percent: 50%
#  rmt_symbols: 144

color:
  - id: my_yellow
    red: 100%
    green: 100%
    blue: 0%
  
font:
  - file: "gfonts://Roboto"
    id: roboto_24
    size: 24

display:
  - platform: ili9xxx
    model: st7789v
    id: display
    cs_pin: GPIO14 #AtomS3: GPIO15
    dc_pin: GPIO42 #AtomS3: GPIO33
    reset_pin: GPIO48 #AtomS3: GPIO34
    update_interval: 1s
    dimensions:
      height: 128
      width: 128
      offset_height: 1
      offset_width: 2
    # Rotate 180deg
    transform:
      mirror_x: true
      mirror_y: true
    invert_colors: false
    lambda: |-
      it.rectangle(0,  0, it.get_width(), it.get_height(), id(my_yellow));      
      it.strftime((128 / 2), (128 / 3) * 1 + 5, id(roboto_24), id(my_yellow), TextAlign::CENTER, "%Y-%m-%d", id(esptime).now());
      it.strftime((128 / 2), (128 / 3) * 2 + 5, id(roboto_24), id(my_yellow), TextAlign::CENTER, "%H:%M:%S", id(esptime).now());

#G41=Button
binary_sensor:
  - platform: gpio
    name: Button
    pin:
      number: 41
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_off: 10ms
    on_press:
      then:
        - logger.log: Button Pressed