substitutions:
    devicename: vvb-temp

esphome:
  comment: "VVB Temperatur"
  name: $devicename
  friendly_name: $devicename
  platformio_options:
    board_build.flash_mode: dio
    board_build.f_cpu: 80000000L
  on_boot:
    - priority: 90
      then:
        - output.turn_on: bme280_supply

esp32:
  board: esp32-c3-devkitm-1
  variant: ESP32C3
  framework:
    type: esp-idf
    version: recommended
    # Custom sdkconfig options
    sdkconfig_options:
      COMPILER_OPTIMIZATION_SIZE: y
    # Advanced tweaking options
    advanced:
      ignore_efuse_mac_crc: false

preferences:
    flash_write_interval: 5s

output:
  - platform: gpio
    pin: GPIO0
    id: bme280_supply
  - platform: gpio
    pin: GPIO1
    id: bme280_gnd

i2c:
  scl: GPIO9
  sda: GPIO8
  scan: True
  frequency: 100kHz

# Enable logging
logger:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable Home Assistant API
api:
  encryption:
    key: "STZYV4y69HgqLizY6PkQ+lSzcB7zqyWdLt+TdYvtSQg="

esp32_ble_tracker:
  scan_parameters:
    active: true

bluetooth_proxy:
  active: true

dallas:
  - pin: GPIO3
    update_interval: 30s

button:
    - platform: restart
      name: "Restart"
      device_class: "restart"

binary_sensor:
  - platform: status
    name: "Status"
    device_class: "connectivity"
    entity_category: "diagnostic"

sensor:
  - platform: dallas
    name: "Top Temperature"
    address: 0x1707235305e77e28
    id: dallas_flat
    device_class: temperature
  - platform: dallas
    name: "Bottom Temperature"
    address: 0x7ef0d9451f64ff28
    id: dallas_round
    device_class: temperature
  - platform: combination
    type: median
    name: "Mix Temperature"
    device_class: temperature
    sources:
      - source: dallas_flat
      - source: dallas_round

  - platform: bme280_i2c
    temperature:
      id: bme_temperature
      name: "Temperature"
      oversampling: 4x
    pressure:
      id: bme_pressure
      name: "Pressure"
      oversampling: 4x
    humidity:
      id: bme_humidity
      name: "Humidity"
      oversampling: 4x
    address: 0x76
    update_interval: 30s

  - platform: wifi_signal
    name: "WiFi Signal dB"
    update_interval: 60s
    device_class: "signal_strength"
    entity_category: "diagnostic"