labels: [esp32]
---

# Pins for this model
packages:
  pins: !include pins/esp32_cam_ov5640.yaml
  i2c: !include extension/internal_i2c.yaml

substitutions:
  device:
    model: "ESP32_CAM ov5640"
    rmt_symbols_block: 64
    framework:
      type: esp-idf
  extension:
    i2c:
      internal:
        frequency: 200kHz

esp32:
# ESP32-WROOM-32
  variant: esp32
  flash_size: 4MB
  cpu_frequency: 240MHz
  framework: 
    type: ${device.framework.type}
    advanced:
      compiler_optimization: PERF
      sram1_as_iram: true
      enable_idf_experimental_features: true
    sdkconfig_options:
      CONFIG_ESP32_SPIRAM_SUPPORT: y
      # CONFIG_ESP32_SPIRAM_SPEED_40M: y
      CONFIG_COMPILER_OPTIMIZATION_PERF: y
      CONFIG_ESP32_DEFAULT_CPU_FREQ_240: y
      CONFIG_SPIRAM_ALLOW_STACK_EXTERNAL_MEMORY: "y"
      CONFIG_SPIRAM_TRY_ALLOCATE_WIFI_LWIP: "y"
      # CONFIG_BT_ALLOCATION_FROM_SPIRAM_FIRST: "y"
      # CONFIG_BT_BLE_DYNAMIC_ENV_MEMORY: "y"
      CONFIG_MBEDTLS_EXTERNAL_MEM_ALLOC: "y"
      CONFIG_MBEDTLS_SSL_PROTO_TLS1_3: "y"
      CONFIG_FATFS_LFN_STACK: "y"  # to support long file name in sdcard
      CONFIG_TASK_WDT: "y"  # prevents watchdog timeouts
      CONFIG_TASK_WDT_TIMEOUT_S: "30"  # prevents watchdog timeouts
      CONFIG_TASK_WDT_CHECK_IDLE_TASK_CPU0: "n"  # prevents watchdog timeouts
      # ## needed by new jpeg camera : https://github.com/esphome/esphome/pull/9496
      CONFIG_SPIRAM_SUPPORT: y
      CONFIG_SPIRAM_USE_CAPS_ALLOC: y
      CONFIG_SPIRAM_USE_MALLOC: y
      CONFIG_LOG_DEFAULT_LEVEL: "0"  # prevents "ESP-IDF" Guru Meditation Error
      CONFIG_CAMERA_TASK_STACK_SIZE: "8192"

esphome:
  project:
    name: "ESP32_CAM.ov5640"
    version: "1.0.0"
  platformio_options:
    board_build.extra_flags:
      - -DBOARD_HAS_PSRAM
      - -DTF_LITE_STATIC_MEMORY  # for tflite micro
      - -DTF_LITE_DISABLE_X86_NEON  #for tflite micro
      - -DESP_NN  #use hardware acceleration : https://github.com/espressif/esp-nn (only if using tflite)

psram:

wifi:
  enable_btm: true
  enable_rrm: true

esp32_camera:
  i2c_id: i2c_internal
  # PINS
  external_clock:
    pin:
      number: ${pin.cam.m_clk}
      ignore_strapping_warning: true
    frequency: 20MHz
  data_pins:
    - number: ${pin.cam.y2}
      ignore_strapping_warning: true
    - ${pin.cam.y3}
    - ${pin.cam.y4}
    - number: ${pin.cam.y5}
      ignore_strapping_warning: true
    - ${pin.cam.y6}
    - ${pin.cam.y7}
    - ${pin.cam.y8}
    - ${pin.cam.y9}
  vsync_pin: ${pin.cam.vs}
  href_pin: ${pin.cam.hs}
  pixel_clock_pin: ${pin.cam.p_clk}
  reset_pin:
    number: ${pin.cam.rst}
    ignore_strapping_warning: true
  # Metadata
  id: espcam
  name: "Camera"
  # Image settings
  resolution: 1024x768
  jpeg_quality: 15
  max_framerate: 1 fps
  frame_buffer_count: 2 # defaults to 1 (1-2)
  vertical_flip: true
  horizontal_mirror: true
  # Exposure
  aec_mode: auto
  aec2: true # defaults to false
  # White balance
  wb_mode: auto

status_led:
  pin: ${pin.light.led}
