---
# https://www.waveshare.com/wiki/E-Paper_ESP32_Driver_Board
# Base functions for Waveshare e-paper ESP32 driver board
#

# Pins for this model
packages:
  pins: !include pins/esp32doit-devkit-v1.yaml

substitutions:
  device:
    framework:
      type: esp-idf

esp32:
  board: esp32doit-devkit-v1
  framework: 
    type: ${device.framework.type}

wifi:
  enable_btm: true
  enable_rrm: true
