# Personal settings for Everything Presence Lite

esp32:
  framework:
    advanced:
      assertion_level: DISABLE

api:
  reboot_timeout: 90min
  encryption:
    key: !secret homeassistant_api

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 30min
  fast_connect: true
  passive_scan: true
  enable_btm: true
  enable_rrm: true

binary_sensor:
  - id: !extend zone2_occupancy
    disabled_by_default: false
  - id: !extend zone3_occupancy
    disabled_by_default: false
  - id: !extend zone4_occupancy
    disabled_by_default: false

number:
  - id: !extend zone1_begin_x
    entity_category: config
  - id: !extend zone1_end_x
    entity_category: config
  - id: !extend zone1_begin_y
    entity_category: config
  - id: !extend zone1_end_y
    entity_category: config
  - id: !extend zone_1_off_delay
    entity_category: config

  - id: !extend zone2_begin_x
    disabled_by_default: false
    entity_category: config
  - id: !extend zone2_end_x
    disabled_by_default: false
    entity_category: config
  - id: !extend zone2_begin_y
    disabled_by_default: false
    entity_category: config
  - id: !extend zone2_end_y
    disabled_by_default: false
    entity_category: config
  - id: !extend zone_2_off_delay
    disabled_by_default: false
    entity_category: config

  - id: !extend zone3_begin_x
    disabled_by_default: false
    entity_category: config
  - id: !extend zone3_end_x
    disabled_by_default: false
    entity_category: config
  - id: !extend zone3_begin_y
    disabled_by_default: false
    entity_category: config
  - id: !extend zone3_end_y
    disabled_by_default: false
    entity_category: config
  - id: !extend zone_3_off_delay
    disabled_by_default: false
    entity_category: config

  - id: !extend zone4_begin_x
    disabled_by_default: false
    entity_category: config
  - id: !extend zone4_end_x
    disabled_by_default: false
    entity_category: config
  - id: !extend zone4_begin_y
    disabled_by_default: false
    entity_category: config
  - id: !extend zone4_end_y
    disabled_by_default: false
    entity_category: config
  - id: !extend zone_4_off_delay
    disabled_by_default: false
    entity_category: config

sensor:
  - id: !extend target1_x
    entity_category: diagnostic
  - id: !extend target1_y
    entity_category: diagnostic
  - id: !extend target1_speed
    disabled_by_default: true
    entity_category: diagnostic
  - id: !extend target1_resolution
    disabled_by_default: true
    entity_category: diagnostic
  - id: !extend target1_angle
    disabled_by_default: true
    entity_category: diagnostic
  - id: !extend target1_distance
    entity_category: diagnostic

  - id: !extend target2_x
    entity_category: diagnostic
  - id: !extend target2_y
    entity_category: diagnostic
  - id: !extend target2_speed
    disabled_by_default: true
    entity_category: diagnostic
  - id: !extend target2_resolution
    disabled_by_default: true
    entity_category: diagnostic
  - id: !extend target2_angle
    disabled_by_default: true
    entity_category: diagnostic
  - id: !extend target2_distance
    entity_category: diagnostic

  - id: !extend target3_x
    entity_category: diagnostic
  - id: !extend target3_y
    entity_category: diagnostic
  - id: !extend target3_speed
    disabled_by_default: true
    entity_category: diagnostic
  - id: !extend target3_resolution
    disabled_by_default: true
    entity_category: diagnostic
  - id: !extend target3_angle
    disabled_by_default: true
    entity_category: diagnostic
  - id: !extend target3_distance
    entity_category: diagnostic

  - id: !extend zone1_target_count
    entity_category: diagnostic
  - id: !extend zone2_target_count
    disabled_by_default: false
    entity_category: diagnostic
  - id: !extend zone3_target_count
    disabled_by_default: false
    entity_category: diagnostic
  - id: !extend zone4_target_count
    disabled_by_default: false
    entity_category: diagnostic

select:
  - id: !extend tracking_behaviour
    initial_option: Above + Speed and Resolution
