---
# https://community.home-assistant.io/t/installing-esphome-on-geekmagic-smart-weather-clock-smalltv-pro/618029/156
# Base functions for:
# GeekMagic SmallTV S3
#

# Pins for this model
packages:
  pins: !include pins/geekmagic_smalltv_s3.yaml

substitutions:
  device:
    framework:
      type: esp-idf

esphome:
  project:
    name: "GeekMagic.SmallTV S3"
  platformio_options:
#    board_build.arduino.memory_type: qio #https://github.com/GeekMagicClock/GeekMagic-S3/pull/8
    board_build.arduino.memory_type: qio_opi # https://community.home-assistant.io/t/installing-esphome-on-geekmagic-smart-weather-clock-smalltv-pro/618029/156
    board_build.flash_mode: dio # HA Forum
#    board_build.flash_mode: qio # AliExpress review
    board_build.psram_type: opi # AliExpress review
    board_upload.maximum_ram_size: 524288
    build_flags:
#      - "-w" # https://docs.platformio.org/en/latest/projectconf/sections/env/options/build/build_flags.html
      - "-DBOARD_HAS_PSRAM"
#      - "-DARDUINO_USB_CDC_ON_BOOT=0"
#      - "-DARDUINO_USB_CDC_ON_BOOT=1"
#      - "-mfix-esp32-psram-cache-issue"

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 16MB
#  partitions: partitions/gm-s3-16MB.csv
  framework:
    type: ${device.framework.type}
    advanced:
      compiler_optimization: PERF

psram:
  mode: octal
  speed: 80MHz

spi:
  clk_pin: ${pin.spi.clk}
  mosi_pin: ${pin.spi.mosi}
#  interface: hardware

output:
  - platform: ledc
    id: backlight_output
    pin: ${pin.light.disp_bl}
    inverted: true

light:
  - platform: monochromatic
    id: backlight_light
    output: backlight_output
    default_transition_length: 250ms
    restore_mode: RESTORE_AND_ON
    initial_state:
      state: on
      brightness: 25%
    name: "Backlight"
    entity_category: config

# Button
esp32_touch:
  #setup_mode: True
  measurement_duration: 0.25ms

binary_sensor:
  - platform: esp32_touch
    id: touch_pad
    pin: ${pin.btn.touch}
    threshold: 130000
    filters:
      # Small filter, to debounce the spurious events.
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_press:
      - logger.log: "Short Touch"
#    on_click:
#    - min_length: 50ms
#      max_length: 500ms
#      then:
#        - lvgl.page.next:
#            animation: MOVE_LEFT
#            time: 300ms
#        - logger.log: "Short Touch"
#    - min_length: 500ms
#      max_length: 2000ms
#      then:
#        - if:
#            condition:
#            - light.is_off: backlight_light
#            then:
#            - light.turn_on: 
#                id: backlight_light
#        - if:
#            condition:
#            - light.is_on: backlight_light
#            then:
#            - lvgl.widget.redraw
#        - logger.log: "Long Touch"
    name: "Touchpad"
    entity_category: diagnostic

display:
  - platform: ili9xxx
    id: display_lcd
    model: st7789v #gc9a01a
    #data_rate: 40MHz
    #cs_pin: ${pin.spi.disp.cs}
    dc_pin: ${pin.spi.disp.dc}
    reset_pin: ${pin.spi.disp.reset}
    spi_mode: MODE3
    dimensions:
      width: 240
      height: 240
    invert_colors: true
    auto_clear_enabled: false
    update_interval: never
