---
# PINs for Sunton module ESP32-S3 with Guition 3.5" display
#

# Pins for this model
packages:
  pins: !include pins/jc3248w535c.yaml

esphome:
  project:
    name: 'Sunton.3,5" 320x480'

esp32:
  board: esp32s3box
  variant: ESP32S3
  flash_size: 16MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: y
      CONFIG_ESP32S3_DATA_CACHE_64KB: y
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: y
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y
    advanced:
      compiler_optimization: PERF

wifi:
  enable_btm: true
  enable_rrm: true

psram:
  mode: octal
  speed: 80MHz

# https://community.home-assistant.io/t/jc3248w535-guition-3-5-config/791363
spi:
  - type: quad
    clk_pin: ${spi_clk_pin}
    data_pins: [$spi_data1_pin, $spi_data2_pin, $spi_data3_pin, $spi_data4_pin]

i2c:
  - id: i2c_internal
    sda: ${i2c_int_sda_pin}
    scl: ${i2c_int_scl_pin}

output:
  - platform: ledc
    id: backlight_output
    pin: ${disp_bl_pin}

light:
  # White
  - platform: monochromatic
    id: backlight_light
    output: backlight_output
    default_transition_length: 100ms
    restore_mode: RESTORE_AND_ON
    initial_state:
      state: on
      brightness: 25%
    name: "Backlight"
    entity_category: config

display:
  - platform: qspi_dbi
    id: display_lcd
    dimensions:
      height: 480
      width: 320
    model: JC4832W535
    data_rate: 40MHz
    cs_pin:
      number: ${disp_cs_pin}
      ignore_strapping_warning: true
    draw_from_origin: true
    update_interval: 5s
    auto_clear_enabled: false

touchscreen:
  - platform: axs15231
    i2c_id: i2c_internal
    id: touchscreen_axs
    # https://community.home-assistant.io/t/esp32-s3-3-5-inch-capacitive-touch-ips-module-320-480/768591/73
    calibration:
      x_min: 0
      x_max: 320
      y_min: 0
      y_max: 480
    transform:
      swap_xy: false   # 0=false, 90=true, 180=false, 270=true
      mirror_x: false  # 0=false, 90=true, 180=true, 270=false
      mirror_y: false   # 0=false, 90=false, 180=true, 270=true
#    on_update:
#      - logger.log:
#          format: Touch %d at (%d, %d)
#          args: [ 'touch->id', 'touch->x', 'touch->y' ]