labels: [esp32s3, psram, JC4832W535, display, i2c]
---
# PINs for Sunton module ESP32-S3 with Guition 3.5" display
#

# Pins for this model
packages:
  pins: !include pins/jc3248w535c.yaml

substitutions:
  device:
    model: 'Sunton 3,5"'
    rmt_symbols_block: 48
    framework:
      type: esp-idf

esphome:
  project:
    name: 'Sunton.3,5" 320x480'

esp32:
# ESP32-S3R8 (Dual-core, 240MHz)
# PSRAM: 8MB Octal
  variant: esp32s3
  flash_size: 16MB
  cpu_frequency: 240MHz
  framework:
    advanced:
      compiler_optimization: PERF
      execute_from_psram: true
    sdkconfig_options:
      # Cache optimizations
      CONFIG_ESP32S3_DATA_CACHE_64KB: y
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: y
      CONFIG_ESP32S3_INSTRUCTION_CACHE_32KB: y
      # Memory allocation for large RGB graphics buffers
      CONFIG_SPIRAM_USE_CAPS_ALLOC: y
      CONFIG_SPIRAM_USE_MALLOC: y
    type: ${device.framework.type}

psram:
  mode: octal
  speed: 80MHz

wifi:
  enable_btm: true
  enable_rrm: true

# https://community.home-assistant.io/t/jc3248w535-guition-3-5-config/791363
spi:
  - type: quad
    clk_pin: ${pin.int.spi.clk}
    data_pins:
      - ${pin.int.spi.dat1}
      - ${pin.int.spi.dat2}
      - ${pin.int.spi.dat3}
      - ${pin.int.spi.dat4}

i2c:
  - id: i2c_internal
    sda: ${pin.int.i2c.sda}
    scl: ${pin.int.i2c.scl}

output:
  - platform: ledc
    id: backlight_output
    pin: ${pin.light.disp_bl}

light:
  # White
  - platform: monochromatic
    id: backlight_light
    output: backlight_output
    default_transition_length: 100ms
    restore_mode: RESTORE_AND_ON
    initial_state:
      state: on
      brightness: 25%
    name: "Backlight"
    entity_category: config

display:
  - platform: qspi_dbi
    id: display_lcd
    model: JC4832W535
    cs_pin:
      number: ${pin.int.spi.disp.cs}
      ignore_strapping_warning: true
    dimensions:
      height: 480
      width: 320
    data_rate: 40MHz
    draw_from_origin: true
    auto_clear_enabled: false
    update_interval: 10s

touchscreen:
  - platform: axs15231
    i2c_id: i2c_internal
    id: touchscreen_axs
    # https://community.home-assistant.io/t/esp32-s3-3-5-inch-capacitive-touch-ips-module-320-480/768591/73
    calibration:
      x_min: 0
      x_max: 320
      y_min: 0
      y_max: 480
    transform:
      swap_xy: false   # 0=false, 90=true, 180=false, 270=true
      mirror_x: false  # 0=false, 90=true, 180=true, 270=false
      mirror_y: false   # 0=false, 90=false, 180=true, 270=true
#    on_update:
#      - logger.log:
#          format: Touch %d at (%d, %d)
#          args: [ 'touch->id', 'touch->x', 'touch->y' ]
