labels: [esp32s3, psram, ST7789V, display, MPU6886]
---
# https://docs.m5stack.com/en/core/AtomS3
# Base functions for:
# M5Stack AtomS3
#

# Pins for this model
packages:
  pins: !include pins/m5stack_atom_s3.yaml

substitutions:
  device:
    model: "M5Stack Atom S3"
    rmt_symbols_block: 48 
    framework:
      type: esp-idf

esphome:
  project:
    name: "M5Stack.Atom S3"

esp32:
# ESP32-S3FN8
  variant: esp32s3
  flash_size: 8MB
  cpu_frequency: 240MHz
  framework:
    advanced:
      compiler_optimization: PERF
    sdkconfig_options:
      # Cache optimizations for reading graphics/fonts directly from Flash
      CONFIG_ESP32S3_DATA_CACHE_64KB: y
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: y
      CONFIG_ESP32S3_INSTRUCTION_CACHE_32KB: y
    type: ${device.framework.type}

wifi:
  enable_btm: true
  enable_rrm: true

spi:
  clk_pin: ${pin.int.spi.clk}
  mosi_pin: ${pin.int.spi.mosi}

output:
  - platform: ledc
    id: backlight_output
    pin: ${pin.light.disp_bl}
    frequency: 500Hz
    min_power: 0.2
    max_power: 1.0
    zero_means_zero: true

light:
  # White
  - platform: monochromatic
    id: backlight_light
    output: backlight_output
    default_transition_length: 100ms
    restore_mode: RESTORE_AND_ON
    initial_state:
      state: on
      brightness: 25%
    name: "Backlight"
    entity_category: config

display:
  - platform: mipi_spi
    model: st7789v
    id: display_lcd
    cs_pin: ${pin.int.spi.disp.cs}
    dc_pin: ${pin.int.spi.disp.dc}
    reset_pin: ${pin.int.spi.disp.reset}
    data_rate: 40Mhz
    invert_colors: true
    update_interval: 10s
    auto_clear_enabled: false
    dimensions:
      height: 128
      width: 128
      offset_width: 2     
      offset_height: 1
      pad_width: 2
      pad_height: 1

# Button
binary_sensor:
  - platform: gpio
    id: btn_display
    pin:
      number: ${pin.btn}
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_off: 10ms
    on_press:
      - logger.log: Button Pressed
    name: Button
    entity_category: diagnostic

#sensor:
    # MPU6886 IMU
#  - platform: mpu6886
#    i2c_id: i2c_internal
#    id: mpu6886_sensor
#    accel_x:
#      id: mpu6886_accel_x
#      name: "MPU6886 Accel X"
#      disabled_by_default: true
#      filters:
#        - sliding_window_moving_average:
#            window_size: 3
#            send_every: 2
#    accel_y:
#      id: mpu6886_accel_y
#      name: "MPU6886 Accel Y"
#      disabled_by_default: true
#      filters:
#        - sliding_window_moving_average:
#            window_size: 3
#            send_every: 2
#    accel_z:
#      id: mpu6886_accel_z
#      name: "MPU6886 Accel z"
#      disabled_by_default: true
#      filters:
#        - sliding_window_moving_average:
#            window_size: 3
#            send_every: 2
#    gyro_x:
#      id: mpu6886_gyro_x
#      name: "MPU6886 Gyro X"
#      disabled_by_default: true
#      filters:
#        - sliding_window_moving_average:
#            window_size: 3
#            send_every: 2
#    gyro_y:
#      id: mpu6886_gyro_y
#      name: "MPU6886 Gyro Y"
#      disabled_by_default: true
#      filters:
#        - sliding_window_moving_average:
#            window_size: 3
#            send_every: 2
#    gyro_z:
#      id: mpu6886_gyro_z
#      name: "MPU6886 Gyro z"
#      disabled_by_default: true
#      filters:
#        - sliding_window_moving_average:
#            window_size: 3
#            send_every: 2
#    temperature:
#      id: mpu6886_temperature
#      name: "MPU6886 Temperature"
#      disabled_by_default: true
#      filters:
#        - sliding_window_moving_average:
#            window_size: 6
#            send_every: 3

# IR
#remote_transmitter:
#  pin: ${pin.light.ir}
#  carrier_duty_percent: 50%
#  rmt_symbols: ${device.rmt_symbols_block}
