---
# https://docs.m5stack.com/en/core/AtomS3%20Lite
# Base functions for:
# M5Stack AtomS3 Lite
#

# Pins for this model
packages:
  pins: !include pins/m5stack_atom_s3_lite.yaml

esp32:
  board: m5stack-atoms3
  variant: esp32s3

# Output that blinks the LED
#output:
#  - platform: template
#    id: status_output
#    type: binary
#    write_action:
#    - if:
#        condition:
#          lambda: return (state);
#        then:
#          - light.turn_on:
#              id: led
#              transition_length: 50ms
#              brightness: 30%
#              red: 100%
#              green: 0%
#              blue: 0%
#        else:
#          - light.turn_off:
#              id: led
#              transition_length: 50ms

#G4=IR
#remote_transmitter:
#  pin: $ir_pin
#  carrier_duty_percent: 50%
#  rmt_symbols: 144

light:
  # Enable status LED
#  - platform: status_led
#    output: status_output
#    name: "Status Led"
#    internal: True

  #G35=RGB WS2812C-2020
  - platform: esp32_rmt_led_strip
    id: led
    rgb_order: GRB
    pin: $rgb_pin
    num_leds: 4
    # RMT 0 channels will be occupied by IR
#    rmt_channel: 1
    rmt_symbols: 384
    chipset: ws2812
    effects:
      - pulse:
      - strobe:
      - addressable_flicker:
      - addressable_rainbow:
      - addressable_color_wipe:
      - addressable_scan:
      - addressable_twinkle:
    default_transition_length: 50ms
    name: "LED"
    entity_category: config
  - platform: partition
    id: led1
    segments: 
      id: led
      from: 0
      to: 1
#  - platform: partition
#    id: led2
#    segments: 
#      id: led
#      from: 1
#      to: 1
#  - platform: partition
#    id: led3
#    segments: 
#      id: led
#      from: 2
#      to: 2
  - platform: partition
    id: led4
    segments: 
      id: led
      from: 2
      to: 3

#G41=Button
binary_sensor:
  - platform: gpio
    name: Button
    entity_category: diagnostic
    pin:
      number: $button_pin
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_off: 10ms
    on_press:
      then:
        - logger.log: Button Pressed
        - script.execute: led_wifi
        - script.wait: led_wifi
        - delay: 1500ms
        - script.execute: led_homeassistant
        - script.wait: led_homeassistant

# Script for status LED
script:
  - id: led_wifi
    then:
      - if:
          condition:
            light.is_off: led1
          then:
            - if:
                condition:
                  wifi.connected:
                then:
                  - light.addressable_set:
                      id: led
                      range_from: 0
                      range_to: 1
                      color_brightness: 10%
                      red: 0%
                      green: 100%
                      blue: 0%
                  - delay: 250ms
                else:
                  - light.addressable_set:
                      id: led
                      range_from: 0
                      range_to: 1
                      color_brightness: 0%
                      red: 0%
                      green: 0%
                      blue: 0%
          else:
            - light.turn_off:
                id: led1
  - id: led_homeassistant
    then:
      - if:
          condition:
            light.is_off: led4
          then:
            - if:
                condition:
                  api.connected:
                then:
                  - light.addressable_set:
                      id: led
                      range_from: 2
                      range_to: 3
                      color_brightness: 10%
                      red: 0%
                      green: 0%
                      blue: 100%
                  - delay: 250ms
                else:
                  - light.addressable_set:
                      id: led
                      range_from: 2
                      range_to: 3
                      color_brightness: 0%
                      red: 0%
                      green: 0%
                      blue: 0%
          else:
            - light.turn_off:
                id: led4
