---
# https://docs.m5stack.com/en/core/ATOM%20Lite
# Base functions for:
# M5Stack Atom Lite
#

substitutions:
  device:
    framework:
      type: esp-idf

# Pins for this model
packages:
  pins: !include pins/m5stack_atom_lite.yaml
  status_led: !include ../features/system_status_led.yaml

esphome:
  project:
    name: "M5Stack.Atom Lite"

esp32:
  board: m5stack-atom
  framework:
    type: ${device.framework.type}

wifi:
  enable_btm: true
  enable_rrm: true

# Output that blinks the LED
#output:
#  - platform: template
#    id: status_output
#    type: binary
#    write_action:
#    - if:
#        condition:
#          lambda: return (state);
#        then:
#          - light.turn_on:
#              id: rgb_led
#              transition_length: 50ms
#              brightness: 30%
#              red: 100%
#              green: 0%
#              blue: 0%
#        else:
#          - light.turn_off:
#              id: rgb_led
#              transition_length: 50ms

# IR
#remote_transmitter:
#  pin: $ir_pin
#  carrier_duty_percent: 50%
#  rmt_symbols: 144

light:
  - platform: esp32_rmt_led_strip
    id: rgb_led
    rgb_order: GRB
    pin: ${pin.light.rgb}
    num_leds: 1
    rmt_symbols: 384
    chipset: sk6812
    effects:
      - pulse:
      - strobe:
      - strobe:
          name: "Slow Blink" # 200ms on, 1500ms off
          colors:
            - state: true
              brightness: 25%
              red: 100%
              green: 0%
              blue: 0%
              duration: 500ms
              transition_length: 500ms
            - state: false
              duration: 2000ms
              transition_length: 1000ms
    default_transition_length: 100ms
    initial_state:
      state: true
      brightness: 50%
      color_brightness: 100%
      red: 100%
      green: 0%
      blue: 0%
    name: "LED"
    entity_category: config

# Button
binary_sensor:
  - platform: gpio
    name: Button
    entity_category: diagnostic
    pin:
      number: ${pin.btn}
      inverted: true
    filters:
      - delayed_off: 10ms
    on_press:
      - logger.log: Button Pressed
    on_click:
      min_length: 1000ms
      max_length: 5000ms
      then:
        - logger.log: Button Held
        - light.turn_off:
            id: rgb_led

