---
# https://docs.m5stack.com/en/core/M5CoreS3%20SE
# Base functions for:
# M5Stack Core S3SE
#
# https://community.home-assistant.io/t/m5stack-m5cores3-se-with-microwakeword/761965/5
# https://github.com/luka6000/wake-word-voice-assistants/blob/main/m5stack-coreS3-se/m5stack-coreS3-se-spk.yaml

substitutions:
  time_timezone: "Europe/Oslo"
  mbus_i2c_shared: "false"
  internal_i2c_bus: i2c_internal

# Pins for this model
packages:
  pins: !include pins/m5stack_core_s3se.yaml

esphome:
  project:
    name: "M5Stack.Core S3 SE"
#  libraries:
#    - m5stack/M5GFX
#    - m5stack/M5Unified
  platformio_options:
    board_build.flash_mode: dio
    board_upload.maximum_size: 16777216

esp32:
#  board: m5stack-cores3
  board: esp32s3box
  variant: ESP32S3
  flash_size: 16MB
  framework:
    type: esp-idf
    advanced:
      compiler_optimization: PERF
    sdkconfig_options:
      CONFIG_ESP32_DEFAULT_CPU_FREQ_240: "y"

      # need to set a s3 compatible board for the adf-sdk to compile
      # board specific code is not used though
#      CONFIG_ESP32_S3_BOX_BOARD: "y"
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB:      "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B:  "y"

      CONFIG_ESP32_WIFI_STATIC_RX_BUFFER_NUM: "16"
      CONFIG_ESP32_WIFI_DYNAMIC_RX_BUFFER_NUM: "512"
      CONFIG_TCPIP_RECVMBOX_SIZE: "512"

      CONFIG_TCP_SND_BUF_DEFAULT: "65535"
      CONFIG_TCP_WND_DEFAULT: "512000"
      CONFIG_TCP_RECVMBOX_SIZE: "512"

wifi:
  enable_btm: true
  enable_rrm: true

psram:
  mode: quad
  speed: 80MHz

logger:
  deassert_rts_dtr: true

#i2c:
# Int
#  - id: i2c_internal
#    sda:
#      number: ${i2c_int_sda_pin}
#      allow_other_uses: ${mbus_i2c_shared}
#    scl:
#      number: ${i2c_int_scl_pin}
#      allow_other_uses: ${mbus_i2c_shared}
#    frequency: ${i2c_internal_frequency}
#    scan: true
# Ext PINs
#  - id: i2c_bus
#    sda: ${i2c_bus_sda_pin}
#    scl: ${i2c_bus_scl_pin}
#    frequency: 200kHz
#    scan: true

spi:
  clk_pin: ${spi_clk_pin}
  mosi_pin: ${spi_mosi_pin}

time:
  - platform: pcf8563
    i2c_id: ${internal_i2c_bus}
    id: time_rtc
    address: 0x51
    update_interval: 10min
#  - platform: sntp
#    id: sntp_time
#    timezone: $time_timezone
#    on_time_sync:
#      then:
#        pcf8563.write_time:

external_components:
#  - source:
#      type: git
#      url: https://github.com/DaAwesomeP/esphome_m5stack_core_s3
#      ref: DaAwesomeP_touch_interrupt_and_backlight
#    components: [ esp32_m5stack_core_s3, aw9523, axp2101 ]
#    refresh: 1d
  - source:
      type: git
      url: https://github.com/luka6000/esphome_m5stack_core_s3
      ref: v202502
      # type: local
      # path: ../../esphome_m5stack_core_s3/esphome/components/
    components: [ esp32_m5stack_core_s3, aw9523 ]
    refresh: 1d

esp32_m5stack_core_s3:
  i2c_id: ${internal_i2c_bus}

i2c_device:
  i2c_id: ${internal_i2c_bus}
  id: axp2101
  address: 0x34

#audio_adc:
#  - platform: es7210
#    i2c_id: i2c_internal
#    address: 0x40
#    id: adc_es7210
#    bits_per_sample: 16bit
#    sample_rate: 16000
#    mic_gain: 24

#i2s_audio:
#  - id: i2s_shared
#    i2s_lrclk_pin: ${i2s_lrclk_pin}
#    i2s_bclk_pin: ${i2s_bclk_pin}
#    i2s_mclk_pin: ${i2s_mclk_pin}

#microphone:
#  - platform: i2s_audio
#    i2s_audio_id: i2s_shared
#    id: microphone_i2s
#    i2s_din_pin: ${i2s_din_pin}
#    pdm: false
#    adc_type: external
#    sample_rate: 16000
#    bits_per_sample: 16bit
#    channel: right
#speaker:
#  - platform: i2s_audio
#    i2s_audio_id: i2s_shared
#    id: speaker_i2s
#    i2s_dout_pin: ${i2s_dout_pin}
#    dac_type: external
#    sample_rate: 16000
#    bits_per_sample: 16bit
#    channel: right

aw9523:
  i2c_id: ${internal_i2c_bus}
  id: aw9523_1
  address: 0x58

display:
  - platform: ili9xxx
    id: display_lcd
    model: M5Stack
    cs_pin: ${disp_cs_pin}
    dc_pin: ${disp_dc_pin}
    dimensions:
      height: 240
      width: 320
#      offset_height: 2
#      offset_width: 1
    # Rotate 180deg
#    transform:
#      mirror_x: true
#      mirror_y: true
    invert_colors: true
    color_palette: 8BIT
    reset_pin:
      aw9523: aw9523_1
      port: 1
      pin: 1
      mode:
        output: true
    update_interval: 5s
    auto_clear_enabled: false

touchscreen:
  - platform: ft63x6
    i2c_id: ${internal_i2c_bus}
    id: touchscreen_ft63x6
    update_interval: 20ms
#    interrupt_pin:
#      aw9523: aw9523_1
#      port: 1
#      pin: 2
#      mode:
#        input: true
#    reset_pin:
#      aw9523: aw9523_1
#      port: 0
#      pin: 0
#      mode:
#        output: true
    on_touch:
      - if:
          condition:
            - light.is_off: backlight_light
          then:
            - light.turn_on:
                id: backlight_light
                brightness: 40%
#    on_update:
#      - logger.log:
#          format: Touch %d at (%d, %d)
#          args: [ 'touch->id', 'touch->x', 'touch->y' ]

binary_sensor:
  - platform: touchscreen
    id: touch
    name: Touchscreen
    entity_category: diagnostic
    x_min: 0
    x_max: 320
    y_min: 0
    y_max: 240

output:
  - platform: template
    id: backlight_output
    type: float
    min_power: 0.20
    max_power: 0.28
    write_action:
      - lambda: >-
          uint8_t x = state * 100 ;
          id(axp2101).write_byte(0x99, x );

# https://devices.esphome.io/devices/M5Stack-Fire#wifi-issues-due-to-gpio15
#  - platform: gpio
#    id: wifi_fix_output
#    pin: ${mbus23}

light:
  # White
  - platform: monochromatic
    id: backlight_light
    output: backlight_output
    default_transition_length: 250ms
    restore_mode: RESTORE_AND_ON
    initial_state:
      state: on
      brightness: 25%
    name: "Backlight"
    entity_category: config
    # on_state:
    #   - lambda: |-
    #       uint8_t light;
    #       if (id(axp2101).read_byte(0x99, &light))
    #         id(backlight).turn_on().set_brightness( (( light << 5 ) - 641 ) /255 );
