---
# https://docs.m5stack.com/en/core/AtomS3R
# Base functions for:
# M5Stack AtomS3R
#

# Pins for this model
packages:
  pins: !include pins/m5stack_atom_s3r.yaml
  i2c_int: !include extension/internal_i2c.yaml

substitutions:
  device:
    framework:
      type: esp-idf

esphome:
  project:
    name: "M5Stack.Atom S3R"
  platformio_options:
    board_build.arduino.memory_type: qio_opi
    build_flags:
      - "-w" # https://docs.platformio.org/en/latest/projectconf/sections/env/options/build/build_flags.html
      - "-DBOARD_HAS_PSRAM"
      - "-DARDUINO_USB_CDC_ON_BOOT=1"
      - "-mfix-esp32-psram-cache-issue"

psram:
  mode: octal
  speed: 80MHz

esp32:
  board: m5stack-atoms3
  variant: esp32s3
  flash_size: 8MB
  framework:
    advanced:
      compiler_optimization: PERF
    type: ${device.framework.type}
#    version: 5.3.1
#    platform_version: 6.9.0
    # Custom sdkconfig options
    sdkconfig_options: # https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/kconfig.html#config-compiler-disable-gcc12-warnings
      CONFIG_SPIFFS_DBG: n

wifi:
  enable_btm: true
  enable_rrm: true

spi:
  clk_pin: ${pin.int.spi.clk}
  mosi_pin: ${pin.int.spi.mosi}

# IR
#remote_transmitter:
#  pin: ${pin.light.ir}
#  carrier_duty_percent: 50%
#  rmt_symbols: 144

external_components:
  - source:
      type: git
      url: https://github.com/ssieb/esphome
      ref: lp5562
    components: [ lp5562 ]
    refresh: 1d

# https://www.reddit.com/r/Esphome/comments/1geelgf/what_would_it_take_to_port_led_driver_lp5562/
lp5562:
  - i2c_id: i2c_internal

output:
  - platform: lp5562
    id: backlight_red
    channel: 0
  - platform: lp5562
    id: backlight_green
    channel: 1
  - platform: lp5562
    id: backlight_blue
    channel: 2
  - platform: lp5562
    id: backlight_white
    channel: 3

#switch:
#  - platform: gpio
#    id: backlight_white
#    pin: $backlight_pin
#    restore_mode: ALWAYS_ON
#    name: "Backlight"
#    entity_category: config

light:
  # White
  - platform: monochromatic
    id: backlight_light
    output: backlight_white
    restore_mode: RESTORE_DEFAULT_ON
    initial_state:
      state: on
      brightness: 25%
    default_transition_length: 50ms
    name: "Backlight"
    entity_category: config
  # RGBW
#  - platform: rgbw
#    id: backlight_light
#    red: backlight_red
#    green: backlight_green
#    blue: backlight_blue
#    white: backlight_white
#    color_interlock: true
#    default_transition_length: 100ms
#    restore_mode: ALWAYS_ON
#    name: "Backlight"
#    entity_category: config

# Button
binary_sensor:
  - platform: gpio
    id: btn_display
    pin:
      number: ${pin.btn}
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_off: 10ms
    on_press:
      - logger.log: Button Pressed
    name: Button
    entity_category: diagnostic

display:
  - platform: ili9xxx
    model: st7789v
    id: display_lcd
    cs_pin: ${pin.int.spi.disp.cs}
    dc_pin: ${pin.int.spi.disp.dc}
    reset_pin: ${pin.int.spi.disp.reset}
    data_rate: 40Mhz
    invert_colors: true
    update_interval: 5s
    dimensions:
      height: 128
      width: 128
      offset_height: 2
      offset_width: 1
    # Rotate 180deg
    transform:
      mirror_x: false
      mirror_y: false