---
# https://docs.m5stack.com/en/core/Atom-Matrix_v1.1
# Base functions for:
# M5Stack Atom Matrix v1.1
#

substitutions:
  device:
    model: "M5Stack Atom Matrix"
    rmt_symbols_block: 64
    framework:
      type: esp-idf

# Pins for this model
packages:
  pins: !include pins/m5stack_atom_lite.yaml

esphome:
  project:
    name: "M5Stack.Atom Matrix"

esp32:
# ESP32-PICO-D4@Dual-core processor, 240MHz
  variant: esp32
  flash_size: 4MB
  cpu_frequency: 240MHz
  framework:
    type: ${device.framework.type}
    advanced:
      compiler_optimization: PERF
      sram1_as_iram: true

wifi:
  enable_btm: true
  enable_rrm: true

light:
  - platform: esp32_rmt_led_strip
    id: rgb_led
    rgb_order: GRB
    pin: ${pin.light.rgb}
    num_leds: 25
    rmt_symbols: ${device.rmt_symbols_block * 2}
    chipset: ws2812
    color_correct: [35%, 35%, 35%]
    effects:
      - pulse:
      - strobe:
      - strobe:
          name: "Slow Blink" # 200ms on, 1500ms off
          colors:
            - state: true
              brightness: 25%
              red: 100%
              green: 0%
              blue: 0%
              duration: 500ms
              transition_length: 500ms
            - state: false
              duration: 2000ms
              transition_length: 1000ms
    default_transition_length: 50ms
    restore_mode: ALWAYS_OFF
    name: "LED"
    on_turn_on:
      lambda: |-
        id(display_matrix)->set_enabled(false);
    on_turn_off:
      lambda: |-
        id(display_matrix)->set_enabled(true);

display:
  - platform: addressable_light
    addressable_light_id: rgb_led
    id: display_matrix
    width: 5
    height: 5
    pages:
      - id: page_blank
        lambda: |-
          it.fill(COLOR_OFF);
          it.draw_pixel_at(1, 2, c_red);
          it.draw_pixel_at(3, 2, c_darkorange);
          // Show wifi icon.
          if ( id(component_wifi).is_connected() ) {
            it.draw_pixel_at(1, 2, c_green);
          }
          // Show HA icon.
          if ( id(component_api).is_connected() ) {
            it.draw_pixel_at(3, 2, c_aquamarine);
          }
      - id: page_colors
        lambda: |-
          it.draw_pixel_at(0, 0, c_red);
          it.draw_pixel_at(0, 1, c_green);
          it.draw_pixel_at(0, 2, c_blue);
          it.draw_pixel_at(0, 4, c_white);
          it.draw_pixel_at(1, 4, c_cyan);
          it.draw_pixel_at(1, 3, c_magenta);
          it.draw_pixel_at(1, 2, c_yellow);
          it.draw_pixel_at(1, 0, c_white);
          it.draw_pixel_at(3, 0, c_gold);
          it.draw_pixel_at(3, 1, c_orange);
          it.draw_pixel_at(3, 2, c_darkorange);
          it.draw_pixel_at(3, 3, c_orangered);
          it.draw_pixel_at(3, 4, c_hotpink);
          it.draw_pixel_at(4, 4, c_slateblue);
          it.draw_pixel_at(4, 3, c_deepskyblue);
          it.draw_pixel_at(4, 2, c_aquamarine);
          it.draw_pixel_at(4, 1, c_springgreen);
          it.draw_pixel_at(4, 0, c_chartreuse);

# Button
binary_sensor:
  - platform: gpio
    id: btn_matrix
    name: Button
    entity_category: diagnostic
    pin:
      number: ${pin.btn}
      inverted: true
    filters:
      - delayed_off: 10ms
    on_press:
      - logger.log: Button Pressed
      - display.page.show_next: display_matrix
    on_click:
      min_length: 1000ms
      max_length: 5000ms
      then:
        - logger.log: Button Held
        - light.toggle: rgb_led

font:
  - file: "gui/fonts/5x5-monospaced.ttf"
    id: font_5x5
    size: 5

color:
  - id: c_red
    red: 100%
    green: 0%
    blue: 0%
  - id: c_green
    red: 0%
    green: 100%
    blue: 0%
  - id: c_blue
    red: 0%
    green: 0%
    blue: 100%
  - id: c_cyan
    red: 0%
    green: 100%
    blue: 100%
  - id: c_magenta
    red: 100%
    green: 0%
    blue: 100%
  - id: c_yellow
    red: 100%
    green: 100%
    blue: 0%
  - id: c_white
    red: 100%
    green: 100%
    blue: 100%

  - id: c_gold
    red: 100%
    green: 84%
    blue: 0%
  - id: c_orange
    red: 100%
    green: 55%
    blue: 0%
  - id: c_orangered
    red: 100%
    green: 27%
    blue: 0%
  - id: c_darkorange
    red: 100%
    green: 55%
    blue: 0%
  - id: c_hotpink
    red: 100%
    green: 41%
    blue: 71%
  - id: c_slateblue
    red: 48%
    green: 41%
    blue: 93%
  - id: c_deepskyblue
    red: 0%
    green: 75%
    blue: 100%
  - id: c_aquamarine
    red: 50%
    green: 100%
    blue: 83%
  - id: c_springgreen
    red: 0%
    green: 100%
    blue: 50%
  - id: c_chartreuse
    red: 50%
    green: 100%
    blue: 0%
