---
# https://docs.m5stack.com/en/core/M5StickC%20PLUS2
# https://devices.esphome.io/devices/M5Stack-M5StickC-PLUS2
# Base functions for:
# M5Stack StickC Plus2
#

# HAT and Mic shared pins
substitutions:
  hat_shared: "false"
  grove_shared: "false"

# Pins for this model
packages:
  pins: !include pins/m5stack_stickc_plus2.yaml

esp32:
#  board: m5stick-c
  board: esp32-pico-devkitm-2
  flash_size: 8MB
  framework:
    advanced:
      compiler_optimization: PERF
    type: esp-idf

esphome:
  project:
    name: "M5Stack.StickC Plus2"
  platformio_options:
#    board_build.arduino.partitions: default_8MB.csv
#    board_build.f_flash: 80000000L
    build_flags:
      - "-w" # https://docs.platformio.org/en/latest/projectconf/sections/env/options/build/build_flags.html
      - "-DBOARD_HAS_PSRAM"
      - "-DARDUINO_USB_CDC_ON_BOOT=1"
      - "-mfix-esp32-psram-cache-issue"
  on_boot:
    - priority: 800
      then:
        # Bypass sleep circuit arduino
  #      - lambda: |-
  #          pinMode(GPIO_NUM_4, OUTPUT);
  #          digitalWrite(GPIO_NUM_4, HIGH);
  #          gpio_hold_en(GPIO_NUM_4);
        # Bypass sleep circuit esp-idf
        - lambda: |-
            gpio_set_direction(GPIO_NUM_4, GPIO_MODE_OUTPUT);
            gpio_set_level(GPIO_NUM_4, 1);
            gpio_hold_en(GPIO_NUM_4);
            gpio_deep_sleep_hold_en();

wifi:
  enable_btm: true
  enable_rrm: true

psram:
  mode: quad
  speed: 80MHz

spi:
  clk_pin: ${spi_clk_pin}
  mosi_pin: ${spi_mosi_pin}

light:
  # Enable status LED
  - platform: status_led
    id: status_light
    pin: ${led_pin}
  # TFT Backlight
  - platform: monochromatic
    output:  backlight_output
    id: backlight_light
    default_transition_length: 100ms
    restore_mode: RESTORE_AND_ON
    initial_state:
      state: on
      brightness: 25%
    name: "Backlight"
    entity_category: config

output:
  # Buzzer
  - platform: ledc
    id: buzzer
    pin: ${buzzer_pin}
  # TFT Backlight
  - platform: ledc
    id: backlight_output
    pin: ${disp_bl_pin}
    frequency: 256Hz
    channel: 7
    min_power: 15%
    zero_means_zero: true
#  - platform: gpio
#    id: power_hold
#    pin:
#      number: ${pwr_mos_pin}
#      allow_other_uses: true

# 1.14 inch, 135*240 Colorful TFT LCD, ST7789v2
display:
  - platform:  ili9xxx
    model: st7789v
    id: display_lcd
    cs_pin: ${disp_cs_pin}
    dc_pin: ${disp_dc_pin}
    reset_pin: ${disp_reset_pin}
    invert_colors: true
    update_interval: 5s
    dimensions:
      height: 240
      width: 135
      offset_height: 40
      offset_width: 52
    # Rotate 270 swap dimensions
#      height: 135
#      width: 240
#      offset_height: 52
#      offset_width: 40
#    transform:
#      swap_xy: true
#      mirror_y: true

binary_sensor:
  # Side Button
  - platform: gpio
    id: button_side
    pin:
      number: ${button_side_pin}
      allow_other_uses: true
      inverted: true
    filters:
      - delayed_off: 10ms
    on_press:
      - logger.log: Side Button Pressed
      - script.execute: buzzer_beep
    on_release:
      - output.turn_off: buzzer
    name: Side Button
    entity_category: diagnostic
  # Front Button
  - platform: gpio
    id: button_front
    pin:
      number: ${button_front_pin}
      allow_other_uses: true
      inverted: true
    filters:
      - delayed_off: 10ms
    on_press:
      - logger.log: Front Button Pressed
      - script.execute: buzzer_beep
    on_release:
      - output.turn_off: buzzer
    name: Front Button
    entity_category: diagnostic

#  - platform: gpio
#    id: pwr_hold
#    name: Power Hold
#    entity_category: diagnostic
#    pin:
#      number: ${pwr_mos_pin}
#      allow_other_uses: true
#      inverted: true
#    on_press:
#      then:
#        - logger.log: Power Hold
#    on_release:
#      then:
#        - logger.log: Power Hold Off

# Script for buzzer beep
script:
  - id: buzzer_on
    then:
      - output.turn_on: buzzer
      - output.ledc.set_frequency:
          id: buzzer
          frequency: "500Hz"
      - output.set_level:
          id: buzzer
          level: "1%"
  - id: buzzer_beep
    then:
      - output.turn_on: buzzer
      - output.ledc.set_frequency:
          id: buzzer
          frequency: "500Hz"
      - output.set_level:
          id: buzzer
          level: "1%"
      - delay: 50ms
      - output.turn_off: buzzer

sensor:
  # Battery voltage
  - platform: adc
    pin: ${bat_feed_back}
    id: bat_adc
    update_interval: 10s
    attenuation: 12db
    samples: 10
    accuracy_decimals: 3
    filters:
      - multiply: 2.0
      - median:
          window_size: 7
          send_every: 7
          send_first_at: 7
    name: "Battery Voltage"
    entity_category: diagnostic
    device_class: voltage
    unit_of_measurement: V
    disabled_by_default: true
    on_value:
      then:
        - component.update: bat_percent
  # Battery Percent
  - platform: template
    name: "Battery"
    id: bat_percent
    lambda: return id(bat_adc).state;
    accuracy_decimals: 0
    filters:
      - calibrate_linear:
          method: exact
          datapoints:
            - 0.00 -> 0.0
            - 3.3 -> 1.0
            - 3.39 -> 10.0
            - 3.75 -> 50.0
            - 4.11 -> 90.0
            - 4.2 -> 100.0
      - lambda: |-
          if (x <= 100) {
            return x;
          } else {
            return 100;
          }
          if (x <0) {
            return 0;
          }
    entity_category: diagnostic
    device_class: battery
    unit_of_measurement: "%"

deep_sleep:
  id: deep_sleep_battery
  run_duration: 120s
  sleep_duration: 180s
  wakeup_pin_mode: KEEP_AWAKE
#  wakeup_pin:
#    number: $power_mos_pin
#    allow_other_uses: true
  esp32_ext1_wakeup: 
    mode: ANY_HIGH
    pins:
#      - number: $rtc_wakeup_pin
      - number: ${pwr_mos_pin}
#        allow_other_uses: true
      - number: ${button_side_pin}
        allow_other_uses: true
      - number: ${button_front_pin}
        allow_other_uses: true

switch:
  # Power Hold
  - platform: template
    id: sw_pwr_hold
    restore_mode: ALWAYS_ON
    turn_on_action:
      then:
        - logger.log: Power Hold On
        - lambda: |-
            gpio_set_direction(GPIO_NUM_4, GPIO_MODE_OUTPUT);
            gpio_set_level(GPIO_NUM_4, 1);
            gpio_hold_en(GPIO_NUM_4);
            gpio_deep_sleep_hold_en();
    turn_off_action:
      then:
        - logger.log: Power Hold Off
        - lambda: |-
            gpio_set_direction(GPIO_NUM_4, GPIO_MODE_OUTPUT);
            gpio_set_level(GPIO_NUM_4, 0);
            gpio_hold_en(GPIO_NUM_4);
            gpio_deep_sleep_hold_en();
    name: Power Hold
    entity_category: config
    optimistic: true

text_sensor:
  - platform: template
    id: wakeup_cause
    lambda: return esp_sleep_get_wakeup_cause();
    filters:
      - lambda: |-
          if (x == 0) {
            return "ESP_SLEEP_WAKEUP_UNDEFINED";
          } else if (x == 1) {
            return "ESP_SLEEP_WAKEUP_ALL";
          } else if (x == 2) {
            return "ESP_SLEEP_WAKEUP_EXT0";
          } else if (x == 3) {
            return "ESP_SLEEP_WAKEUP_EXT1";
          } else if (x == 4) {
            return "ESP_SLEEP_WAKEUP_TIMER";
          } else if (x == 5) {
            return "ESP_SLEEP_WAKEUP_TOUCHPAD";
          } else if (x == 6) {
            return "ESP_SLEEP_WAKEUP_ULP";
          } else if (x == 7) {
            return "ESP_SLEEP_WAKEUP_GPIO";
          } else if (x == 8) {
            return "ESP_SLEEP_WAKEUP_UART";
          } else if (x == 9) {
            return "ESP_SLEEP_WAKEUP_WIFI";
          } else if (x == 10) {
            return "ESP_SLEEP_WAKEUP_COCPU";
          } else if (x == 11) {
            return "ESP_SLEEP_WAKEUP_COCPU_TRAP_TRIG";
          } else if (x == 12) {
            return "ESP_SLEEP_WAKEUP_BT";
          } else {
            return "UNKNOWN";
          }
    name: "Wakeup Cause"
    entity_category: diagnostic

# Audio not tested
#i2s_audio:
#  id: i2s_bus
#  i2s_lrclk_pin:
#    number: ${i2s_lrclk_pin}
#    allow_other_uses: ${hat_shared}
#  i2s_bclk_pin:
#    number: ${i2s_bclk_pin}
#    allow_other_uses: ${hat_shared}

#microphone:
#  - platform: i2s_audio
#    i2s_din_pin: ${mic_pin}
#    i2s_audio_id: i2s_bus
#    adc_type: external
#    pdm: true
#    id: mic