labels: [esp32, WS2812, RGB, RMT_LED, display]
---
# https://docs.m5stack.com/en/core/Atom-Matrix_v1.1
# Base functions for:
# M5Stack Atom Matrix v1.1
#

substitutions:
  device:
    model: "M5Stack Atom Matrix"
    rmt_symbols_block: 64
    framework:
      type: esp-idf

# Pins for this model
packages:
  pins: !include pins/m5stack_atom_lite.yaml

esphome:
  project:
    name: "M5Stack.Atom Matrix"

esp32:
# ESP32-PICO-D4@Dual-core processor, 240MHz
  variant: esp32
  flash_size: 4MB
  cpu_frequency: 240MHz
  framework:
    type: ${device.framework.type}
    advanced:
      compiler_optimization: PERF
      sram1_as_iram: true

wifi:
  enable_btm: true
  enable_rrm: true

light:
  - platform: esp32_rmt_led_strip
    id: rgb_led
    rgb_order: GRB
    pin: ${pin.light.rgb}
    num_leds: 25
    rmt_symbols: ${device.rmt_symbols_block * 2}
    chipset: ws2812
    color_correct: [35%, 35%, 35%]
    effects:
      - pulse:
      - strobe:
      - strobe:
          name: "Slow Blink" # 200ms on, 1500ms off
          colors:
            - state: true
              brightness: 25%
              red: 100%
              green: 0%
              blue: 0%
              duration: 500ms
              transition_length: 500ms
            - state: false
              duration: 2000ms
              transition_length: 1000ms
      - addressable_rainbow:
          width: 25
      - addressable_color_wipe:
      - addressable_scan:
          scan_width: 2
      - addressable_twinkle:
      - addressable_random_twinkle:
      - addressable_flicker:
    default_transition_length: 50ms
    restore_mode: ALWAYS_OFF
    name: "LED"
    on_turn_on:
      lambda: |-
        id(display_matrix)->set_enabled(false);
    on_turn_off:
      lambda: |-
        id(display_matrix)->set_enabled(true);

display:
  - platform: addressable_light
    addressable_light_id: rgb_led
    id: display_matrix
    width: 5
    height: 5
    # Display pixel map
    # 0,0 1,0 2,0 3,0 4,0
    # 0,1 1,1 2,1 3,1 4,1
    # 0,2 1,2 2,2 3,2 4,2
    # 0,3 1,3 2,3 3,3 4,3
    # 0,4 1,4 2,4 3,4 4,4
    update_interval: 100ms

# Button
binary_sensor:
  - platform: gpio
    id: btn_matrix
    name: Button
    entity_category: diagnostic
    pin:
      number: ${pin.btn}
      inverted: true
    filters:
      - delayed_off: 10ms
    on_press:
      - logger.log: Button Pressed
    on_click:
      min_length: 1000ms
      max_length: 5000ms
      then:
        - logger.log: Button Held
        - light.toggle: rgb_led
