---
# https://docs.m5stack.com/en/core/fire_v2.7
# Base functions for:
# M5Stack Fire
#

# Pins for this model
packages:
  pins: !include pins/m5stack_fire.yaml

i2c:
# Internal
  - id: i2c_internal
    sda: $i2c_int_sda_pin
    scl: $i2c_int_scl_pin
    scan: true

spi:
  clk_pin: $spi_clk_pin
  mosi_pin: $spi_mosi_pin
  miso_pin: $spi_miso_pin

# IR
#remote_transmitter:
#  pin: $ir_pin
#  carrier_duty_percent: 50%
#  rmt_symbols: 144

#display:
#  - platform: ili9xxx
#    id: display_lcd
#    model: M5STACK
#    cs_pin: $disp_cs_pin
#    dc_pin: $disp_dc_pin
#    reset_pin: $disp_rs_pin
#    lambda: |-
#      it.print(80, 0, id(roboto), Color(255, 255, 255), TextAlign::TOP_CENTER, "M5Stack Fire Test");

external_components:
  - source:
      type: git
      url: https://github.com/ssieb/custom_components
    components: [ip5306]

ip5306:
  battery_level:
    id: bat_percent
    name: "Battery"
    entity_category: diagnostic
    device_class: battery
    unit_of_measurement: "%"
  charger_connected:
    id: bat_connected
  charge_full:
    id: bat_full

# Internal LEDS
output:
  - platform: ledc # backlight output
    id: backlight_output
    pin: $disp_bl_pin

light:
  - platform: monochromatic # backlight
    id: backlight_light
    output: backlight_output
    default_transition_length: 100ms
    restore_mode: RESTORE_DEFAULT_ON
    initial_state:
      state: on
      brightness: 25%
    name: "Backlight"
    entity_category: config
  - platform: esp32_rmt_led_strip
    id: side_light
    rgb_order: GRB
    pin: $led_pin
    num_leds: 10
    rmt_channel: 1
    chipset: SK6812
    restore_mode: RESTORE_DEFAULT_OFF
    default_transition_length: 0s
    name: "Side Light"

# Microphone and Speaker
i2s_audio:
  i2s_lrclk_pin: $i2s_lrclk_pin

microphone:
  - platform: i2s_audio
    id: adc_mic
    adc_pin: $mic_pin
    adc_type: internal

media_player:
  - platform: i2s_audio
    id: media_player_out
    dac_type: internal
    mode: right
    name: "Internal Media Player"

# Buttons
binary_sensor:
  # Button A
  - platform: gpio
    id: btn_a
    name: "Button A"
    entity_category: diagnostic
    pin:
      number: $button_a_pin
      inverted: true
    filters:
      - delayed_off: 10ms
    on_press:
      then:
        - logger.log: Button A Pressed
  # Button B
  - platform: gpio
    id: btn_b
    name: "Button B"
    entity_category: diagnostic
    pin:
      number: $button_b_pin
      inverted: true
    filters:
      - delayed_off: 10ms
    on_press:
      then:
        - logger.log: Button B Pressed
  # Button C
  - platform: gpio
    id: btn_c
    name: "Button C"
    entity_category: diagnostic
    pin:
      number: $button_c_pin
      inverted: true
    filters:
      - delayed_off: 10ms
    on_press:
      then:
        - logger.log: Button C Pressed
