labels: [esp32s3, psram, BMI270, OV3660, camera, i2c]
---
# https://docs.m5stack.com/en/core/AtomS3R-M12
# https://docs.m5stack.com/en/homeassistant/camera/atoms3r_m12
# Base functions for:
# M5Stack AtomS3R-M12
#

# Pins for this model
packages:
  pins: !include pins/m5stack_atom_s3r.yaml
# Limit of 2 i2c buses on ESP32-S3, one already occupied by camera
# Include internal IMU or Grove/HAT i2c in top level device config
#  i2c_int: !include extension/internal_i2c.yaml
#  imu: !include module/chip_imu_bmi270.yaml

substitutions:
  time_timezone: "Europe/Oslo"
  mbus_i2c_shared: "false"
  module:
    internal:
      i2c_bus: i2c_internal
  device:
    model: "M5Stack Atom S3R-M12"
    rmt_symbols_block: 48
    framework:
      type: esp-idf

esphome:
  project:
    name: "M5Stack.Atom S3R-M12"
    version: "1.0.0"
  # on_boot:
  #   - priority: 800
  #     then:
  #       - lambda: |-
  #           gpio_set_direction(GPIO_NUM_18, GPIO_MODE_OUTPUT);
  #           gpio_set_level(GPIO_NUM_18, 0);
  #           vTaskDelay(pdMS_TO_TICKS(1500));

esp32:
# ESP32-S3-PICO-1-N8R8@Dual-core Xtensa LX7, up to 240MHz
# PSRAM: 8MB Octal
  variant: esp32s3
  flash_size: 8MB
  cpu_frequency: 240MHz
  framework:
    advanced:
      compiler_optimization: PERF
      execute_from_psram: true
      enable_idf_experimental_features: true
      loop_task_stack_size: 16384
      assertion_level: DISABLE
      enable_lwip_assert : false
    type: ${device.framework.type}
    sdkconfig_options:
      # Caching Optimizations
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_ESP32S3_INSTRUCTION_CACHE_32KB: "y"
      
      # PSRAM Integrations
      CONFIG_SPIRAM_ALLOW_STACK_EXTERNAL_MEMORY: "y"
      CONFIG_MBEDTLS_EXTERNAL_MEM_ALLOC: "y"
      
      # TLS and Logging
      CONFIG_MBEDTLS_SSL_PROTO_TLS1_3: "y"
      CONFIG_LOG_DEFAULT_LEVEL: "0"  # prevents "ESP-IDF" Guru Meditation Error
      
      # Camera Specifics
      CONFIG_CAMERA_TASK_STACK_SIZE: "8192"

psram:
  mode: octal
  speed: 80MHz

wifi:
  output_power: 10dB
  power_save_mode: light
  use_psram: true
  enable_btm: true
  enable_rrm: true

preferences:
  flash_write_interval: 30min

logger:
  logs:
    esp32_camera: DEBUG

external_components:
  - source: github://m5stack/esphome-yaml/components
    components: [ early_init ]

early_init:
  id: power_up_barrier
  pins:
    - pin:
        number: ${pin.cam.pwr}
      level: false
  delay: 500ms

i2c:
  - id: i2c_cam
    sda: ${pin.cam.sda}
    scl: ${pin.cam.scl}
    frequency: 100kHz
    timeout: 10ms
    scan: true

# IR
#remote_transmitter:
#  pin: ${pin.light.ir}
#  carrier_duty_percent: 50%
#  rmt_symbols: ${device.rmt_symbols_block}

esp32_camera:
  i2c_id: i2c_internal
  # PINS
  external_clock:
    pin: ${pin.cam.m_clk}
    frequency: 20MHz
  data_pins:
    - ${pin.cam.y2}
    - ${pin.cam.y3}
    - ${pin.cam.y4}
    - ${pin.cam.y5}
    - ${pin.cam.y6}
    - ${pin.cam.y7}
    - ${pin.cam.y8}
    - ${pin.cam.y9}
  vsync_pin: ${pin.cam.vs}
  href_pin: ${pin.cam.hs}
  pixel_clock_pin: ${pin.cam.p_clk}
  # Metadata
  id: espcam
  name: "Camera OV3640"
  # Image settings
  resolution: 800x600
  pixel_format: JPEG
  jpeg_quality: 20
  vertical_flip: false
  max_framerate: 2 fps
  frame_buffer_count: 2 # defaults to 1
  # Exposure
  aec_mode: auto
  aec2: true # defaults to false
  ae_level: 2
  agc_gain_ceiling: 8x
  # White balance
  wb_mode: auto

# If NOT JPEG pixel_format
#camera_encoder:
#  type: esp32_camera
#  quality: 70
#  buffer_size: 524288
#  buffer_expand_size: 2097152

sensor:
  - platform: internal_temperature
    name: "CPU Temperature"
    id: cpu_temperature
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement
    icon: "mdi:thermometer"
    update_interval: 5s
    entity_category: diagnostic

status_led:
  pin: ${pin.light.led}
