---
# https://docs.m5stack.com/en/core/M5CoreS3%20SE
# Base functions for:
# M5Stack Core S3SE
#
# https://community.home-assistant.io/t/m5stack-m5cores3-se-with-microwakeword/761965/5
# https://github.com/luka6000/wake-word-voice-assistants/blob/main/m5stack-coreS3-se/m5stack-coreS3-se-spk.yaml

substitutions:
  time_timezone: "Europe/Oslo"
  mbus_i2c_shared: "false"
  module:
    internal:
      i2c_bus: i2c_internal
  device:
    model: "M5Stack Core S3 SE"
    framework:
      type: esp-idf

# Pins for this model
packages:
  pins: !include pins/m5stack_core_s3se.yaml

esphome:
  project:
    name: "M5Stack.Core S3 SE"

esp32:
# ESP32-S3@Xtensa LX7 Dual-Core, 240MHz
# PSRAM: 8MB Quad
  variant: esp32s3
  flash_size: 16MB
  cpu_frequency: 240MHz
  framework:
    advanced:
      compiler_optimization: PERF
      execute_from_psram: true
    sdkconfig_options:
      # Cache optimizations for display graphics
      CONFIG_ESP32S3_DATA_CACHE_64KB: y
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: y
      CONFIG_ESP32S3_INSTRUCTION_CACHE_32KB: y
      # Memory allocation rules for graphics buffers
      CONFIG_SPIRAM_USE_CAPS_ALLOC: y
      CONFIG_SPIRAM_USE_MALLOC: y
    type: ${device.framework.type}

psram:
  mode: quad
  speed: 80MHz

wifi:
  enable_btm: true
  enable_rrm: true


logger:
  deassert_rts_dtr: true

#i2c:
# Int
#  - id: i2c_internal
#    sda:
#      number: ${pin.int.i2c.sda}
#      allow_other_uses: ${mbus_i2c_shared}
#    scl:
#      number: ${pin.int.i2c.scl}
#      allow_other_uses: ${mbus_i2c_shared}
#    frequency: ${i2c_internal_frequency}
#    scan: true
# Ext PINs
#  - id: i2c_bus
#    sda: ${pin.ext.i2c.mbus.sda}
#    scl: ${pin.ext.i2c.mbus.scl}
#    frequency: 200kHz
#    scan: true

spi:
  clk_pin: ${pin.int.spi.clk}
  mosi_pin: ${pin.int.spi.mosi}
  miso_pin: 
    number: ${pin.int.spi.miso}
    allow_other_uses: true

time:
  - platform: bm8563
    i2c_id: ${module.internal.i2c_bus}
    id: time_rtc
    address: 0x51
    update_interval: 15min
  - id: !extend time_homeassistant
    on_time_sync:
      - then:
          - bm8563.write_time:

external_components:
  - source: github://m5stack/esphome-yaml/components
    components: [axp2101, aw88298, aw9523b]

# PMU
axp2101:
  id: axp2101_pmu
  i2c_id: ${module.internal.i2c_bus}

# IO Expander
aw9523b:
  i2c_id: ${module.internal.i2c_bus}
  id: aw9523b_hub
  p0_drive_mode: PUSH_PULL
  interrupt_pin: ${pin.int.i2c.int}

#i2s_audio:
#  id: i2s_audio_bus
#  i2s_lrclk_pin: ${pin.audio.i2s_lrclk}
#  i2s_bclk_pin: ${pin.audio.i2s_bclk}
#  i2s_mclk_pin:
#    number: ${pin.audio.i2s_mclk}
#    ignore_strapping_warning: true
#audio_adc:
#  - platform: es7210
#    i2c_id: ${module.internal.i2c_bus}
#    id: adc_es7210
#    bits_per_sample: 16bit
#    sample_rate: 16000
#    mic_gain: 36
#audio_dac:
#  - platform: aw88298
#    i2c_id: ${module.internal.i2c_bus}
#    id: dac_aw88298
#    sample_rate: 48000
#microphone:
#  - platform: i2s_audio
#    i2s_audio_id: i2s_audio_bus
#    id: i2s_mic
#    i2s_din_pin: ${pin.audio.mic}
#    bits_per_sample: 16bit
#    sample_rate: 16000
#    adc_type: external
#speaker:
#  - platform: i2s_audio
#    i2s_audio_id: i2s_shared
#    id: speaker_i2s
#    dac_type: external
#    i2s_dout_pin: ${pin.audio.i2s_dout}
#    audio_dac: dac_aw88298

display:
  - platform: mipi_spi
    id: display_lcd
    model: ili9342
    cs_pin: ${pin.int.spi.disp.cs}
    dc_pin:
      number: ${pin.int.spi.disp.dc}
      allow_other_uses: true
    reset_pin:
      aw9523b_id: aw9523b_hub
      number: 9
    dimensions:
      height: 240
      width: 320
    transform:
      swap_xy: false
      mirror_x: false
      mirror_y: false
    invert_colors: true
    update_interval: 5s
    auto_clear_enabled: false

touchscreen:
  - platform: ft63x6
    i2c_id: ${module.internal.i2c_bus}
    id: touchscreen_ft63x6
#    update_interval: 20ms
#    interrupt_pin:
#      aw9523b_id: aw9523b_hub
#      number: 10
    reset_pin:
      aw9523b_id: aw9523b_hub
      number: 0
    on_touch:
      - then:
          - lambda: |-
                ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
                    touch.x,
                    touch.y,
                    touch.x_raw,
                    touch.y_raw
                    );  
          - if:
              condition:
                - light.is_off: backlight_light
              then:
                - light.turn_on:
                    id: backlight_light
                    brightness: 40%
#    on_update:
#      - logger.log:
#          format: Touch %d at (%d, %d)
#          args: [ 'touch->id', 'touch->x', 'touch->y' ]

binary_sensor:
  - platform: touchscreen
    id: touch
    name: Touchscreen
    entity_category: diagnostic
    x_min: 0
    x_max: 320
    y_min: 0
    y_max: 240
  # some aw9523b inputs (handle interrupts)
  - platform: gpio
    name: "ES_INT P0_3"
    pin:
      aw9523b_id: aw9523b_hub
      number: 3
    on_press:
      then:
        - logger.log: "ES7210 interrupt triggered"
    internal: true
  - platform: gpio
    name: "TF_SW P0_4"
    pin:
      aw9523b_id: aw9523b_hub
      number: 4 
    on_press:
      then:
        - logger.log: "TF_SW interrupt triggered"
    internal: true
  - platform: gpio
    name: "TOUCH_INT P1_2"
    pin:
      aw9523b_id: aw9523b_hub
      number: 10
    on_press:
      then:
        - logger.log: "TOUCH interrupt triggered"
    internal: true
  - platform: gpio
    name: "AW_INT P1_3"
    pin:
      aw9523b_id: aw9523b_hub
      number: 11
    on_press:
      then:
        - logger.log: "AW88298 interrupt triggered"
    internal: true

output:
  - platform: axp2101
    type: range
    channel: DLDO1
    id: backlight_output
    min_voltage: 2600
    max_voltage: 3300

  - platform: axp2101
    channel: ALDO1
    voltage: 1800

  - platform: axp2101
    channel: ALDO2
    voltage: 3300
  
  - platform: axp2101
    channel: BLDO1
    voltage: 2800
  
  - platform: axp2101
    channel: BLDO2
    voltage: 1500

#  - platform: axp2101
#    channel: DCDC1
#    voltage: 3300

#  - platform: axp2101
#    channel: DCDC3
#    voltage: 3300

# https://devices.esphome.io/devices/M5Stack-Fire#wifi-issues-due-to-gpio15
#  - platform: gpio
#    id: wifi_fix_output
#    pin: ${mbus23}

light:
  # White
  - platform: monochromatic
    id: backlight_light
    output: backlight_output
    default_transition_length: 250ms
    restore_mode: RESTORE_AND_ON
    initial_state:
      state: on
      brightness: 25%
    name: "Backlight"
    entity_category: config
    # on_state:
    #   - lambda: |-
    #       uint8_t light;
    #       if (id(axp2101).read_byte(0x99, &light))
    #         id(backlight).turn_on().set_brightness( (( light << 5 ) - 641 ) /255 );

switch:
  - platform: gpio
    id: sw_bus_out_en
    name: "BUS_OUT_EN"
    pin:
      aw9523b_id: aw9523b_hub
      number: 1
    # BUS_OUT_EN = 1
    restore_mode: RESTORE_DEFAULT_ON
    entity_category: config

  - platform: gpio
    id: sw_usb_otg_en
    name: "USB_OTG_EN"
    pin:
      aw9523b_id: aw9523b_hub
      number: 5
    # USB_OTG_EN = 0
    restore_mode: RESTORE_DEFAULT_OFF
    entity_category: config
    disabled_by_default: true

  - platform: gpio
    id: sw_boost_en
    name: "BOOST_EN"
    pin:
      aw9523b_id: aw9523b_hub
      number: 15
    # BOOST_EN
    restore_mode: RESTORE_DEFAULT_ON
    entity_category: config