---
# https://docs.m5stack.com/en/core/M5NanoC6
# Base functions for:
# M5Stack NanoC6
#

# Pins for this model
packages:
  pins: !include pins/m5stack_nano_c6.yaml
  status_led: !include ../features/system_status_led.yaml

esphome:
  project:
    name: "M5Stack.Nano C6"
#  platformio_options:
#    board_build.f_cpu: 160000000L
#    board_build.f_flash: 80000000L
#    board_build.flash_size: 4MB
#    build_flags: "-DBOARD_HAS_PSRAM"
#    board_build.arduino.memory_type: qio_opi

esp32:
  board: esp32-c6-devkitm-1
  variant: esp32c6
  flash_size: 4MB

# Enable status LED
status_led:
  id: status_light
  pin: ${pin.light.led}

switch:
  - platform: gpio
    id: rgb_switch
    pin: ${pin.int.rgb_pwr}
    restore_mode: RESTORE_DEFAULT_ON
    name: "RGB on/off"
    entity_category: config

# Configuration of onboard RGB LED
light:
  - platform: esp32_rmt_led_strip
    id: rgb_led
    rgb_order: GRB
    pin: ${pin.light.rgb}
    num_leds: 1
    chipset: WS2812
    rmt_channel: 1
    is_rgbw: true
    effects:
      - pulse:
      - strobe:
      - strobe:
          name: "Slow Blink" # 200ms on, 1500ms off
          colors:
            - state: true
              brightness: 25%
              red: 100%
              green: 0%
              blue: 0%
              duration: 500ms
              transition_length: 500ms
            - state: false
              duration: 2000ms
              transition_length: 1000ms
#      - addressable_flicker:
#      - addressable_rainbow:
#      - addressable_color_wipe:
#      - addressable_scan:
#      - addressable_twinkle:
    default_transition_length: 100ms
    initial_state:
      state: true
      brightness: 50%
      color_brightness: 100%
      red: 100%
      green: 0%
      blue: 0%
    name: "LED"
    entity_category: config

# Button
binary_sensor:
  - platform: gpio
    name: Button
    entity_category: diagnostic
    pin:
      number: ${pin.btn}
      inverted: true
    filters:
      - delayed_off: 10ms
    on_press:
      - logger.log: Button Pressed
    on_click:
      min_length: 1000ms
      max_length: 5000ms
      then:
        - logger.log: Button Held
        - light.turn_off:
            id: rgb_led
