---
# https://docs.m5stack.com/en/core/AtomS3
# Base functions for:
# M5Stack AtomS3
#

# Pins for this model
packages:
  pins: !include pins/m5stack_atom_s3.yaml

esphome:
  project:
    name: "M5Stack.Atom S3"

esp32:
  board: m5stack-atoms3
  variant: esp32s3

substitutions:
  gyro_i2c_bus: i2c_internal

spi:
  clk_pin: $spi_clk_pin
  mosi_pin: $spi_mosi_pin

# IR
remote_transmitter:
  pin: $ir_pin
  carrier_duty_percent: 50%

output:
  - platform: ledc
    id: backlight_output
    pin: $disp_bl_pin
    frequency: 500Hz
    min_power: 0.1
    max_power: 1.0
    zero_means_zero: true

light:
  # White
  - platform: monochromatic
    id: backlight_light
    output: backlight_output
    default_transition_length: 100ms
    restore_mode: RESTORE_AND_ON
    initial_state:
      state: on
      brightness: 25%
    name: "Backlight"
    entity_category: config

# Button
binary_sensor:
  - platform: gpio
    name: Button
    entity_category: diagnostic
    pin:
      number: $button_pin
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_off: 10ms
    on_press:
      then:
        - logger.log: Button Pressed
        - display.page.show_next: display_lcd

#display:
#  - platform: ili9xxx
#    model: st7789v
#    id: display_lcd
#    cs_pin: $disp_cs_pin
#    dc_pin: $disp_dc_pin
#    reset_pin: $disp_reset_pin
#    data_rate: 40Mhz
#    invert_colors: true
#    update_interval: 1s
#    dimensions:
#      height: 128
#      width: 128
#      offset_height: 2
#      offset_width: 1
    # Rotate 180deg
#    transform:
#      mirror_x: true
#      mirror_y: true
#    pages:

# Example configuration entry
sensor:
  - platform: mpu6886
    i2c_id: $gyro_i2c_bus
    id: mpu6886_sensor
    accel_x:
      id: accel_x_mpu6886
      name: "MPU6886 Accel X"
      entity_category: diagnostic
    accel_y:
      id: accel_y_mpu6886
      name: "MPU6886 Accel Y"
      entity_category: diagnostic
    accel_z:
      id: accel_z_mpu6886
      name: "MPU6886 Accel z"
      entity_category: diagnostic
    gyro_x:
      id: gyro_x_mpu6886
      name: "MPU6886 Gyro X"
      entity_category: diagnostic
    gyro_y:
      id: gyro_y_mpu6886
      name: "MPU6886 Gyro Y"
      entity_category: diagnostic
    gyro_z:
      id: gyro_z_mpu6886
      name: "MPU6886 Gyro z"
      entity_category: diagnostic
    temperature:
      id: temperature_mpu6886
      name: "MPU6886 Temperature"
      disabled_by_default: true
      device_class: "temperature"
      state_class: "measurement"
    address: 0x68
    update_interval: 10s