---
# PINs for Sunton module ESP32-S3 with 4.3" display
#

# Pins for this model
packages:
  pins: !include pins/sunton-8048s043c.yaml

esphome:
  project:
    name: 'Sunton.4,3" 800x480'
  platformio_options:
    build_flags: "-DBOARD_HAS_PSRAM"
    board_build.esp-idf.memory_type: qio_opi
    board_build.flash_mode: dio
    board_upload.maximum_ram_size: 524288

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 16MB
  framework:
    type: esp-idf
    # these versions prevent artifacting
    version: 5.0.0
    platform_version: 6.8.1
    # Required to achieve sufficient PSRAM bandwidth
    sdkconfig_options:
#      COMPILER_OPTIMIZATION_SIZE: y
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: y
      CONFIG_ESP32S3_DATA_CACHE_64KB: y
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: y
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y
      CONFIG_ESPTOOLPY_FLASHSIZE_16MB: y # fix warning about 2mb found
    advanced:
      compiler_optimization: PERF

wifi:
  enable_btm: true
  enable_rrm: true

psram:
  mode: octal
  speed: 80MHz

i2c:
  - id: i2c_internal
    sda: ${pin.int.i2c.sda}
    scl: ${pin.int.i2c.scl}

output:
  - platform: ledc
    id: backlight_output
    pin: ${pin.light.disp_bl}
    frequency: 1220Hz

light:
  # White
  - platform: monochromatic
    id: backlight_light
    output: backlight_output
    default_transition_length: 100ms
    restore_mode: RESTORE_AND_ON
    initial_state:
      state: on
      brightness: 25%
    name: "Backlight"
    entity_category: config

# https://community.home-assistant.io/t/esp32-8048s043-sunton-4-3-cyd-config/780603
display:
  - platform: rpi_dpi_rgb
    id: display_lcd
    dimensions:
      height: 480
      width: 800
    color_order: RGB
    rotation: 90
    de_pin: ${pin.int.disp.de}
    hsync_pin: ${pin.int.disp.hsync}
    vsync_pin: ${pin.int.disp.vsync}
    pclk_pin: ${pin.int.disp.pclk}
    pclk_inverted: true
    pclk_frequency: 14MHz
    hsync_front_porch: 8
    hsync_pulse_width: 4
    hsync_back_porch: 8
    vsync_front_porch: 8
    vsync_pulse_width: 4
    vsync_back_porch: 8
    data_pins:
      red: [ $pin.int.disp.red.r1, $pin.int.disp.red.r2, $pin.int.disp.red.r3, $pin.int.disp.red.r4, $pin.int.disp.red.r5 ]
      green: [ $pin.int.disp.green.g1, $pin.int.disp.green.g2, $pin.int.disp.green.g3, $pin.int.disp.green.g4, $pin.int.disp.green.g5, $pin.int.disp.green.g6 ]
      blue: [ $pin.int.disp.blue.b1, $pin.int.disp.blue.b2, $pin.int.disp.blue.b3, $pin.int.disp.blue.b4, $pin.int.disp.blue.b5 ]
    update_interval: never
    auto_clear_enabled: false

touchscreen:
  - platform: gt911
    i2c_id: i2c_internal
    address: 0x5D
    id: touchscreen_gt911
    update_interval: 16ms
#    on_update:
#      - logger.log:
#          format: Touch %d at (%d, %d)
#          args: [ 'touch->id', 'touch->x', 'touch->y' ]