labels: [esp32c3]
---
# https://github.com/Xinyuan-LilyGO/LilyGo-T-OI-PLUS
# Base functions for:
# LilyGo T-OI Plus v1.3

# Pins for this model
packages:
  pins: !include pins/ttgo_t_oi_plus.yaml

substitutions:
  device:
    model: 'ttGo T-OI'
    rmt_symbols_block: 48
    framework:
      type: esp-idf

esphome:
  project:
    name: 'LilyGo.T-OI Plus'
    version: "1.3"

esp32:
# ESP32-C3
  variant: esp32c3
  flash_size: 4MB
  cpu_frequency: 160MHz
  framework:
    advanced:
      compiler_optimization: PERF
      enable_idf_experimental_features: true
    type: ${device.framework.type}

wifi:
  enable_btm: true
  enable_rrm: true

ota:
  - platform: esphome
    allow_partition_access: true

# Enable status LED
status_led:
  id: status_light
  pin: ${pin.light.led}

sensor:
  # CPU Temperature
  - platform: internal_temperature
    name: "CPU Temperature"
    id: cpu_temperature
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement
    icon: "mdi:thermometer"
    update_interval: 5s
    entity_category: diagnostic
