labels: [esp32]
---
# Base functions for uPesy Wroom
#

# Pins for this model
packages:
  pins: !include pins/upesy_wroom.yaml

substitutions:
  device:
    model: "uPesy Wroom"
    rmt_symbols_block: 64
    framework:
      type: esp-idf

esp32:
# uPesy ESP-WROOM-32
#  board: upesy_wroom
  variant: esp32
  flash_size: 4MB
  cpu_frequency: 240MHz
  framework:
    type: ${device.framework.type}

status_led:
  pin: ${pin.light.led}