---
# https://www.waveshare.com/wiki/E-Paper_ESP32_Driver_Board
# Base functions for Waveshare e-paper ESP32 driver board
#

# Pins for this model
packages:
  pins: !include pins/upesy_wroom.yaml

substitutions:
  device:
    framework:
      type: esp-idf

esp32:
  board: upesy_wroom
    framework:
      type: ${device.framework.type}

status_led:
  pin: ${pin.light.led}