labels: [esp32p4, psram, i2c, mipi_csi, mipi_dsi]
---
# https://docs.waveshare.com/ESP32-P4-WIFI6
# Base functions for:
# Waveshare ESP32-P4-Wifi6
# --
# For REVISION 1.3
# --

# Pins for this model
packages:
  pins: !include pins/waveshare_p4_wifi6.yaml
  i2c_int: !include extension/internal_i2c.yaml

substitutions:
  extension:
    i2c:
      internal:
        frequency: 400kHz
  device:
    model: 'Waveshare P4-Wifi6'
    rmt_symbols_block: 48
    framework:
      type: esp-idf

esphome:
  project:
    name: 'Waveshare.ESP32-P4-Wifi6'
    version: "1.3"

esp32:
# ESP32-P4R32
# PSRAM: 32MB
  variant: esp32p4
  flash_size: 16MB
  cpu_frequency: 360MHz
  framework:
    advanced:
      compiler_optimization: PERF
      execute_from_psram: true
      enable_idf_experimental_features: true
    type: ${device.framework.type}

logger:
  hardware_uart: UART0

ota:
  - platform: esphome
    allow_partition_access: true

psram:
  speed: 200MHz

wifi:
  use_psram: true
  enable_btm: true
  enable_rrm: true

preferences:
  flash_write_interval: 5min

http_request:  # Needed by esp32_hosted-update and any JSON stuff
  buffer_size_rx: 2048

esp_ldo:
  # Force stable 3.3V to the Main Flash Memory
#  - id: ldo_flash_power
#    channel: 1
#    voltage: passthrough
#    allow_internal_channel: true
  # Force stable 3.3V to the High-Speed PSRAM
#  - id: ldo_psram_power
#    channel: 2
#    voltage: passthrough
#    allow_internal_channel: true

  # For display
  - id: ldo_dsi_power
    channel: 3
    voltage: 2.5V
  # For SD card
#  - id: ldo_sd_power
#    channel: 4
#    voltage: 2.7V

# Network hardware
esp32_hosted:
  active_high: true
  variant: ESP32C6
  reset_pin: ${pin.int.c6_hosted.rst}
  clk_pin: ${pin.int.c6_hosted.clk}
  cmd_pin: ${pin.int.c6_hosted.cmd}
  d0_pin: ${pin.int.c6_hosted.d0}
  d1_pin: ${pin.int.c6_hosted.d1}
  d2_pin: ${pin.int.c6_hosted.d2}
  d3_pin: ${pin.int.c6_hosted.d3}
  use_psram: true

# Firmware update for esp32_hosted ESP32-C6
update:
  - platform: esp32_hosted
    name: "C6 CoProcessor Update"
    icon: mdi:chip
    type: http
    source: https://esphome.github.io/esp-hosted-firmware/manifest/esp32c6.json
    update_interval: 6h

# Audio - speaker/mic
i2s_audio:
  - id: i2s_audio_bus
    i2s_lrclk_pin: ${pin.audio.i2s_lrclk}
    i2s_bclk_pin: ${pin.audio.i2s_bclk}
    i2s_mclk_pin: ${pin.audio.i2s_mclk}

audio_dac:
  - platform: es8311
    i2c_id: i2c_internal
    id: dac_es8311
    address: 0x18

#audio_adc:
#  - platform: es7210
#    i2c_id: i2c_internal
#    id: adc_es7210
#    address: 0x36

microphone:
  - platform: i2s_audio
    id: i2s_mic
    i2s_audio_id: i2s_audio_bus
    i2s_din_pin: ${pin.audio.mic}
    sample_rate: 16000
    bits_per_sample: 16bit
    adc_type: external
    channel: left

speaker:
  - platform: i2s_audio
    id: i2s_speaker
    i2s_audio_id: i2s_audio_bus
    i2s_dout_pin: ${pin.audio.spk}
    dac_type: external
    audio_dac: dac_es8311
    channel: mono
    num_channels: 1
    buffer_duration: 1000ms
    bits_per_sample: 16bit
    sample_rate: 16000

  - platform: mixer
    id: mixing_speaker
    output_speaker: i2s_speaker
    task_stack_in_psram: true
    source_speakers:
      - id: announcement_mixing_input
      - id: media_mixing_input

  - platform: resampler
    id: announcement_resampling_speaker
    output_speaker: announcement_mixing_input
    task_stack_in_psram: true

  - platform: resampler
    id: media_resampling_speaker
    output_speaker: media_mixing_input
    task_stack_in_psram: true

switch:
  # Speaker Amplifier Enable
  - platform: gpio
    id: speaker_enable
    pin: ${pin.audio.amp}
    restore_mode: ALWAYS_ON
    name: "Speaker Enable"
    icon: "mdi:volume-high"
    entity_category: config

  - platform: template
    id: mic_mute
    name: Microphone Mute
    icon: "mdi:microphone-off"
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
    entity_category: config
    on_turn_off:
        - microphone.unmute:
    on_turn_on:
        - microphone.mute:

sensor:
  - platform: sound_level
    id: sound_level_sensor
    passive: false
    measurement_duration: 2000ms
    rms:
      name: "Noise Level"
      id: average_loudness
      filters:
        - multiply: -1
  # CPU Temperature
  - platform: internal_temperature
    name: "CPU Temperature"
    id: cpu_temperature
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement
    icon: "mdi:thermometer"
    update_interval: 5s
    entity_category: diagnostic
