# required vars:
# - uid
# - entity_id

binary_sensor:
  - id: ${uid}_widget_sensor
    platform: homeassistant
    entity_id: ${entity_id}
    publish_initial_state: true
    on_state:
      - if:
          condition:
            - binary_sensor.is_on: ${uid}_widget_sensor
          then:
            - lvgl.widget.hide:
                - ${uid}_widget_unknown
                - ${uid}_widget_off
            - lvgl.widget.show:
                - ${uid}_widget_on
          else:
            - lvgl.widget.hide:
                - ${uid}_widget_unknown
                - ${uid}_widget_on
            - lvgl.widget.show:
                - ${uid}_widget_off
