---
# m5stack i2c Grove Port

substitutions:
  i2c_grove_frequency: 50kHz

i2c:
# Grove port
  - id: i2c_grove
    sda: $i2c_grove_sda_pin
    scl: $i2c_grove_scl_pin
    frequency: $i2c_grove_frequency
#    timeout: 5ms
    scan: true