---
# https://docs.m5stack.com/en/atom/atom_mate
# m5stack i2c HAT

# HAT Shared pins
substitutions:
  extension:
    i2c:
      hat:
        shared: "false"
        frequency: 50kHz

i2c:
# Mate HAT
  - id: i2c_hat
    sda:
      number: ${pin.ext.i2c.hat.sda}
      allow_other_uses: ${extension.i2c.hat.shared}
    scl:
      number: ${pin.ext.i2c.hat.scl}
      allow_other_uses: ${extension.i2c.hat.shared}
    frequency: ${extension.i2c.hat.frequency}
#    timeout: 10ms
    scan: false