---
# i2c internal

substitutions:
  i2c_internal_frequency: 200kHz

i2c:
# Internal
  - id: i2c_internal
    sda: $i2c_int_sda_pin
    scl: $i2c_int_scl_pin
    frequency: $i2c_internal_frequency
    scan: true