---
# i2c internal

substitutions:
  extension:
    i2c:
      internal:
        frequency: 100kHz

i2c:
# Internal
  - id: i2c_internal
    sda: ${pin.int.i2c.sda}
    scl: ${pin.int.i2c.scl}
    frequency: ${extension.i2c.internal.frequency}
#    timeout: 5ms
    scan: true