---
# m5stack mBus i2c

# Shared pins
substitutions:
  extension:
    i2c:
      mbus:
        shared: "false"
        frequency: 400kHz

i2c:
# mBus Extension
  - id: i2c_mbus
    sda:
      number: ${pin.ext.mbus.p17}
      allow_other_uses: ${extension.i2c.mbus.shared}
    scl:
      number: ${pin.ext.mbus.p18}
      allow_other_uses: ${extension.i2c.mbus.shared}
    frequency: ${extension.i2c.mbus.frequency}
#    timeout: 10ms
    scan: true