---
# m5stack mBus i2c

# Shared pins
substitutions:
  mbus_i2c_shared: "false"
  i2c_mbus_frequency: 400kHz

i2c:
# mBus Extension
  - id: i2c_mbus
    sda:
      number: ${pin.ext.mbus.p17}
      allow_other_uses: ${mbus_i2c_shared}
    scl:
      number: ${pin.ext.mbus.p18}
      allow_other_uses: ${mbus_i2c_shared}
    frequency: ${i2c_mbus_frequency}
#    timeout: 10ms
    scan: true