---
# https://docs.m5stack.com/en/unit/Unit-PaHub%20v2.1
# https://esphome.io/components/tca9548a.html
# https://community.home-assistant.io/t/m5-atoms3-lite-with-i2c-hub-pahub-2-m5-relay-kmeteriso-and-ext-io-gpio-extender-peripherals-in-esphome/737727/7
# m5stack Unit PaHub

substitutions:
  multiplexer_i2c_bus: i2c_grove

# i2c Multiplexer
tca9548a:
  - i2c_id: $multiplexer_i2c_bus
    id: multiplex_pa_hub
    address: 0x70
    channels:
      - bus_id: i2c_pa_hub_c0
        channel: 0
      - bus_id: i2c_pa_hub_c1
        channel: 1
      - bus_id: i2c_pa_hub_c2
        channel: 2
      - bus_id: i2c_pa_hub_c3
        channel: 3
      - bus_id: i2c_pa_hub_c4
        channel: 4
      - bus_id: i2c_pa_hub_c5
        channel: 5
