---
# Logger component
#
# The logger component automatically logs all log messages through the serial
# port and through MQTT topics.
#
# https://esphome.io/components/logger.html
#

substitutions:
  log_level: DEBUG

logger:
  id: component_logger
  level: DEBUG
  initial_level: $log_level
  baus_rate: 0
#  logs:
#    light: INFO

select:
  - platform: logger
    id: logger_select
    name: "Logger Select"
    entity_category: config
    disabled_by_default: true