---
# Status
#
# Device status
# WiFi signal strength, connectivity and uptime
#

# https://esphome.io/components/binary_sensor/status.html
binary_sensor:
  - platform: status
    name: "Status"
    device_class: "connectivity"
    entity_category: diagnostic

sensor:
  # https://esphome.io/components/sensor/uptime.html
  - platform: uptime
    id: sensor_uptime
    type: timestamp
    name: "Uptime"
    device_class: timestamp
    entity_category: diagnostic
