---
# Time
#
# The time component allows you to set up real time clock time sources
# for ESPHome.
#
# https://esphome.io/components/time.html
#
substitutions:
  time_timezone: "Europe/Oslo"

time:
  # https://esphome.io/components/time.html#home-assistant-time-source
  - platform: homeassistant
    id: time_homeassistant
    timezone: "${time_timezone}"

  # https://esphome.io/components/time.html#sntp-time-source
  - platform: sntp
    id: time_sntp
    timezone: "${time_timezone}"