---
# Wi-Fi component package
#
# Contains my common Wi-Fi setup.
#
# https://esphome.io/components/wifi.html
#
wifi:
  id: component_wifi
#  ssid: !secret wifi_ssid
#  password: !secret wifi_password
#  fast_connect: true
#  reboot_timeout: 30min
#  passive_scan: true

sensor:
  # https://esphome.io/components/sensor/wifi_signal.html
  - platform: wifi_signal
    id: sensor_wifi_signal
    name: "WiFi Signal dB"
    entity_category: diagnostic
    device_class: "signal_strength"
    state_class: measurement
    disabled_by_default: true
    update_interval: 60s
    filters:
      - or:
          - heartbeat: 900s
          - delta: 1

text_sensor:
  # https://esphome.io/components/text_sensor/wifi_info
  - platform: wifi_info
    ip_address:
      id: sensor_ip_address
      name: "IP Address"
      entity_category: diagnostic
      disabled_by_default: true
      address_0:
        id: sensor_ip_address_0
        name: "IP Address 0"
        entity_category: diagnostic
        disabled_by_default: true
      address_1:
        id: sensor_ip_address_1
        name: "IP Address 1"
        entity_category: diagnostic
        disabled_by_default: true
      address_2:
        id: sensor_ip_address_2
        name: "IP Address 2"
        entity_category: diagnostic
        disabled_by_default: true
      address_3:
        id: sensor_ip_address_3
        name: "IP Address 3"
        entity_category: diagnostic
        disabled_by_default: true
      address_4:
        id: sensor_ip_address_4
        name: "IP Address 4"
        entity_category: diagnostic
        disabled_by_default: true
    ssid:
      id: sensor_ssid
      name: "Connected SSID"
      entity_category: diagnostic
      disabled_by_default: true
    mac_address:
      id: sensor_mac_address
      name: "Mac Address"
      entity_category: diagnostic
      disabled_by_default: true
