# required vars:
# - uid
# - entity_id

sensor:
  - id: ${uid}_homeassistant
    platform: homeassistant
    entity_id: ${entity_id}
    on_value:
      - lvgl.label.update:
          id: ${uid}_widget_text
          text:
            format: "%.0f"
            args: [ 'x' ]